### ISSUE TITLE
Failure during planning phase when node pool resources are exhausted

### ISSUE THREAD

**Issue by coryodaniel** [terraform-providers/terraform-provider-google#4116] opened 2019-07-26 17:25 UTC
When a machine type is exhausted in a zone, terraform plan fails making it impossible to destroy, taint, or change the nodepool. 

To continue you have to delete the node pool in the GCP UI or CLI and then remove it from the terraform state.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

Applies to any GCP machine type that is exhausted.

### Debug Output

Error: Error reading NodePool "pool-worker-preemptible" from cluster "CLUSTER_NAME": Nodepool "pool-worker-preemptible" has status "RUNNING_WITH_ERROR" with message "asia-northeast1-a: Deploy error: Not all instances running in IGM after 4m4.752299662s. Expect 1. Current errors: [ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS]: Instance 'INSTANCE_NAME' creation failed: The zone 'projects/ox-delivery-prod/zones/asia-northeast1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'."

### Expected Behavior

The plan reads the current state and does not fail.

### Actual Behavior

The plan reads and encounters an error on the resource and crashes.

### Steps to Reproduce

1. `terraform apply`
2. Wait for the machine type to be exhausted in a region
3. `terraform plan` # this will crash

### Important Factoids

Machine type is exhausted. Currently requesting n1-standard-96 pvms. These are easy to exhaust (and I know we shouldn't be using them), but the bug exists for other machine types as well.

### References

* May be related to https://github.com/terraform-providers/terraform-provider-google/issues/3304

**Comment by WillBeebe** [comment] 2019-07-26 17:26
We're having this issue as well.

**Comment by paddycarver** [comment] 2019-08-02 10:00
I think this is definitely related to #3304. I think the crux of the problem is that we need to detect an error for when resources are exhausted, but we need to distinguish that from other errors, and I think that's trickier than it would appear at first blush.

**Comment by rileykarson** [comment] 2019-12-16 18:20
Closing as dupe of #3304

**Closed by rileykarson** 2019-12-16 18:20 UTC
Labels: bug
