### ISSUE TITLE
google_container_cluster crash when daily_maintenance_window unspecified

### ISSUE THREAD

**Issue by johnwheffner** [terraform-providers/terraform-provider-google#4028] opened 2019-07-15 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.4
+ provider.google v2.10.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

```tf
provider "google" {
  project = "REDACTED"
  region  = "us-east1"
  version = "~> 2.10"
}


resource "google_container_cluster" "jheffner-test" {
  name = "jheffner-test"

  location = "us-east1-d"
  initial_node_count = 1

  node_config {
    machine_type = "n1-standard-1"

    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
    ]
  }

//  maintenance_policy {
//    daily_maintenance_window {
//      start_time = "04:00"
//    }
//  }
}
```

### Panic Output

https://gist.github.com/johnwheffner/0d5c4f07f34e60a99f8e1b1150210561

### Actual Behavior

`terraform apply` failed with a crash

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The stack trace pointed to a crash accessing the maintenance policy.  I added a `maintenance_policy.daily_maintenance_window` (commented out in the above-pasted config) and it does not crash.

### References

* #0000

**Comment by slevenick** [comment] 2019-07-15 16:26
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/4010

The next release of the terraform google provider will fix this issue, release expected tomorrow. Until then specifying a maintenance window should be a workaround

**Closed by slevenick** 2019-07-15 16:26 UTC
Labels: bug
