### ISSUE TITLE
FAIL: TestProvider: id is a reserved field name for a resource with latests github.com/hashicorp/terraform

### ISSUE THREAD

**Issue by cthiel** [terraform-providers/terraform-provider-google#353] opened 2017-08-24 12:14 UTC
I'm building & testing terraform-provider-google with the latests github.com/hashicorp/terraform and ran into this test failure:

```
--- FAIL: TestProvider (0.01s)
provider_test.go:26: err: 5 errors occurred:
* resource google_project: id is a reserved field name for a resource
* resource google_compute_target_https_proxy: id is a reserved field name for a resource
* resource google_compute_target_http_proxy: id is a reserved field name for a resource
* resource google_compute_url_map: id is a reserved field name for a resource
* resource google_compute_ssl_certificate: id is a reserved field name for a resource
```

Just removing the id entries from the schema for the respective resources fixes the tests, but I'm unsure about the side-effects this might cause.

**Comment by cthiel** [comment] 2017-08-24 12:17
This doesn't seem to be happening with the vendored version of hashicorp/terraform in https://github.com/terraform-providers/terraform-provider-google/tree/master/vendor/github.com/hashicorp/terraform

**Comment by selmanj** [comment] 2017-08-24 16:58
Looks like the warning code was introduced here: https://github.com/hashicorp/terraform/pull/15522

**Comment by paddycarver** [comment] 2017-08-28 18:57
This appears to have been introduced into this repo in #302. Weirdly, this seems to pass in our CI? It also passes for me locally. Can you let us know what revision you're building under and what command you're using, @cthiel?

That aside, those resources _are_ subtly broke at the moment until those things are fixed. I think, for some resources, the breakage isn't really material, but for others it may make a difference. From my understanding, resources that have an `id` field will always return the zero value as the value for that field, seeing it as unset even if the user specifies something in their config.

**Comment by cthiel** [comment] 2017-08-28 19:13
I'm building against hashicorp/terraform master as of last week, ie not using the vendored version (at all). You should be able to update the vendored version using govendor and switch to master instead of the 0.10.0 tag. (Sorry I don't have commands ready to reproduce this easily.)

**Comment by paddycarver** [comment] 2017-08-28 19:29
So you're explicitly ignoring the `vendored` version? Can I ask how, and why?

The main reason I ask is I seem to be unable to reproduce this.

**Comment by cthiel** [comment] 2017-08-28 20:21
This is mostly due to the fact that the build system that I'm using is discouraging vendored dependencies. Also, it seems risky to have terraform-providers/terraform-provider-google vendor much and then diverge from master, which then later requires more work to be done to re-base and integrate, like this bug is showing.

(I'm happy to explain in more detail via mail.)

**Comment by paddycarver** [comment] 2017-08-28 21:02
Hey @cthiel, thanks for the clarification. While this specific instance is something we're definitely interested in fixing, as it represents code that's broken in the vendored directory, I just want to be clear that we explicitly do not track master of all the dependencies, and builds that don't use our pinned, vendored dependencies are likely to fail, possibly in destructive and surprising ways. They're explicitly not supported.

As for diverging, we don't really ever diverge from any of our dependencies, that I know of. But we do lag. We have so many providers, each with so many dependencies, that keeping all of them working against master all the time is an unrealistic goal. So we update dependencies as they get bug fixes and improvements that are used in the provider, making the changes necessary at that time.

That being said, because this specific change doesn't introduce the break, it just exposes it, I'm definitely interested in getting these resources updated to work correctly.

**Comment by cthiel** [comment] 2017-08-28 21:17
Sure, thanks for the clarifications and looking into fixing the provider!

**Comment by radeksimko** [comment] 2017-09-05 06:24
> From my understanding, resources that have an id field will always return the zero value as the value for that field, seeing it as unset even if the user specifies something in their config.

This certainly shouldn't be happening. The intention of the extra check I introduced a while back was only to force providers to clean up the schema by removing fields which have _no effect_, `id` being one of them.

https://github.com/hashicorp/terraform/blob/67ceb1ab07acd55ebc0d7b6efb39019e73fd1888/helper/resource/map.go#L79

Based on ^ that the ID should always be set in the state, if `d.SetId()` is called. If it isn't called then the resource is more significantly broken already, b/c much of the code relies on non-empty ID being the guarantor of resource existence.

**Comment by paddycarver** [comment] 2017-09-06 23:18
@radeksimko this is my understanding based on https://github.com/hashicorp/terraform/pull/10425#issuecomment-273914750 Basically, your check didn't break things, just exposed things that were already broken. So even though `d.SetId` and `d.Set("id")` were both called, `d.Get("id")` returned the empty string--though `d.GetId` would hypothetically work. Basically, it's `d.Get` not the ID writing that's broken when `id` is a field. If memory serves.

But the upshot of this is that we're using a reserved name as a field, we shouldn't be, and the new check doesn't break code, it just tells us code we broke long ago is broken. :) I'll open PRs to migrate off `id` and onto something not reserved.

**Comment by paddycarver** [comment] 2017-12-07 20:29
All uses of `id` _should_ be gone from the provider now, so I'm going to close this out. Feel free to reopen if it crops back up again!

**Closed by paddycarver** 2017-12-07 20:29 UTC
Labels: bug
