### ISSUE TITLE
Import google_sql_database_instance does not work 

### ISSUE THREAD

**Issue by joshughes** [terraform-providers/terraform-provider-google#1929] opened 2018-08-22 22:56 UTC
```
 terraform import  module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master offorl-master
module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master: Importing from ID "offorl-master"...
module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master: Import complete!
  Imported google_sql_database_instance (ID: offorl-master)
module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master: Refreshing state... (ID: offorl-master)

Error: module.offorl.provider.kubernetes: 1:3: unknown variable accessed: var.k8_config_context in:

${var.k8_config_context}



Error: module.offorl.module.6rs_software.provider.kubernetes: 1:3: unknown variable accessed: var.k8_config_context in:

${var.k8_config_context}



Error: module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master (import id: offorl-master): 1 error(s) occurred:

* import module.offorl.module.postgres-cloud-sql.google_sql_database_instance.master result: offorl-master: google_sql_database_instance.master: project: required field is not set


Releasing state lock. This may take a few moments...
```

```
Terraform v0.11.7

+ provider.google v1.17.1
```

**Comment by emilymye** [comment] 2018-08-22 23:29
Looks like the import doesn't set the project, will get a fix out soon. There's other things going on in these logs that I think are separate (k8s provider) so I'm just going to ignore those for now.

**Comment by paddycarver** [comment] 2018-08-22 23:48
I think this is a duplicate of #1410.

**Closed** 2018-08-28 23:51 UTC
