### ISSUE TITLE
Was there an outage this morning between 9:47-10:05 PST 2019-11-15?

### ISSUE THREAD

**Issue by byoshimi** [terraform-providers/terraform-provider-google#4920] opened 2019-11-15 20:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

all

### Affected Resource(s)

* google_XXXXX

### Debug Output

Error installing provider "google": bad response code: 403.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

### Panic Output

none

### Expected Behavior

No code changes were made.  Same terraform init succeeded before and after this time range.

### Actual Behavior

terraform failed with return code -1

### Steps to Reproduce

Not reproducable.

### References

* #0000

**Comment by paddycarver** [comment] 2019-11-15 21:27
Hey @byoshimi,

Yes, I can confirm there was a brief period where users attempting to download the terraform-provider-google version 3.0.0-beta.1 binary this morning would have received a 403 error code. That would mean users of Terraform 0.11 without a major version pinned as their provider version, and users of Terraform 0.12 without any provider version constraints set at all.

The 3.0.0-beta.1 release was only intended to be available for Terraform 0.12 users, but due to an error in our release process, it was unintentionally available to users of 0.11 and listed as the latest available version of the provider without any opt-in. As we worked to mitigate this, the linux_amd64 binary for version 3.0.0-beta.1 of terraform-provider-google became unavailable for a short period of time.

We're still working to ensure this situation is resolved, but at this time all `terraform init`s should behave as normal, and only users of Terraform 0.12 with either no provider constraints or a provider constraint that explicitly includes `3.0.0-beta.1` under the rules of semver should receive version 3.0.0-beta.1 of the provider. Everyone else should receive version 2.20.0 of the provider.

My apologies for any inconvenience this has caused.

**Comment by byoshimi** [comment] 2019-11-15 21:48
Cool. Thanks for the update!

**Comment by paddycarver** [comment] 2019-11-15 21:52
I'm going to close this issue, as there's no further action it requires, but if people are still getting version 3.0.0-beta.1 of the provider and believe they should not be, please open an issue and let us know so we can look into it. When you do, please include your operating system (e.g., linux, macos, etc.) and your processor architecture (amd64, i386, arm, etc.) to aid our debugging. Sorry for the issues, all.

**Closed by paddycarver** 2019-11-15 21:52 UTC
Labels: bug
