### ISSUE TITLE
Stackdriver Monitoring Provider

### ISSUE THREAD

**Issue by Mistobaan** [terraform-providers/terraform-provider-google#1044] opened 2018-02-03 23:18 UTC
Is there any plans to create a stackdriver provider for monitoring ?

something similar to [datadog's provider](https://www.terraform.io/docs/providers/datadog/r/user.html)

API https://cloud.google.com/monitoring/api/ref_v3/rest/

**Comment by rosbo** [comment] 2018-02-05 18:48
Hi Fabrizio,

I believe @srivasta was working on this. @srivasta, can you post an update about your progress on this?

Thank you

**Comment by srivasta** [comment] 2018-02-13 19:08
I had started working with the stackdriver V3 API which was initially whitelist only. It has been published, so the work can be proceed now. I have a private branch that started working with it, but it is not yet complete. I should be able to get back to working on it next week (there is a work based exercise this week that is making availability sketchy)

**Comment by sdouche** [comment] 2018-04-08 01:05
Hi,
Any update on this? The StackDriver Monitoring v3 API is now in beta, and it would be cool to use it with Terraform.

Regards.

**Comment by robolmos** [comment] 2018-05-17 02:27
This would be a helpful provider to have.

**Comment by mDantas** [comment] 2018-06-08 02:55
Very excited to use this. Thanks @srivasta !

**Comment by dictvm** [comment] 2018-06-11 14:51
@srivasta are you still on this?

**Comment by AndrewFarley** [comment] 2018-06-24 21:55
+1 Ping, inquiring minds want/need to use this feature in Terraform.  :)

**Comment by danawillow** [comment] 2018-07-02 17:09
Hey all, this is currently being actively worked on. Stay tuned :)

**Comment by shotarohorai** [comment] 2018-08-03 09:28
I am very excited and eager to use this.

How is this going on? @danawillow 
I hope you can tell when it is available.

Thank you so much again for you work 😃.

**Comment by danawillow** [comment] 2018-08-03 16:21
I'm excited too! We've had a few people working on this over its lifetime, which is why it's been taking so long. We do have someone assigned to it now, who I expect will be the person to finally finish it up. I'd expect the code to be ready within the next 2-3 weeks, but if it isn't, feel free to ping me for another update.

**Comment by Zamyatin** [comment] 2018-08-24 14:51
Hey @danawillow was wondering on an update. We have been watching this issue evolve and are quite excited to see how implementation works.  I actually had a reminder set to hit y'all up :) Any news?

**Comment by AndrewFarley** [comment] 2018-08-28 18:10
Looking forward to updates, and would happily test alpha/betas and provide feedback.  :)  Let us know!

**Comment by hayesgm** [comment] 2018-09-06 00:39
Happy also to hear a bit of updates here for forecasting.

**Comment by danawillow** [comment] 2018-09-06 01:53
Sorry all, I was out on vacation last week and @Sirgitsalot is out all this week, so hopefully next week we'll have some news for you. #1967 is the first PR for this, which has some necessary prereqs.

**Comment by sudoforge** [comment] 2018-09-07 14:26
Please refrain from adding comments that don't provide value, instead, prefer using [reactions][0] to show your support for an issue.

This avoids sending out an email, or otherwise generating a notification for everyone subscribed to a thread.

[0]: https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/

**Comment by chrisst** [comment] 2018-09-21 01:51
![potato](https://user-images.githubusercontent.com/1569002/45855649-f48a7180-bd05-11e8-8c66-9cefc5a5b551.gif)
@SirGitsalot had to get pulled off, so I'll be working on this now.

**Comment by chrisst** [comment] 2018-10-09 18:36
The first resource is out here https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html

I'll continue to add some of the others soon but I wanted to make sure to get alert policy in rather then let it get backed up behind several other resources.

**Comment by chrisst** [comment] 2018-11-13 22:03
Stackdriver Groups: https://github.com/terraform-providers/terraform-provider-google/pull/2451

**Comment by chrisst** [comment] 2018-11-13 22:04
Stackdriver Notification Channels: https://github.com/terraform-providers/terraform-provider-google/pull/2452

**Comment by chrisst** [comment] 2018-11-28 18:44
Uptime Checks: https://github.com/terraform-providers/terraform-provider-google/pull/2502

**Comment by chrisst** [comment] 2018-12-14 19:59
All of the stackdriver resources that are available in the apis got released in v1.20.0 this morning. Closing this now, if there are new features or bugs please open new tickets.

**Closed by chrisst** 2018-12-14 19:59 UTC
Labels: enhancement, new-resource

**Comment by mdz** [comment] 2018-12-16 02:48
Thanks, @chrisst!

**Comment by dannycohn** [comment] 2018-12-17 14:59
@chrisst I don't see any documentation for [creating log metrics](https://cloud.google.com/logging/docs/logs-based-metrics/counter-metrics) via TF. Am I missing something?

**Comment by chrisst** [comment] 2018-12-17 18:02
@dannycohn I'm keeping this PR scoped to the [stackdriver monitoring api](https://cloud.google.com/monitoring/api/ref_v3/rest/) as "stackdriver" is now a whole suite of different apis. Creating log metrics is under the logging.googleapis.com namespace so I didn't include it in these additions, but please file a new issue requesting it and we'll get to it as soon as we can!

**Comment by dannycohn** [comment] 2018-12-17 18:11
> @dannycohn I'm keeping this PR scoped to the [stackdriver monitoring api](https://cloud.google.com/monitoring/api/ref_v3/rest/) as "stackdriver" is now a whole suite of different apis. Creating log metrics is under the logging.googleapis.com namespace so I didn't include it in these additions, but please file a new issue requesting it and we'll get to it as soon as we can!

Looks like one exists https://github.com/terraform-providers/terraform-provider-google/issues/1236

**Comment by sergei-ivanov** [comment] 2018-12-17 19:36
I updated the provider and gave it a go today. Unfortunately, the documentation on Terraform site has not been updated yet (at the time of writing), so I had to go back to the PRs and look up the resource descriptions there.

I was able to import the existing uptime checks and alerting policies, and reconcile the terraform view against the actual state. It looks like email notification channels are created ad hoc when editing the policy, but it was possible to pre-create them via terraform and reuse across a number of alerting policies.

The only snag is that after reapplying the alerting policies that used to have uptime checks in their conditions, these conditions are no longer recognised/displayed as uptime checks in the cloud console. Instead they look like ad hoc custom conditions. This is probably a Google Cloud thing, because I have done `gcloud alpha monitoring policies list` before and after applying terraform changes, and there are no differences in the conditions there.

**Comment by chrisst** [comment] 2018-12-17 21:16
@sergei-ivanov I added an uptime check and alert policy via the UI and imported them into TF but running apply (after I had resolved all the diffs) hasn't changed how the UI displays the alert policy. If you open a bug with sufficient repro steps and some screen shots I'd be happy to talk with the stack driver team and see if it's a bug upstream.

**Comment by sergei-ivanov** [comment] 2018-12-17 22:08
@chrisst have you tried changing it slightly before applying to force a change through the API? In my case the applied difference was in display name and the list of notifications (which resulted in an in-place modification). It was an old policy introduced a couple of months ago by hand, and I was eager to finally bring it under terraform. I'll try to set up a test policy manually tomorrow and see if I can reproduce the problem in my environment.

**Comment by sergei-ivanov** [comment] 2018-12-18 17:08
I have found out that if I set up an uptime check from scratch in the Cloud Console UI and import it into Terraform, then it is managed by Terraform just fine, and recognised as uptime check by Cloud Console UI. Apparently there's been some change in the way the uptime check maps into raw metrics filter, and retrofitting that change into the old filters in Terraform resulted in them being recognised as uptime checks in the UI again. So that seems to be a non-issue. I'll raise separate bugs / feature requests for other issues that I've found during my testing.
Thank you for a great piece of work!
