### ISSUE TITLE
Support node groups and node templates creation

### ISSUE THREAD

**Issue by prbobba** [terraform-providers/terraform-provider-google#3402] opened 2019-04-09 10:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I am trying to build an e2e use case for provisioning compute in sole tenant node. I saw an issue( #2700 ) which, if addressed, can support provisioning to existing node groups. My use case is to create all the prereqs for this -- node groups and node templates as well.

### References

* #2700

**Comment by emilymye** [comment] 2019-04-16 20:12
I'm going to go ahead and close this because it is a duplicate of #2700, but we are currently working on this.

**Closed by emilymye** 2019-04-16 20:12 UTC
Labels: enhancement
