### ISSUE TITLE
scheduling / automatic_restart is not detected for change

### ISSUE THREAD

**Issue by tpoindessous** [terraform-providers/terraform-provider-google#4668] opened 2019-10-14 08:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.12.10
provider : 2.17.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "default" {
  name         = "${var.vm_instance_name}"
  machine_type = "${var.vm_instance_machine_type}"
  zone         = "${var.vm_instance_zone}"

  tags = "${var.vm_instance_tags}"

  boot_disk {
    initialize_params {
      image = "${var.vm_image}"
      size  = "${var.vm_instance_disk_size}"
    }

    auto_delete = "${var.vm_disk_autodelete}"
  }

  labels = "${var.vm_instance_labels}"

  network_interface {
    access_config {}
    subnetwork    = "${var.vm_subnetwork}"
  }
}
```

### Expected Behavior

I created the VM with TF code. Then with the webconsole, I changed scheduling / automatic_restart to false.
I can see the change if I do a `terraform refresh ; terraform show`
```
    scheduling {
        automatic_restart   = false
        on_host_maintenance = "MIGRATE"
        preemptible         = false
    }
```

When I ask for a `terraform plan`, Terraform should tell me that scheduling / automatic_restart is not the default value.
### Actual Behavior

```
No changes. Infrastructure is up-to-date.
```
### Important Factoids

I got hit by issue https://github.com/terraform-providers/terraform-provider-google/issues/1947 and I have a LOT of VM which are set to automatic_restart to false and Terraform can't tell me that I need to change those VM.
 

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/1947

**Comment by slevenick** [comment] 2019-10-14 17:18
I don't believe this is possible without changing the behavior of the `scheduling` block. The `scheduling` block is marked as `Computed` which means if there is no defined value it will take whatever is returned by the API. So when you change the `automatic_restart` value behind the scenes it doesn't create a diff because terraform will accept whatever the API returns for the entire block as correct.

If you add a `scheduling` block with `automatic_restart = true` it should update this field.

**Closed by slevenick** 2019-10-14 17:18 UTC
Labels: bug

**Comment by tpoindessous** [comment] 2019-10-14 19:30
Thanks @slevenick for the explanation. I will try to propose a PR for the documentation.

But there is something , I don't understand.

If I put a 
```
scheduling {}
```
block in my code (without `automatic_restart` line), then TF will detect that this boolean is not set to the default value and then it will propose to change it.

So TF can consider that this `scheduling` block is always set and try to detect if it should propose change.

What do you think of this ?

**Comment by slevenick** [comment] 2019-10-14 20:59
Adding `scheduling {}` is effectively specifying that the scheduling block should have all the default values. 

This is different from saying that you don't care what exists within the scheduling block (which is what not declaring it means)

The issue is that changing the `scheduling` block to always default `automatic_restart` would involve changes to the behavior of other fields within the block. Technically it would be possible, and you could reopen this issue and we could categorize it as an enhancement

**Comment by duijf** [comment] 2019-10-29 15:44
> This is different from saying that you don't care what exists within the scheduling block (which is what not declaring it means)

Just ran into this behavior. I would like to mention that this is quite unintuitive to me.

It would be helpful to mention this in the [documentation of `google_compute_instance`](https://www.terraform.io/docs/providers/google/r/compute_instance.html).

Here is what my thought process was while reading the docs:

 - Read the docs, see the defaults for scheduling.
 - Conclude that the defaults are what I want.
 - Therefore, omit the scheduling block in my Terraform code.

I think a lot more people read that page and conclude: "if you ommit it, defaults are chosen". Not: "if you ommit it, a undocumented uninitialized value is chosen".

(If you have to opt in to the defaults, then they shouldn't be called defaults)
