### ISSUE TITLE
google_compute_url_map fails to re-apply changes after manual modification in cloud console

### ISSUE THREAD

**Issue by bbrouwer** [terraform-providers/terraform-provider-google#2543] opened 2018-11-29 20:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.10
+ provider.google v1.18.0
+ provider.null v1.0.0
```

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

* [url_map.tf](https://gist.github.com/bbrouwer/7844251c930f76be4cf86db1a621025b#file-url_map-tf)

### Debug Output

* [tf-debug.log](https://gist.github.com/bbrouwer/7844251c930f76be4cf86db1a621025b#file-tf-debug-log)

### Expected Behavior

Applies the configuration without error

### Actual Behavior

`Error, failed to update Url Map naoo-url-map: googleapi: Error 400: Invalid value for field 'resource': ''. Host rules conflict, invalid`

### Steps to Reproduce

1. `terraform apply` when the url map does not exist. This succeeds.
2. Modify the url-map in the cloud console, combining multiple host rules to a single back-end.
3. `terrform apply` to undo the manual changes performed. This fails.
   * I also attempted to manually recreate the host rules in the cloud console.
   * While I am able to do this manually, I still cannot `terraform apply`

### Important Factoids

I am using a service account to apply these changes

### References

* None that I could find that sounded similar to my issue.

**Comment by rileykarson** [comment] 2018-11-29 20:34
Hey @bbrouwer! This should be fixed in `2.0.0` by #2245. Some resources were what we call 'non-authoritative', meaning that they ignored changes made upstream in GCP, including this one; making them authoritative was tracked by #1167.

I'm going to close this for now, but if you continue to encounter the issue after the `2.0.0` release (unfortunately we have no timeline on that yet other than alongside Terraform 0.12) please feel free to reopen or file a new issue!

**Closed by rileykarson** 2018-11-29 20:34 UTC
Labels: bug

**Comment by bbrouwer** [comment] 2018-11-30 13:37
Thanks @rileykarson. How would you recommend I fix this in the near term? Do I have to delete all my `host_rule` and `path_matcher` sections, run a `terraform apply` and then put them back in and run another `terraform apply`? Or do you have a recommendation that doesn't cause me an outage?

**Comment by rileykarson** [comment] 2018-11-30 16:04
I'm not aware of a good path for reconciliation here; my normal recommendation would be to use `terraform import`, but it won't work because the resource is non-authoritative. This is the problem that #2245 solves- letting Terraform properly diff those fields & allowing import to function correctly.

What the resource does pre-`2.0.0` is ignore fields that aren't present in state but that are present in GCP. Your state will have been created by the last successful `terraform apply`, you can see the state with `terraform show`. Your best bet is likely to revert the Terraform config to the config you used to create your state, get the GCP upstream to match your Terraform config by removing values, and then modify the config to add the new values; this means there'll be an outage in the meantime.

If it's _really important_ that there's no outage, you could try [modifying Terraform state](https://www.terraform.io/docs/state/index.html#inspection-and-modification) to match upstream; once every `path_matcher` and `url_map` is present in state, Terraform will read them as intended. Modifying state is considered unsafe, so make sure you back it up first if you do so. To my best knowledge `terraform plan` and `terraform apply` will still be correct, and the danger is mostly around syntax errors/potentially adding wrong/impossible values.

Sorry about your experience here & hope that helps in the short term! Once `2.0.0` has been released this resource (and every other legacy non-authoritative resource) should work authoritatively to avoid situations like this.
