### ISSUE TITLE
Updating google_container_node_pool stopped working

### ISSUE THREAD

**Issue by dsymonds** [terraform-providers/terraform-provider-google#5896] opened 2020-03-16 03:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.12.23
+ provider.google v3.12.0
+ provider.google-beta v3.12.0
+ provider.kubernetes v1.11.1
```

### Affected Resource(s)

* google_container_node_pool

Until recently, it was working fine, but now trying to make some innocuous change (e.g. changing the node pool size) fails with a 404 Not Found when it does a `GET /v1beta1/<location>/<cluster>/<nodepool>?alt=json&prettyPrint=false HTTP/1.1`. I now need to make such changes via the cloud console web UI.

It might be some Google-internal change has disabled the v1beta1 API, so it might be hard to reproduce elsewhere. I note that this provider has vendored an old version of the generated API client [1], so perhaps that just needs updating/replacing.

[1] https://github.com/terraform-providers/terraform-provider-google/blob/master/vendor/google.golang.org/api/container/v1beta1/container-api.json

**Comment by rileykarson** [comment] 2020-03-16 14:47
I believe this is a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5767. If the [`3.13.0` release](https://github.com/terraform-providers/terraform-provider-google/blob/release-3.13.0/CHANGELOG.md#3130-unreleased) later today doesn't fix it, can you reopen this / open a new issue?

**Closed by rileykarson** 2020-03-16 14:47 UTC
Labels: bug

**Comment by dsymonds** [comment] 2020-03-16 20:44
Yes, updating to 3.13.0 did indeed fix things. Thanks! Sorry I couldn't find that other issue with some searching.
