### ISSUE TITLE
Goggle compute API beta->v1 change keeps triggering a TF diff with 1.13.0

### ISSUE THREAD

**Issue by czka** [terraform-providers/terraform-provider-google#1610] opened 2018-06-07 12:34 UTC
```
$ terraform version
Terraform v0.11.7
+ provider.google v1.13.0
```
`terraform plan` with `provider.google v1.10.0` reports no changes on `terraform plan`. After upgrading to `v1.13.0`, `terraform plan` keeps reporting the change quoted below, even though I did run `terraform apply` on it in advance.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_compute_instance.machine1
      network_interface.#:                    "1" => "1"
      network_interface.0.address:            "10.118.234.33" => <computed>
      network_interface.0.name:               "nic0" => <computed>
      network_interface.0.network_ip:         "10.118.234.33" => <computed>
      network_interface.0.subnetwork:         
"https://www.googleapis.com/compute/beta/projects/project1/regions/us-east4/subnetworks/subnet1" => 
"https://www.googleapis.com/compute/v1/projects/project1/regions/us-east4/subnetworks/subnet1"
      network_interface.0.subnetwork_project: "project1" => <computed>


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by rosbo** [comment] 2018-06-07 17:40
This issue is also related to #988 where we have a perm diff when there should be no diff. We are investigating it.

**Comment by danawillow** [comment] 2018-06-07 22:17
@czka, mind sharing your config? Are you using `lifecycle.ignore_changes` by any chance?

**Comment by czka** [comment] 2018-06-08 09:11
@danawillow This particular node has `ignore_changes = ["metadata_startup_script", "boot_disk.0.initialize_params.0.image", "boot_disk.0.device_name"` only. Nothing else is being ignored all over the TF resources which are processed during the `terraform plan`. I can't share my config. It's top secret production stuff :).

@rosbo After switching from 1.10.0 to 1.13.0 I'm only getting a diff for `google_compute_instance` (a number of them; this one I'm quoting here is just one example). TF doesn't return diff for any other resources.

**Comment by rosbo** [comment] 2018-06-08 16:33
@danawillow found a bug in Terraform Core which is causing `ForceNew` field with a `DiffSuppressFunc` to not behave properly when there is a 'suppressable' diff. See for more details: hashicorp/terraform#18209

While waiting for the Terraform Core to be fixed, we can cheat a bit by converting the subnetwork `self_link` to v1 before we store it in the state. I will open a PR soon

**Comment by rosbo** [comment] 2018-06-08 16:56
I will keep this issue open until hashicorp/terraform#18209 is merged

**Comment by rosbo** [comment] 2018-06-08 16:57
Actually, this specific issue with beta links is resolved with the latest fix merged. We will keep #988 open to track the real root cause of this issue. Closing

**Closed by rosbo** 2018-06-08 16:57 UTC
Labels: bug
