### ISSUE TITLE
Tags/labels property behaviour incompatibility on migration from v0.9.11 to v0.10.0

### ISSUE THREAD

**Issue by AirsickPayload** [terraform-providers/terraform-provider-google#301] opened 2017-08-07 16:54 UTC
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "puppetdb-psql01" {
  name         = "puppetdb-psql01"
  machine_type = "n1-standard-2"
  zone         = "us-central1-a"
  tags         = ["no-ip"]

  lifecycle {
    ignore_changes = ["metadata_startup_script", "create_timeout", "disk", "machine_type"]
  }

  disk {
    image = "${var.centos_7_2}"
  }

  disk {
    disk        = "puppetdb-psql01-data-drive01"
    device_name = "postgresql-data"
    auto_delete = 0
  }

  network_interface {
    network = "sddc"
  }

  metadata {
    puppet_master      = "${var.puppetmaster}"
    puppet_environment = "production"
  }

  metadata_startup_script = "${file("../common/scripts/bootstrap.sh")}"
}

resource "google_compute_instance" "puppetdb-psql02" {
  name         = "puppetdb-psql02"
  machine_type = "n1-standard-4"
  zone         = "us-central1-a"
  tags         = ["no-ip"]

  lifecycle {
    ignore_changes = ["metadata_startup_script", "create_timeout"]
  }

  disk {
    image = "${var.centos_7_2}"
  }

  disk {
    disk        = "puppetdb-psql02-data-drive02"
    device_name = "postgresql-data"
    auto_delete = 0
  }

  network_interface {
    network = "sddc"
  }

  metadata {
    puppet_master      = "${var.puppetmaster}"
    puppet_environment = "production"
  }

  metadata_startup_script = "${file("../common/scripts/bootstrap.sh")}"
}
```

### Debug Output
https://gist.github.com/AirsickPayload/3366fd047ab910720c394b5a63d747e9

### Expected Behavior

Only `google_container_cluster.gitlab-cluster` and `google_service_account.docker_reader_kubernetes` should be planned for removal.

### Actual Behavior

Terraform has planned to also change `google_compute_instance.puppetdb-psql01`'s and `google_compute_instance.puppetdb-psql02`'s labels.

### Steps to Reproduce
1. `terraform plan`

# Temporary fix

replace
```hcl
tags         = ["no-ip"]
```
with
```hcl
  tags         = ["no-ip"]
  labels       = {"no-ip" = ""}
```

**Comment by gdubicki** [comment] 2017-08-08 12:34
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/254 ?

**Comment by gdubicki** [comment] 2017-08-08 12:34
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/254 ?

**Comment by selmanj** [comment] 2017-08-14 21:14
Looks similar to #254. This behavior is working as intended; A quick summary is that when labels were introduced, all the existing tags were also duplicated as a label. Now that terraform manages labels, you must explicitly list any labels you wish to preserve (such as 'no-ip' as shown above).

Feel free to reopen if you disagree or if I misinterpreted.

**Closed by selmanj** 2017-08-14 21:14 UTC
