### ISSUE TITLE
google_service_networking_connection fails when referencing data.google_compute_network

### ISSUE THREAD

**Issue by andyshinn** [terraform-providers/terraform-provider-google#4950] opened 2019-11-20 00:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```console
$ terraform version              
Terraform v0.12.13
+ provider.google v2.20.0
+ provider.ns1 v1.4.1
+ provider.random v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.16. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

* google_service_networking_connection
* data.google_compute_network

### Terraform Configuration Files

Config (same as from #4805): https://gist.github.com/andyshinn/601353a0bd5b86508e4a85dcda03741c

### Debug Output

Debug plan: https://gist.github.com/andyshinn/5159ff9455e1b89fcc8b6bffc10cbbce

### Expected Behavior

Not quite sure...

In my case the project doesn't exist. Terraform will be creating it. I might expect the data source to wait until the project is created so that the network is available.

It might be considered acceptable to fail `data.google_compute_network` earlier with an appropriate message if there is no created network available (because of no project). Though, this forces me to separate into two Terraform projects using state references between them.

### Actual Behavior

It appears `google_service_networking_connection` fails because `network` referenced from `data.google_compute_network` is either missing or empty.

### Steps to Reproduce

1. Start with no project.
1. `terraform plan`

### Important Factoids

May be similar issue to #4805. This is the same config attempted to be applied after #4805 was fixed.

Should we be avoiding creation and reference of projects in the same set of templates?

### References

* #4805

**Comment by slevenick** [comment] 2019-11-20 17:41
Creation of a project and reference within a data source *should* work. I've been able to use a simple config to create a data source that depends on another resource, and the data source doesn't attempt to refresh its state until the other resource is successfully created.

I notice that in your debug logs the only operations that happen are KMS calls, and then the network GET. Does the project already exist in the `tfstate` file, so terraform doesn't try to create it?

**Comment by andyshinn** [comment] 2019-11-20 19:05
There is no `google_project` in state at all (not even one with empty `instances`, all my other managed resources have state with empty `instances`).

**Comment by slevenick** [comment] 2019-11-20 19:15
If you throw an explicit `depends_on` on the data source does it change anything?

```
  depends_on = [
    google_project.analytics,
  ]
```

**Comment by andyshinn** [comment] 2019-11-20 22:54
That appears to work, at least, the plan now completes. But shouldn't it already depend on it from `project    = google_project.analytics.project_id`?

**Comment by slevenick** [comment] 2019-11-20 23:30
Normally it does, and I am unable to reproduce this locally.

I'd guess that terraform core is doing something clever to realize that it can tell `project_id` at plan time rather than depending on the project being created before it can interpret it.

Might be worth asking the question on terraform core: https://github.com/hashicorp/terraform
But at this point I'm going to close this as it is not a provider issue.

**Closed by slevenick** 2019-11-20 23:30 UTC
Labels: bug

**Comment by andyshinn** [comment] 2019-11-21 00:43
This seems strange because now the `depends_on` change is forcing a re-read of `data.google_compute_network.default` which is causing replacements of things like `google_compute_global_address` and `google_service_networking_connection` which worries me that I'm about to kill an existing private SQL IP address.

Are you looking for a more reliable way to troubleshoot? I'm not sure how to reproduce in the Terraform core as it seems to be dependent on a data source from a resource that hasn't been created yet.

**Comment by slevenick** [comment] 2019-11-21 00:53
I would expect a re-read of the datasource is necessary because if the project didn't exist there was no way for the data source to successfully read in the first place. 

Replacement of the global address and networking connection are worrying, but were they successfully configured during a previous run when the project was created but the data source read was unsuccessful? I was under the impression that the environment was never created successfully, which is why the data source read was failing in the first place

A more reliable way to troubleshoot would definitely help, but if you can reliably reproduce the issue then your debug logs should have enough information for the core team to have a look.

**Comment by andyshinn** [comment] 2019-11-21 01:00
There are multiple workspaces in this case, each having been created at different iteration points in the Terraform project. The existing workspaces probably had the service networking created _after_ the project was already set up (which is why they didn't have a dependency issue).

But now applying this fix for the _new_ workspace also affects the existing ones by forcing replacements and other in-place changes where the network is referenced.

I'll see if I can better distill this down into a simpler reproduction.

**Comment by andyshinn** [comment] 2019-12-11 19:22
I want to bring this up again because this broke my private SQL addresses the next application. Reading `data.google_compute_network` is changing on _every_ plan. My example is just these two resources:

```
Terraform will perform the following actions:

  # data.google_compute_network.default will be read during apply
  # (config refers to values not yet known)
 <= data "google_compute_network" "default"  {
      + description            = (known after apply)
      + gateway_ipv4           = (known after apply)
      + id                     = (known after apply)
      + name                   = "default"
      + project                = "fm-analytics-staging"
      + self_link              = (known after apply)
      + subnetworks_self_links = (known after apply)
    }

  # google_compute_global_address.private_ip_address must be replaced
-/+ resource "google_compute_global_address" "private_ip_address" {
      ~ address            = "10.95.252.0" -> (known after apply)
        address_type       = "INTERNAL"
      ~ creation_timestamp = "2019-12-11T11:01:39.539-08:00" -> (known after apply)
      ~ id                 = "private-ip-address" -> (known after apply)
        name               = "private-ip-address"
      ~ network            = "https://www.googleapis.com/compute/v1/projects/fm-analytics-staging/global/networks/default" -> (known after apply) # forces replacement
        prefix_length      = 24
        project            = "fm-analytics-staging"
        purpose            = "VPC_PEERING"
      ~ self_link          = "https://www.googleapis.com/compute/v1/projects/fm-analytics-staging/global/addresses/private-ip-address" -> (known after apply)
    }
```

This will change on every apply. Is this not a bug? Am I doing something wrong?
