### ISSUE TITLE
credentials attribute not being accepted for all requests

### ISSUE THREAD

**Issue by jeff-knurek** [terraform-providers/terraform-provider-google#2114] opened 2018-09-26 15:17 UTC
### Terraform Version
0.11.8

### Affected Resource(s)

* google_sql_database_instance
* google_service_account_key

### Problem Description

There seems to be a problem with the authentication process for:
- data_source_google_service_account_key
- resource_sql_database_instance

What seems to happen is that there is the GCE-provided service account (in IAM it has the name `Compute Engine default service account`). 

When creating a terraform project that has, for example:
```
provider "google" {
  version     = "1.10"
  alias       = "k8s"
  credentials = "${file("/.service-account.json")}"
  project     = "Project-Id"
  region      = "europe-west1"
}
```
the service account defined in the key file `"/.service-account.json"` is used, and whatever project you're connected to in your terminal doesn't matter because the one set by the provider is used. 

However for the resources mentioned above _(everything else we use works fine)_, the authentication seems to not be connected using the service account in the file, but rather with the GCE-provided account. 

I'm not really sure how to describe the steps to reproduce this issue, because it seems to be impacted by having multiple projects in Google using the the same authentication pattern. And one project will function without issue, while any others will fail.

### Workaround 

The workaround for a regular user is to  remove `~/.config/gcloud/application_default_credentials.json` and then, `gcloud auth application-default login` which should create the file again.

For a service account however (which is needed in CI), the workaround above doesn't work. What seems to work instead, is to run: 
```
gcloud auth activate-service-account --key-file ./service-account.json
gcloud container clusters get-credentials --zone europe-west1-b --project PROJECT CLUSTERNAME
```
and then set the `GOOGLE_APPLICATION_CREDENTIALS` env var. 

### Related logs

Evaluating the logs when the issue occurs, vs when the workarounds are applied, reveals differences in the authentication.
For example, when running in with a service account in CI, if the gcloud auth commands are not executed, 
```
plugin.terraform-provider-google_v1.10.0_x4: 2018/09/20 15:32:05 [INFO] Authenticating using DefaultClient
plugin.terraform-provider-google_v1.10.0_x4: 2018/09/20 15:32:26 [INFO] Requesting Google token...
```
both authentication strategies are attempted. It is unclear why, but it would be expected that the DefaultClient would possibly be using the wrong connection. 
When the `GOOGLE_APPLICATION_CREDENTIALS` env var is used, only the `Authenticating using DefaultClient` strategy is used (still twice though).

-----

One thing that was noticed in the config.go file, probably not related, the client scopes are hardcoded, and so maybe there's not enough permissions there:
```
	clientScopes := []string{
		"https://www.googleapis.com/auth/compute",
		"https://www.googleapis.com/auth/cloud-platform",
		"https://www.googleapis.com/auth/ndev.clouddns.readwrite",
		"https://www.googleapis.com/auth/devstorage.full_control",
	}
```

---------

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

**Comment by rileykarson** [comment] 2019-06-25 21:10
Our handling of authentication methods has changed a lot since this was filed, including `2.0.0`. Based on that, and the lack of context in this bug, I'm going to close this out- there isn't much we can do from our side without more details / a newer provider version. That said, if you're able to reproduce this in a `2.X` series release, please file again!

**Closed by rileykarson** 2019-06-25 21:10 UTC
Labels: bug
