### ISSUE TITLE
google_dns_record_set

### ISSUE THREAD

**Issue by qgriffith** [terraform-providers/terraform-provider-google#232] opened 2017-07-24 15:56 UTC
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- google_dns_record_set TXT records

### Terraform Configuration Files
```hcl
resource "google_dns_record_set" "foo-TXT" {
   name = "on-site.com."
   managed_zone = "${google_dns_managed_zone.on-site-com.name}"
   type = "TXT"
   ttl = "300"
   rrdatas = ["v=spf1 blah foo bar ]
}
```

### Expected Behavior
Creates a TXT record as a single string

"v=spf1 blah foo bar"

### Actual Behavior
It is quoting everything in between the spaces which create an invalid SPF record

"v=spf1" "blah" "foo" "bar"

When I add the record via the Google Console it is created properly something in terraform is adding the quotes to everything separated by a space

### Steps to Reproduce

1. Create a TXT type record with a long string
2. Run `terraform apply`
3. Look in the google console or use dig to see that the record contains several strings instead of a single string with qutoes.

### References
This was fixed for another provider 
https://github.com/hashicorp/terraform/pull/13260

**Comment by rosbo** [comment] 2017-07-28 19:53
Hi,

Duplicate of [#13463](https://github.com/hashicorp/terraform/issues/13463).

The behavior of splitting on spaces and quoting each chunk comes from the GCloud API, not Terraform. See issue linked above for background.

The work around is to add `\"` around your string. Your configuration should be:
```hcl
rrdatas = ["\"v=spf1 blah foo bar\""]
```

I will update the documentation.

Thank you!

**Closed** 2017-08-01 16:59 UTC
Labels: bug
