### ISSUE TITLE
TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample

### ISSUE THREAD

**Issue by slevenick** [terraform-providers/terraform-provider-google#5450] opened 2020-01-21 17:45 UTC
Test failing since 01/15/2020

**Comment by emilymye** [comment] 2020-01-21 18:58
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5449

**Closed by emilymye** 2020-01-21 18:58 UTC
Labels: test failure
