### ISSUE TITLE
resource_dns_managed_zone seems to make terraform crash

### ISSUE THREAD

**Issue by BlowaXD** [terraform-providers/terraform-provider-google#4805] opened 2019-11-04 08:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.12
+ provider.google v2.18.1

### Affected Resource(s)

* google_dns_managed_zone

### Terraform Configuration Files

```tf
terraform {
  backend "gcs" {
    bucket = "av-terraform"
    prefix = "managed-dns/state"
  }
}


data "google_compute_network" "default" {
  name = "default"
}

# this has been previously created
data "google_compute_network" "antvoice-vpc" {
  name = "antvoice-general-vpc"
}



# Sentry zone
resource "google_dns_managed_zone" "private-sentry" {
  name        = "sentry"
  dns_name    = "sentry."
  description = "Sentry private zone"

  labels = {
    type = "sentry"
  }

  visibility = "private"

  private_visibility_config {
    networks {
      network_url = data.google_compute_network.default.self_link
    }
    networks {
      network_url = data.google_compute_network.antvoice-vpc.self_link
    }
  }
}
```

### Debug Output

https://gist.github.com/BlowaXD/eace5b0e7669146d9f66008a730991c6

### Panic Output

https://gist.github.com/BlowaXD/8d3bf3830be7c336f26bdfd1b15cae20

### Expected Behavior

I should have been able to plan my resources

### Actual Behavior

Just crash when it tries to read the DNS managed zone without any step

### Steps to Reproduce

```sh
terraform init
terraform plan
```

### Important Factoids

I'm applying as a user, I think I got enough rights (dns admin/vpc admin...) to at least plan my resources
resource_dns_managed_zone seems to be contains the error

**Comment by danawillow** [comment] 2019-11-07 00:17
Hi @BlowaXD, I'm not able to reproduce this in my own project. A few questions:
- Is this the full TF config you're using, or just an excerpt? If an excerpt, would you mind sharing the full config?
- Are the networks and managed zones in the same project, or different projects?
- Does this happen on the plan before the resource is created, or when running plan after the resource already exists?

Thanks!

**Comment by andyshinn** [comment] 2019-11-07 00:44
If it helps, I'm also having this issue and my project is being created at the same time as the DNS record that depends on it. No project exists yet.

**Comment by danawillow** [comment] 2019-11-07 00:51
@andyshinn thanks! Would you mind also posting the full config you're using as well as debug logs (https://www.terraform.io/docs/internals/debugging.html)? More data certainly can't hurt.

**Comment by andyshinn** [comment] 2019-11-07 01:18
Here is the sanitized config and log: https://gist.github.com/andyshinn/601353a0bd5b86508e4a85dcda03741c

It pulls some remote state, let me know if that project is helpful also. This is run from Terraform Cloud.

**Comment by BlowaXD** [comment] 2019-11-07 18:42
> 
> 
> Hi @BlowaXD, I'm not able to reproduce this in my own project. A few questions:
> 
>     * Is this the full TF config you're using, or just an excerpt? If an excerpt, would you mind sharing the full config?
> 
>     * Are the networks and managed zones in the same project, or different projects?
> 
>     * Does this happen on the plan before the resource is created, or when running plan after the resource already exists?
> 
> 
> Thanks!

Hi this is not the full TF config I'm using, but it's enough to reproduce the bug.

The networks and managed zones are all inside the same project

This happen when the resources already exists and are then fetched.

**Comment by danawillow** [comment] 2019-11-07 18:42
Thanks, those logs help a lot. Just from reading through those, it looks like the project "analytics" existed in state (but not upstream in GCP) at the time the plan was run (so maybe it was deleted in the console or with gcloud). Is that correct, or was this plan running with an empty state?

**Comment by danawillow** [comment] 2019-11-07 18:46
@BlowaXD, would you mind also posting debug logs (https://www.terraform.io/docs/internals/debugging.html)? I'd like to see what requests/responses are getting sent to/from GCP.

**Comment by andyshinn** [comment] 2019-11-07 18:51
No, it should have ever existed in this case. I have another workspace where I iteratively created the project (where it was probably created before `google_dns_managed_zone` was added). But in this case I was creating a new workspace and new project. Everything in state has an empty `instances` except for the remote data and the random provider.

**Comment by danawillow** [comment] 2019-11-07 18:53
Ah, got it. I also just managed to get a repro going where I used a data source for a network that doesn't exist (for some reason it didn't repro for me if the data source depended on a project resource that didn't exist).

**Comment by danawillow** [comment] 2019-11-07 23:54
So here's what I'm pretty sure is happening: the network data source is trying to read the network, seeing it doesn't exist, and writing empty state. Then, the DNS resource is trying to interpolate the value of the network from the data source, seeing that it's not in state, and interpreting that as if the `network_url` had been set to `null`. Our code assumes that if `networks` is defined in config, then it won't be nil, hence the crash.

The code on our side is super easy to fix, I can just add a nil check and be done with it. I'm at a loss for why the network data source is doing a read at all at plan-time given that it interpolates a value from the project resource, which hasn't been created yet (for what it's worth, I couldn't reproduce that part of the issue). I think that if that's indeed happening, then that's an issue that should be filed with the core terraform repo.

**Comment by andyshinn** [comment] 2019-11-08 00:12
> I'm at a loss for why the network data source is doing a read at all at plan-time given that it interpolates a value from the project resource, which hasn't been created yet (for what it's worth, I couldn't reproduce that part of the issue).

In my case the resource `project_id` it references just comes from `var.workspace`. Maybe in that case where it doesn't need a computed value the resource doesn't need to exist yet?

Thanks for pushing a fix for this!

**Comment by danawillow** [comment] 2019-11-08 02:07
I've seen similar behavior in the past, but I thought it was fixed (especially since I don't seem to be encountering the same thing). Out of curiosity, what does `terraform graph` say?

**Comment by andyshinn** [comment] 2019-11-08 02:15
`terraform graph`: https://gist.github.com/andyshinn/1d3ffbc1eac94c8998d49715dd24e89d

**Comment by danawillow** [comment] 2019-11-08 02:44
Hmm yeah it definitely shows  the network being dependent on the project. Weird!

**Closed** 2019-11-09 00:42 UTC
Labels: bug

**Comment by BlowaXD** [comment] 2019-11-12 10:02
Hi, sorry for the delay @danawillow 

This is not the entire configuration, however, I reduced to a minimum reproducible state. It effectively needs to fetch existing resources.

The logs are already in the issue, did I do something wrong with it ?

> Debug Output
https://gist.github.com/BlowaXD/eace5b0e7669146d9f66008a730991c6

> Panic Output
https://gist.github.com/BlowaXD/8d3bf3830be7c336f26bdfd1b15cae20

Btw, thanks for the fix but I'm still having a crash, even thought I updated gcp's terraform provider to 2.19.0

Here are the debug logs of the latest crash :
`terraform -v` :
> Terraform v0.12.13
>+ provider.google v2.19.0


`LOG_LEVEL=DEBUG terraform plan` :
* crash.log : https://gist.github.com/BlowaXD/844f57d6dde99a4ea7db87d57bb77259
* console output : https://gist.github.com/BlowaXD/373b467d2f7da3680ab94eb94ff8f8c4


`terraform graph` https://gist.github.com/BlowaXD/8f29592b689bb1669a0f3898ccfb30fe

**Comment by andyshinn** [comment] 2019-11-12 14:09
I don't think the fix is in 2.19.0. The commit is https://github.com/terraform-providers/terraform-provider-google/commit/4ccce14a5d9f2125f80456ce8b0b32a3e855bf71 and I don't see any tag listed so probably have to wait for next version.

**Comment by danawillow** [comment] 2019-11-12 17:52
Yup, @andyshinn is correct. It'll be in 2.20, which comes out probably today.

**Comment by BlowaXD** [comment] 2019-11-12 18:25
My bad, I should sleep a bit more 😅
