### ISSUE TITLE
container_node_pool docs are outdated

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#2104] opened 2018-09-24 08:02 UTC
https://www.terraform.io/docs/providers/google/r/container_node_pool.html
```
Usage with a regional cluster

resource "google_container_cluster" "regional" {
  name   = "marcellus-wallace"
  region = "us-central1"
}

resource "google_container_node_pool" "regional-np" {
  name       = "my-node-pool"
  region     = "us-central1"
  cluster    = "${google_container_cluster.primary.name}"
  node_count = 1
}
```

^-- that usage won't work `Error 400: Cluster.initial_node_count must be greater than zero., badRequest`

**Comment by wyardley** [comment] 2018-10-19 17:37
I am also seeing similar issues (w/ zonal clusters)
#285 has some really good explanations and examples that, AFAICT, still haven't made it into the docs.

**Comment by hawksight** [comment] 2018-11-26 12:16
You're right that you get exactly that error, but the issue is not with the `google_container_node_pool` resource, but rather with the `google_container_cluster` configuration. The Google API creates the cluster first, but it will not create without a node.

> Error 400: Cluster.initial_node_count

You might want to consider the following options if you are trying to create a cluster with only your specified node_pool:

```hcl-terraform
resource "google_container_cluster" "regional" {
  name   = "marcellus-wallace"
  region = "us-central1"
  intital_node_count = "1"
  remove_default_node_pool = "true"
}

resource "google_container_node_pool" "regional-np" {
  name       = "my-node-pool"
  region     = "us-central1"
  cluster    = "${google_container_cluster.regional.name}"
  node_count = 1
  depends_on = ["google_container_cluster.regional"]
}
```

(Code snippets from own config - untested as seen)

That should create the cluster with the default node_pool and terraform then removes the default node_pool. You get around the issue by providing `intital_node_count = "1"`.

@wyardley points to some good discussions about why creating cluster / node_pools can be very tricky. There's a lot of combinations to cover.

On the cluster docs it [does say](https://www.terraform.io/docs/providers/google/r/container_cluster.html#initial_node_count):

> initial_node_count - (Optional) The number of nodes to create in this cluster (not including the Kubernetes master). Must be set if node_pool is not set.

Unsure how to clarify the docs, but hoping that solution gives a way to achieve what I think you were trying to.

**Comment by rileykarson** [comment] 2019-02-15 15:46
Should be fixed when I made a pass at these docs, but let me know if that's not the case. https://github.com/GoogleCloudPlatform/magic-modules/pull/1329

**Closed by rileykarson** 2019-02-15 15:46 UTC
Labels: documentation
