### ISSUE TITLE
enable_flow_logs in google_compute_subnetwork error 400 - resource.fingerprint not specified

### ISSUE THREAD

**Issue by dthapa** [terraform-providers/terraform-provider-google#1469] opened 2018-05-10 05:17 UTC
### Terraform Version
Terraform v0.11.7
+ provider.google v1.12.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_subnetwork

### Terraform Configuration Files
```hcl
resource 'google_compute_subnetwork' 'my-subnetwork-01' {
  name = "my-subnetwork-01"
  ip_cidr_range = "10.50.240.0/25"
  network = "my-network-01"
  region = "us-west1"
  private_ip_google_access = "true"
  enable_flow_logs = true
}
```

### Debug Output
https://gist.github.com/dthapa/dd7f6a37c92f31b6c2b598722edc10ff

### Panic Output
na

### Expected Behavior
enable_flow_logs should be set to true

### Actual Behavior
googleapi: Error 400: Required field ‘resource.fingerprint’ not specified, required

### Steps to Reproduce
`terraform apply`

### Important Factoids
no

### References
https://github.com/terraform-providers/terraform-provider-google/pull/1385

**Comment by ndmckinley** [comment] 2018-05-10 20:36
@paddycarver - you might have the most context on this.  Did you run into this in your PR?

**Comment by paddycarver** [comment] 2018-05-10 22:42
I think this is just shoddy testing on my part, sorry. :( I'll take this one on. I think I just botched the update function and then didn't have sufficient test coverage to catch it.

**Comment by robgil** [comment] 2018-05-18 18:31
Running in to this as well while attempting to apply `enable_flow_logs`.

**Comment by paddycarver** [comment] 2018-05-19 00:01
Do you happen to have a reproducible config for this, or debug logs? I've been unable to reproduce it in our tests or on my own.

**Comment by dthapa** [comment] 2018-05-22 02:18
@paddycarver ty; apologies for not getting to this fast enough.

here is my test config:

subnetworks.tf

```
resource "google_compute_network" "tf-test-vpc" {
  name                    = "tf-test-vpc"
  auto_create_subnetworks = "false"
}

resource "google_compute_subnetwork" "tf-test-vpc" {
  name                     = "tf-test-vpc"
  ip_cidr_range            = "10.48.3.0/24"
  network                  = "${google_compute_network.tf-test-vpc.self_link}"
  region                   = "us-central1"
  private_ip_google_access = "true"
  enable_flow_logs         = true
}
```

[debug.log](https://github.com/terraform-providers/terraform-provider-google/files/2024697/debug.log)

**Comment by wmuizelaar** [comment] 2018-05-23 08:56
I can reproduce this as well - what I noticed is that resources that do /not/ have secondary_ip_ranges defined didn't work, and resources that /do/ have secondary_ip_ranges defined actually work.

**Comment by bitglue** [comment] 2018-06-01 17:31
The error seems to happen only on update, which may explain the difficulty in reproducing. I'm getting the same error trying to add a `secondary_ip_range` to an existing subnetwork.

**Comment by paddycarver** [comment] 2018-06-08 00:58
I'm confused about this, but could you try with version 1.13.0 or 1.14.0 of the GCP provider and let me know if this is still happening? I think it may have been fixed by unrelated changes.

**Comment by wmuizelaar** [comment] 2018-06-08 07:43
I tested with 1.13.0, and cannot reproduce the issue anymore.

**Comment by paddycarver** [comment] 2018-06-19 19:50
Cool, thank you for the update! I'm going to close this out, then. If anyone can reproduce with 1.13.0 or 1.14.0, I'd love to hear about it.

**Closed by paddycarver** 2018-06-19 19:50 UTC
Labels: bug, waiting-response
