### ISSUE TITLE
google_composer_environment - allowed to pass empty environment variable

### ISSUE THREAD

**Issue by poligraph** [terraform-providers/terraform-provider-google#5401] opened 2020-01-14 12:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.18
provider.google v2.20.1

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```
locals {
  default_env_variables = {
    "FACEBOOK_AN_ACCESS_TOKEN"    = "vkrjnvkjrvekrnvcekcnkncvk"
    "FACEBOOK_AN_APP_IDS"         = "123456789"
    "FACEBOOK_AN_BQ_DATASET_NAME" = "dsknckdsnk"
    "FACEBOOK_AN_BREAKDOWNS"      = "country,delivery_method,platform,property,placement_name"
    "FACEBOOK_AN_METRICS"         = ""
  }
}

resource "google_composer_environment" "composer" {
  provider = google

  name   = "${var.project}-composer"
  region = var.region

  config {
    node_count = var.node_count

    node_config {
      machine_type    = var.machine_type
      zone            = var.zone
      network         = google_compute_network.composter.self_link
      subnetwork      = google_compute_subnetwork.composter_subnet.self_link
      service_account = google_service_account.composter.name
    }

    software_config {
      pypi_packages  = merge(local.default_pypi_packages, var.pypi_packages)
      env_variables  = merge(local.default_env_variables, var.env_variables)
      image_version  = var.image_version
      python_version = "3"

      airflow_config_overrides = {
        "core-dags_are_paused_at_creation" = "True"
      }
    }
  }
}
```

### Expected Behavior

`terraform apply` should fail on pre-check, because it's impossible to set empty ENV VAR in google cloud console for composer.

### Actual Behavior

`terraform apply` running successfully and actually set FACEBOOK_AN_METRICS var to empty value 

                  ~ "FACEBOOK_AN_ACCESS_TOKEN"            = "DISABLED" -> "vkrjnvkjrvekrnvcekcnkncvk"
                  ~ "FACEBOOK_AN_APP_IDS"                 = "DISABLED" -> "123456789"
                  ~ "FACEBOOK_AN_BQ_DATASET_NAME"         = "DISABLED" -> "dsknckdsnk"
                  ~ "FACEBOOK_AN_BREAKDOWNS"              = "DISABLED" -> "country,delivery_method,platform,property,placement_name"
                  ~ "FACEBOOK_AN_METRICS"                 = "DISABLED" -> ""
### Steps to Reproduce

1. `terraform apply` with non empty env vars
1. `terraform apply` with one var changed to empty value

### References

* #0000

**Comment by edwardmedia** [comment] 2020-01-17 00:33
@poligraph it's hard to understand what the issue is. Can you post the entire configuration, along with  lot of `var ` and `local.default_pypi_packages`, etc. How to navigate to find `ENV VAR in google cloud console for composer.`? Thanks

**Comment by poligraph** [comment] 2020-01-22 10:59
@edwardmedia here is my config

```
locals {
  default_env_variables = {
    "FACEBOOK_AN_APP_IDS"         = "DISABLED"
    "FACEBOOK_AN_ACCESS_TOKEN"    = "DISABLED"
    "FACEBOOK_AN_METRICS"         = ""
    "FACEBOOK_AN_BREAKDOWNS"      = "DISABLED"
    "FACEBOOK_AN_BQ_DATASET_NAME" = "DISABLED"
  }
}


variable "project" {
  type        = string
  default = "PROJECT"
}

variable "region" {
  type    = string
  default = "europe-west1"
}

variable "zone" {
  default = "europe-west1-c"
}

variable "ip_cidr_range" {
  default = "192.168.10.0/24"
}

variable "env" {
  default = "composer"
}

resource "google_composer_environment" "airflow" {
  provider = google
  name   = var.env
  region = var.region
  project = var.project
  config {
    node_count = 3
    node_config {
      zone         = var.zone
      machine_type = "n1-standard-2"
      disk_size_gb = 50
      network         = google_compute_network.composer.self_link
      subnetwork      = google_compute_subnetwork.composer_subnet.self_link
    }
    software_config {
      python_version = 3
      env_variables  = merge(local.default_env_variables)
    }
  }
  labels = {
    env = var.env
  }
}

resource "google_compute_network" "composer" {
  name                    = "${var.project}-composer-net"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "composer_subnet" {
  name          = var.composer_subnet_name
  ip_cidr_range = var.ip_cidr_range
  region        = var.region
  network       = google_compute_network.composer.self_link
}

```

**Comment by edwardmedia** [comment] 2020-01-22 22:17
@poligraph I see what you mean now. I see the difference for this between GCP console and API. While the console does not allow you to enter an empty value key, API does. We follow the API standard. Below is the API reference
https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments#SoftwareConfig
I am closing this. If you want further discussion, you may reopen it. Thanks

**Closed by edwardmedia** 2020-01-22 22:17 UTC
Labels: bug
