### ISSUE TITLE
Scopes, labels and tags for node-pool

### ISSUE THREAD

**Issue by holoGDM** [terraform-providers/terraform-provider-google#162] opened 2017-06-28 09:36 UTC
Hello

  As sugested [here](https://serverfault.com/questions/856793/gke-cant-tag-cluster-with-terraform-config) im opening this issue.

  There is no possibility to set up scopes, tags and labels when adding additional node-pools to cluster with Terraform. Things are possible when you are creating cluster eg: [node_config](https://github.com/terraform-providers/terraform-provider-google/blob/a25461f2cc6f2a58c58b43b67a55c14a5af8b055/google/resource_container_cluster.go#L295-L300) options - tags, labels, oauth_scopes. Please can you add such possibility?

Regards
holo

**Comment by danawillow** [comment] 2017-06-28 16:20
Closing as a duplicate of #161

**Closed by danawillow** 2017-06-28 16:20 UTC
