### ISSUE TITLE
istio_config always triggers a Terraform change

### ISSUE THREAD

**Issue by maguro** [terraform-providers/terraform-provider-google#3809] opened 2019-06-06 16:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.1
+ provider.google v2.8.0
+ provider.google-beta v2.8.0

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "foo-cluster" {
  provider = "google-beta"
  name     = "tf-foo-${var.env}"
  project  = var.project_id
  location = var.location
  network  = var.network
  logging_service = "logging.googleapis.com"

  min_master_version = var.node_version

  master_auth {
    // Google OIDC is used for all new GKE clusters
    // and basic authentication is no longer needed.
    username = ""
    password = ""

    // Client certificate authentication is also no
    // longer needed for new GKE clusters.
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  lifecycle {
    ignore_changes = [
      "node_pool"]
  }

  addons_config {
    // The Kubernetes Dashboard is enabled by default, but is no
    // longer be needed because equivalent functionality is available
    // in the Google Cloud Console. Customers are advised not to run
    // the Kubernetes Dashboard for security reasons.
    kubernetes_dashboard {
      disabled = true
    }

    http_load_balancing {
      disabled = false
    }

    istio_config {
      disabled = false
      auth     = "AUTH_NONE"
    }

    cloudrun_config {
      disabled = false
    }
  }

  // empty default pool
  node_pool {
    name = "default-pool"
  }
}
```

### Debug Output

https://gist.github.com/maguro/6b2be345ae9662c953c92b773f92059c

### Expected Behavior

There should be no change.

### Actual Behavior

Plan claims there is a change:

          ~ istio_config {
              + auth     = "AUTH_NONE"
                disabled = false
            }

### Steps to Reproduce

1. `terraform apply` # to create
2. `terraform plan` # to see that the istio config always triggers a change.

**Comment by rileykarson** [comment] 2019-06-10 18:13
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3807

**Closed by rileykarson** 2019-06-10 18:13 UTC
Labels: bug
