### ISSUE TITLE
google_container_node_pool incorrectly recreating

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#5265] opened 2019-12-27 09:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.18, with 3.3.0 google plugin

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "node_pool" {
  provider   = google-beta
  name       = var.name
  node_count = var.min_node_count
  cluster    = var.cluster.name
  location   = var.cluster.zone
  version    = var.node_version
```

### Debug Output

```tf
  ~ resource "google_container_node_pool" "node_pool" {
        cluster             = "delivery-platform"
        id                  = "europe-west4-a/delivery-platform/vds-20191114"
        initial_node_count  = 0
        instance_group_urls = [
            "https://www.googleapis.com/compute/v1/projects/at-delivery-platform-testing/zones/europe-west4-a/instanceGroupManagers/gke-delivery-platform-vds-20191114-1648b4ed-grp",
            "https://www.googleapis.com/compute/v1/projects/at-delivery-platform-testing/zones/europe-west4-b/instanceGroupManagers/gke-delivery-platform-vds-20191114-a95b2424-grp",
        ]
        location            = "europe-west4-a"
        max_pods_per_node   = 110
        name                = "vds-20191114"
        node_count          = 0
        node_locations      = [
            "europe-west4-a",
            "europe-west4-b",
        ]
        project             = "at-delivery-platform-testing"
        version             = "1.14.8-gke.21"
      - zone                = "europe-west4-a" -> null
```

### Expected Behavior

Nothing to rebuild

### Actual Behavior

Following our upgrade to version 3.3.0 of the provider, we are getting node pools being recreated due to to the `zone` field changing.

You cannot set zone, as it's deprecated, and you're told to use location instead (which we are setting), the only way we could stop the pools being recreated was to add `zone` to the `lifecycle.ignore_changes` array.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Stono** [comment] 2019-12-27 09:56
There's a very similar problem with `google_container_cluster` too.  Omitting `zone` and `additional_zones` gives you update in place, but setting them gives you:

```
Error: "additional_zones": [REMOVED] Use node_locations instead

  on modules/container-cluster/main.tf line 67, in resource "google_container_cluster" "cluster":
  67: resource "google_container_cluster" "cluster" {
```

The work around again is to add them to the ignore_lifecycle block

**Comment by venkykuberan** [comment] 2019-12-27 22:31
@Stono can you please copy here your both cluster and node_pool config.

**Comment by danawillow** [comment] 2019-12-30 21:25
@venkykuberan it looks to me like this particular issue is caused by having a node pool that was already using `zone`, and then updating the provider to a version where `zone` was removed. Creating a node pool without setting `zone` is the correct thing to do for new clusters, but won't help users that already have clusters that used the old field.

Here's how I can repro this-

In my terraform-provider-google directory:
```
~/go/src/github.com/terraform-providers/terraform-provider-google (master)$ git fetch --tags
remote: Enumerating objects: 175, done.
remote: Counting objects: 100% (175/175), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 245 (delta 165), reused 163 (delta 161), pack-reused 70
Receiving objects: 100% (245/245), 140.96 KiB | 10.07 MiB/s, done.
Resolving deltas: 100% (187/187), completed with 73 local objects.
From https://github.com/terraform-providers/terraform-provider-google
   4e3c5913..75417ae4  master     -> upstream/master
~/go/src/github.com/terraform-providers/terraform-provider-google (master)$ git checkout v2.20.1
Note: switching to 'v2.20.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5a1a8bc2 v2.20.1
~/go/src/github.com/terraform-providers/terraform-provider-google ((v2.20.1))$ make
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go install
go: downloading github.com/hashicorp/terraform-plugin-sdk v1.3.0
go: extracting github.com/hashicorp/terraform-plugin-sdk v1.3.0
go: downloading github.com/keybase/go-crypto v0.0.0-20181127160227-255a5089e85a
go: downloading github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
go: extracting github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
go: extracting github.com/keybase/go-crypto v0.0.0-20181127160227-255a5089e85a
go: downloading github.com/hashicorp/hcl2 v0.0.0-20190821123243-0c888d1241f6
go: downloading github.com/pierrec/lz4 v2.0.5+incompatible
go: downloading github.com/hashicorp/hil v0.0.0-20190212112733-ab17b08d6590
go: extracting github.com/hashicorp/hil v0.0.0-20190212112733-ab17b08d6590
go: extracting github.com/hashicorp/hcl2 v0.0.0-20190821123243-0c888d1241f6
go: downloading github.com/golang/snappy v0.0.1
go: extracting github.com/golang/snappy v0.0.1
go: extracting github.com/pierrec/lz4 v2.0.5+incompatible
go: finding github.com/hashicorp/terraform-plugin-sdk v1.3.0
go: finding github.com/hashicorp/hil v0.0.0-20190212112733-ab17b08d6590
go: finding github.com/keybase/go-crypto v0.0.0-20181127160227-255a5089e85a
go: finding github.com/pierrec/lz4 v2.0.5+incompatible
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/hashicorp/terraform-config-inspect v0.0.0-20190821133035-82a99dc22ef4
go: finding github.com/hashicorp/hcl2 v0.0.0-20190821123243-0c888d1241f6
```

Then, in a folder where I store my terraform configs, I `terraform apply`-ed with that version of the provider and this basic config:
```
resource "google_container_cluster" "primary" {
  name               = "is-5265"
  zone               = "us-central1-a"
  initial_node_count = 1
}
```

Now, back in terraform-provider-google:
```
~/go/src/github.com/terraform-providers/terraform-provider-google ((v2.20.1))$ git checkout v3.3.0
Previous HEAD position was 5a1a8bc2 v2.20.1
HEAD is now at 85d4b598 v3.3.0
~/go/src/github.com/terraform-providers/terraform-provider-google ((v3.3.0))$ make
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go install
```

Now, running `terraform plan` for the same config gives this:
```
Error: "zone": [REMOVED] Use location instead

  on main.tf line 1, in resource "google_container_cluster" "primary":
   1: resource "google_container_cluster" "primary" {
```

Then I can go and change `zone` to `location`, and I end up with a plan with these parts (redacting the rest because it's not relevant):
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_container_cluster.primary: Refreshing state... [id=is-5265]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_container_cluster.primary will be updated in-place
  ~ resource "google_container_cluster" "primary" {
[a bunch of unchanged things]
      - zone                      = "us-central1-a" -> null
[a bunch of other unchanged things]
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

This is a bug- removing a field that can't be set shouldn't give a diff. We can fix this pretty easily by marking the field as `Computed`, which will allow users to safely remove it from their configs. In reality, I think this should be fixed in the SDK (rather than in the provider) so provider developers don't have to know that all `Removed` fields should also be `Computed`. I'll file an issue there, but since it's pretty easily worked around on our side by just setting the fields to computed, I'll do that as well.

@Stono, your issue title mentions that the node pools are recreating, but your description only shows a plan with an in-place update. Do you have an additional example of one that recreates?

**Closed** 2020-01-06 20:47 UTC
Labels: bug, waiting-response
