### ISSUE TITLE
Updating IAM Members at bigquery dataset level

### ISSUE THREAD

**Issue by sanmmishra** [terraform-providers/terraform-provider-google#5174] opened 2019-12-14 21:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

Can we add IAM Members to bigquery dataset similar to how iam members can be done for other resource (bigtable, [dataproc](https://www.terraform.io/docs/providers/google/r/dataproc_cluster_iam.html#google_dataproc_cluster_iam_member), kms rings, etc)

Currently, the only way to add iam members is to modify the google_bigquery_dataset's access block. It would be useful to add IAM Members to bigquery dataset independently rather than making configuration changes to overall bigquery dataset.

### New or Affected Resource(s)

* google_bigquery_dataset

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset_iam_binding" "editor" {
  dataset_id  = "example_dataset"
  role    = "roles/editor"
  members = [
    "user:jane@example.com",
  ]
}
```

### References

* #0000

**Comment by danawillow** [comment] 2019-12-16 17:30
The BigQuery API doesn't have getIamPolicy/setIamPolicy methods, which would be necessary in order to use the same IAM infrastructure we have in the provider (https://cloud.google.com/bigquery/docs/reference/rest/#rest-resource-v2datasets). However, we can probably do something similar- marking this as a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3990 and https://github.com/terraform-providers/terraform-provider-google/issues/2686

**Closed by danawillow** 2019-12-16 17:30 UTC
Labels: enhancement
