### ISSUE TITLE
Private and public IP addresses not available in the statefile.

### ISSUE THREAD

**Issue by anas-aso** [terraform-providers/terraform-provider-google#543] opened 2017-10-06 16:13 UTC
### Terraform Version
``` bash
$ terraform -v
Terraform v0.10.6
```

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "n1-standard-1"
  zone         = "us-central1-a"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-8"
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }
}

output "private_ip" {
  value = "${google_compute_instance.default.network_interface.0.address}"
}

output "public_ip" {
  value = "${google_compute_instance.default.network_interface.0.access_config.0.assigned_nat_ip}"
}
```

### Expected Behavior
Get the private and public IPs of the created instance.

### Actual Behavior
Nothing is printed, and when I checked the statefile I found something like the following:
```
[...]
     "network_interface.0.access_config.0.assigned_nat_ip": "",
     "network_interface.0.access_config.0.nat_ip": "<the correct public IP>",
     "network_interface.0.address": "",
[...]
```

### Steps to Reproduce
1. `terraform apply`
2. open the statefile to check that `network_interface.0.address` and `network_interface.0.access_config.0.assigned_nat_ip` are not set.

**Comment by danawillow** [comment] 2017-10-06 17:07
This looks like a duplicate of #519 so closing in favor of that (let me know if I'm wrong!)

**Closed by danawillow** 2017-10-06 17:07 UTC

**Comment by anas-aso** [comment] 2017-10-06 17:24
sorry @danawillow for duplicating the issue. I didn't manage to find it myself 😄

**Comment by danawillow** [comment] 2017-10-06 18:28
no worries!
