### ISSUE TITLE
google_container_cluster missing AuthenticatorGroupsConfig 

### ISSUE THREAD

**Issue by philicious** [terraform-providers/terraform-provider-google#3440] opened 2019-04-16 11:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GCP recently added support for [Google Groups for GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#groups-setup-gsuite) to RBAC

The Google API GO package also supports it https://github.com/googleapis/google-api-go-client/blob/master/container/v1beta1/container-gen.go#L375 since 2 weeks

However, the `google_container_cluster` resource from google-beta provider still misses it

### New or Affected Resource(s)

* google_container_cluster

### Potential Terraform Configuration

```tf
authenticator_groups_config {
  disabled = false
  security_group = "gke-security-groups@[yourdomain.com]"
}
```

### References

* #0000

**Comment by philicious** [comment] 2019-04-17 10:34
duplicate of #3407

**Comment by rileykarson** [comment] 2019-05-01 16:40
Closing as dupe of #3407

**Closed by rileykarson** 2019-05-01 16:40 UTC
Labels: enhancement
