### ISSUE TITLE
Transient error: google_project.project: Error retrieving App Engine application ... 503

### ISSUE THREAD

**Issue by drigz** [terraform-providers/terraform-provider-google#2814] opened 2019-01-07 16:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

terraform v0.11.7
* provider.google: version = "~> 1.20"

### Affected Resource(s)

* google_project

### Terraform Configuration Files

_omitted, issue only occurs in our CI job_

### Debug Output

_omitted, issue only occurs in our CI job_

### Panic Output

_omitted, issue only occurs in our CI job_

### Expected Behavior

Terraform should not fail due to a transient 503 error.

### Actual Behavior

Terraform occasionally fails with:

```
Error: Error refreshing state: 1 error(s) occurred:

* google_project.project: 1 error(s) occurred:

* google_project.project: google_project.project: Error retrieving App Engine application "my-project": googleapi: Error 503: The service is currently unavailable., backendError
```

### Steps to Reproduce

_omitted, issue only occurs in our CI job_

### Important Factoids

_omitted, issue only occurs in our CI job_

### References

Should Apps.Get ([call site](https://github.com/terraform-providers/terraform-provider-google/blob/104bbbe70e6d4c9a713afb9c1adc512f85f5857d/google/resource_google_project.go#L379)) be wrapped with `retryTime`? I've made a similar PR before (https://github.com/terraform-providers/terraform-provider-google/pull/1713/files) but since the Apps.Get call has been removed in master/2.0.0 (https://github.com/terraform-providers/terraform-provider-google/pull/2386), I can't see if/how to make this change.

**Comment by emilymye** [comment] 2019-01-07 20:42
We now generate the app engines resource code in Magic Modules, the file would be here: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/resources/resource_app_engine_application.go

**Comment by drigz** [comment] 2019-01-08 10:02
@emilymye Thanks for the info! Will `Apps.Get` still be used by `google_project` in future 1.x releases? See [resource_google_project.go#L379@v1.20.0](https://github.com/terraform-providers/terraform-provider-google/blob/v1.20.0/google/resource_google_project.go#L379). That code was removed from master by https://github.com/terraform-providers/terraform-provider-google/pull/2386 on Nov 2, but was still present in the v1.20.0 release on Dec 14.

**Comment by emilymye** [comment] 2019-01-08 21:41
Yup, that's the plan. @chrisst may have dealt with those retries for 2.x going forward but tagging to make sure.

**Comment by chrisst** [comment] 2019-01-08 21:45
Correct, as of https://github.com/terraform-providers/terraform-provider-google/pull/2568/files we should retry on 503's for all CRUD requests made by generated resources.

**Comment by danawillow** [comment] 2019-05-14 23:03
Closing due to @chrisst's comment, feel free to reopen if the issue is still occurring.

**Closed by danawillow** 2019-05-14 23:03 UTC
Labels: enhancement
