### ISSUE TITLE
Google provider Set IAM policy not remove "deleted:" entries and API returns 400 : Policy members must be of the form "<type>:<value>"., badRequest

### ISSUE THREAD

**Issue by mldmld68** [terraform-providers/terraform-provider-google#5151] opened 2019-12-12 11:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
0.11.14
Provider Google 2.20
### Affected Resource(s)
google_project_iam_member
google_compute_subnetwork_iam_member

### Terraform Configuration Files
```provider "google" {
  region  = "europe-west1" 
 version = "~> 2.20"
}

provider "google-beta" {
  region  = "europe-west1" 
  version = "~> 2.20"
}

terraform {
  backend "gcs" {}
}
```

### Debug Output
https://gist.github.com/mldmld68/34dc19b0e8424e516baa69cfb05d54f4
### Expected Behavior
New IAM policy should be applied.
Terraform should remove the deleted: entries to achieve this.
### Actual Behavior

The updated IAM policy is not applied because API returns
```
Error 400: Policy members must be of the form "<type>:<value>"., badRequest
```
### Steps to Reproduce
I detected it enabling terraform log = trace
The IAM policy was returning this 
$ gcloud beta compute networks subnets get-iam-policy xxxxxx-subnet --region europe-west1  > mypolicy.txt # Warning : Deleted entries are not displayed without redirecting to file or using a grep
$ cat mypolicy.txt
bindings:
- members:
  - deleted:serviceAccount:xxxxx@xxxxxx.iam.gserviceaccount.com?uid=123456789123456789
  - deleted:serviceAccount:xxxx@xxxx.iam.gserviceaccount.com?uid=123456789123456789
  - serviceAccount:NNNNNNNNN@cloudservices.gserviceaccount.com
  - serviceAccount:NNNNNNNNN@cloudservices.gserviceaccount.com
 - serviceAccount:xxxxxxx@xxxxxxx.iam.gserviceaccount.com
<...>

1. `terraform apply`

### Workaround
Export IAM policy of the resource in a file, remove the deleted: entries, set iam policy.
Then rerun terraform apply

**Comment by griffinator76** [comment] 2019-12-13 03:09
I have the exact same issue with `google_storage_bucket_iam_member` resources. The Google API call to `/storage/v1/b/my-bucket/iam?alt=json&prettyPrint=false` returns deleted members for some of the roles, which Terraform then tries to reapply. That results in a HTTP 400 Bad Request error with the message:

> The member deleted:serviceaccount:xxxxx@xxxx.iam.gserviceaccount.com?uid=109581550612306456925 is of an unknown type. Please set a valid type prefix for the member.

**Comment by Jeskz0rd** [comment] 2019-12-13 15:46
Have you checked [this resource](https://cloud.google.com/iam/docs/policies#handle-deleted-members) guys?

Release notes from [9th December](https://cloud.google.com/iam/docs/release-notes)
---

Cloud IAM policies now identify deleted members that are bound to a role. Deleted members have the prefix deleted: and the suffix ?uid=`[NUMERIC_ID]`.

For example, if you delete the account for the user bob@example.com, and a policy binds that user to a role, the policy shows an identifier similar to deleted:user:bob@example.com?uid=123456789012345678901.

For SetIamPolicy requests, you can use this new syntax starting today. For GetIamPolicy and SetIamPolicy responses, because we are still rolling out this change, you might see the new prefix and suffix in some, but not all, responses. We expect to complete the rollout by December 13, 2019.

See the documentation for a [detailed example](https://cloud.google.com/iam/docs/policies#example-deleted-member), as well as guidance on [updating policies that contain deleted members](https://cloud.google.com/iam/docs/policies#handle-deleted-members).

Hope it helps!

**Comment by slevenick** [comment] 2019-12-13 17:58
Looks like this is a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5107

This was caused by the API change that started returning `deleted:` IAM members. A fix will be included in the next release of the provider. I'm going to close this issue in favor of #5107

**Closed by slevenick** 2019-12-13 17:58 UTC
Labels: bug
