### ISSUE TITLE
Missing implicit dependency between pubsub topic

### ISSUE THREAD

**Issue by wyardley** [terraform-providers/terraform-provider-google#2765] opened 2018-12-28 05:58 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.11.10
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
+ provider.null v1.0.0
```

### Affected Resource(s)

* google_pubsub_topic
* google_pubsub_topic_iam_binding

### Terraform Configuration Files

```tf
resource "google_pubsub_topic" "foo" {
  name = "foo"
}

resource "google_pubsub_topic_iam_binding" "foo" {
  topic = "foo"
  role  = "roles/pubsub.publisher"

  members = [
    "serviceAccount:svcacct@someotherproject.iam.gserviceaccount.com",
  ]
}
```

### Debug Output
[not included here; let me know if we need to find a way to provide sanitized debug output]

### Expected Behavior
Terraform creates resources in expected order and completes successfully on the first run

### Actual Behavior
[somewhat sanitized]
Terraform errors like:
```
* google_pubsub_topic_iam_binding.foo: Error retrieving IAM policy for pubsub topic "projects/xxx/topics/foo": googleapi: Error 404: Resource not found (resource=foo)., notFound
* module.foo.google_pubsub_topic_iam_binding.foo: 1 error(s) occurred:
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Applying a second time seems to resolve the issue, so I think it's a dependency / idempotency issue. Adding an explicit dependency between the resources also resolves it (e.g., in the binding resource):

```tf
 depends_on = ["google_pubsub_topic.foo"]
```

Let me know if you feel this is not a bug (seems identical to #2384), but I believe normally these dependencies should not need to be created explicitly?

### References

* #2384

**Comment by Chupaka** [comment] 2018-12-28 10:13
Yes, it's not a bug. `topic = "${google_pubsub_topic.foo.name}"` is an implicit dependency.

**Comment by rileykarson** [comment] 2018-12-28 15:59
Hey @wyardley! @Chupaka is correct. Terraform resource code doesn't know anything about dependencies, the only way to establish the Terraform dependency graph is by interpolating between resources. You can achieve this with an interpolation, or by using `depends_on` which will ensure that the resource is created after the resource it depends on at create time, but does *not* ensure it gets recreated alongside the other resource.

I'm going to close this out since this is Terraform working as intended, but feel free to comment again if you have any more questions!

**Closed by rileykarson** 2018-12-28 15:59 UTC
