### ISSUE TITLE
Error with service account id on google_service_account_iam_member

### ISSUE THREAD

**Issue by angelzamir** [terraform-providers/terraform-provider-google#1321] opened 2018-04-11 19:22 UTC
### Terraform Version
v0.10.8

### Affected Resource(s)
- google_service_account_iam_member

### Terraform Configuration Files
```hcl
resource "google_service_account_iam_member" "service_account_iam_additive" {
  count = "${local.service_account_additive_iam ? length(local.additive_bindings_array) : 0}"
  service_account_id = "${var.service_account}"
  member             = "${element(split(",", local.additive_bindings_array[count.index]), 1)}"
  role               = "${element(split(",", local.additive_bindings_array[count.index]), 0)}"
}
```
Hello, 
Something weird is happening on the resource above. In this case var.service_account = "" and
```hcl 
local.service_account_additive_iam = false
```
and 

```hcl 
length(local.additive_bindings_array) = 5
```
So, the resource shouldn't be created, but with terraform plan command, this happens:

```hcl 
Error: module.iam_binding.google_service_account_iam_member.service_account_iam_additive: "service_account_id" ("") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))/serviceAccounts/[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$"
```

But if I put on the service_account_id a valid service account string like this:

```hcl 
resource "google_service_account_iam_member" "service_account_iam_additive" {
  count = "${local.service_account_additive_iam ? length(local.additive_bindings_array) : 0}"

  service_account_id = "projects/foo-project/serviceAccounts/terraform@foo-project.iam.gserviceaccount.com"

  member             = "${element(split(",", local.additive_bindings_array[count.index]), 1)}"
  role               = "${element(split(",", local.additive_bindings_array[count.index]), 0)}"
}
```
The resource is NOT created and the error disappears when I perform terraform plan

```hcl 
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

One important thing is that this error doesn't happen with google_service_account_iam_binding resource. I have the same logic for count and also the service_account_id value is "", and there's no error.

Thanks!

**Comment by danawillow** [comment] 2018-04-11 20:57
Hey @angelzamir, I'm a bit confused about your use case. Why are you trying to set the `service_account_id` to the empty string?

**Comment by angelzamir** [comment] 2018-04-11 21:02
Hi @danawillow, thanks for the fast response.
Well, the creation of this resource depends if the user sets the service account var, if so, I check that in a variable (service_account_additive_iam), as the user sets the service account variable to "", the boolean (service_account_additive_iam) is false, and the resource shouldn't be created, but it seems that even when count is 0 or whatever else, the resource first evaluate the service_account_id value. Note: this is not happening on google_service_account_iam_binding. Both have the same logic, and in the last one there's no error.

Thanks!

**Comment by danawillow** [comment] 2018-04-11 21:12
Hey @angelzamir, I'm not able to reproduce this. What version of the terraform tool are you using? (`terraform -v` will tell you both the tool and the provider)

Here's the config I tried to repro it, by the way:
```
locals {
  service_account_additive_iam = false
  additive_bindings_array = ["thing1, thing2"]
}

variable "service_account" {
  type = "string"
  default = ""
}

resource "google_service_account_iam_member" "is-1321" {
  count = "${local.service_account_additive_iam ? length(local.additive_bindings_array) : 0}"
  service_account_id = "${var.service_account}"
  member             = "${element(split(",", local.additive_bindings_array[count.index]), 1)}"
  role               = "${element(split(",", local.additive_bindings_array[count.index]), 0)}"
}
```

When running this in an empty directory, it tells me no changes.

**Comment by danawillow** [comment] 2018-04-11 21:38
Ah ok, are you able to upgrade Terraform? 0.10.8 is a fairly old version, and I wouldn't be surprised if this was a bug that's been fixed since then.

**Comment by angelzamir** [comment] 2018-04-11 21:53
I've upgrade it but fails.

**Comment by danawillow** [comment] 2018-04-11 21:56
Hmm ok. If you use the exact config that I posted, does it still fail?

**Comment by angelzamir** [comment] 2018-04-11 21:59
No, it doesn't fail... I'm surprised because the difference is that I call a module. I'll try to reproduce this as a small mirror of my project.

**Comment by angelzamir** [comment] 2018-04-11 22:25
Okay, I think I could and the bug is with the additive_bindings_array variable. If I set it up as a random array, it works, but if I put it like:

```hcl
additive_bindings_array="${compact(split(" ", data.external.script.result["array"]))}"
```
If fails, here the file.

```hcl
locals {
  service_account_additive_iam = "${var.service_account != ""}"
  additive_bindings_array      = "${compact(split(" ", data.external.additive_bindings_array.result["array"]))}"
  roles                        = ["role1", "role2"]
}

variable "service_account" {
  default = ""
}

variable "mode" {
  default = "additive"
}

variable "bindings" {
  type = "map"

  default = {
    "role" = [
      "group:group@domain.com",
    ]

    "role2" = [
      "group:group@domain.com",
    ]

    "role3" = [
      "group:group@domain.com",
    ]
  }
}

data "external" "script" {
  program = ["bash", "${path.module}/scripts/script.sh", "${jsonencode(var.bindings)}"]
}


resource "google_service_account_iam_member" "service_account_iam_additive" {
  count = "${local.service_account_additive_iam ? length(local.additive_bindings_array) : 0}"

  service_account_id = "${var.service_account}"

  member = "${element(split(",", local.additive_bindings_array[count.index]), 1)}"
  role   = "${element(split(",", local.additive_bindings_array[count.index]), 0)}"
}

```

In the script I'm just doing string manipulation and returning a string like:
"string1 string2 string3 string4"

Note: I have several resources under those conditions using the same variables, and only this one fails.

**Comment by angelzamir** [comment] 2018-04-13 20:02
I've changed from the script calling to a null resource calling. The null resource does the same, string manipulation with the map's items, but it fails too.

**Comment by ndmckinley** [comment] 2018-04-17 00:50
I'm trying to understand what the issue is - it seems like it's an issue with the config, and not an issue with the google provider, since the issue shows up even when you use a null data source?

**Comment by angelzamir** [comment] 2018-04-17 15:11
I think is an error with the resource because I have several resources with the same conditions and logic, and this resource is the only one that fails.

I'm building up an array (first with a external provider and then (I changed it) with a null data source); many resources take that array in the count variable in the same way that google_service_account_iam_member does, and this is the only resource that has this problem.

**Comment by ndmckinley** [comment] 2018-04-17 20:43
Right.  What I think is happening is, this resource validates its fields before it sends requests.  It validates them even if the count is 0, which you might be able to argue is a bug - but it'd be a terraform bug, not a provider bug, and you could ask for that to be changed on the main terraform repo.  Other resources might not do that validation.  As a hacky solution, you might try

```hcl
service_account_id = "${local.service_account_additive_iam ? ${var.service_account} : 0}"
```

Does that work?

If not, please post the debug logs - the output you get by running `TF_LOG=debug terraform apply`.

**Comment by angelzamir** [comment] 2018-04-19 16:57
I'm doing it with a local

```hcl
service_account_tmp = "${var.service_account == "" ? "projects/foo-project/serviceAccounts/terraform@foo-project.iam.gserviceaccount.com" : var.service_account}"
```
And in the resource:

```hcl
....
service_account_id = "${local.service_account_tmp}"
...
```
It works. I suppose then it's a terraform bug.

**Comment by morgante** [comment] 2018-04-19 19:52
Do we have a fix for this? @ndmckinley's proposed hack is fine for now.

I'm unsure as to why this only happens on this resource though. Shouldn't all iam resources exhibit the same behavior?

**Comment by ndmckinley** [comment] 2018-04-19 19:58
I don't know if it's a bug at all, but you could probably file on terraform core and see if they would like the idea of not doing validation in the event that `count = 0`.  And @morgante I'm not sure why it's only on this resource.  Can you give me a list of the resources you tried?

**Comment by angelzamir** [comment] 2018-04-19 20:11
@ndmckinley the resources are:

- google_folder_iam_member
- google_kms_crypto_key_iam_member
- google_kms_key_ring_iam_member
- google_organization_iam_member
- google_project_iam_member
- google_pubsub_subscription_iam_member
- google_pubsub_topic_iam_member
- google_storage_bucket_iam_member
- google_compute_subnetwork_iam_member

Same conditions in all for count: 
```hcl
count = ${boolean ? length(the array) : 0}
```
(boolean = false as in this bug)

**Comment by ndmckinley** [comment] 2018-04-19 20:16
Sure.  The only one of those with a `ValidateFunc` that is invalidated by this PR is service account.  See here:

https://github.com/terraform-providers/terraform-provider-google/blob/master/google/iam_service_account.go#L16

Closing because this is WAI.

**Comment by rileykarson** [comment] 2019-03-04 23:55
@morgante if this is still important do you mind opening a separate issue?

**Closed by rileykarson** 2019-03-04 23:55 UTC
Labels: bug
