### ISSUE TITLE
DataProc Cluster  Scheduled deletion, max-age and expiration-time support

### ISSUE THREAD

**Issue by HectorLagos** [terraform-providers/terraform-provider-google#5155] opened 2019-12-12 14:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Please include support for auto terminating the dataproc cluster when based on max-age or expiration-time. Details for both option can be found [here](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/scheduled-deletion). 

### Potential Terraform Configuration

```tf
resource "google_dataproc_cluster" "mycluster" {
    name   = "dproc-cluster-unique-name"
    region = "us-central1"
    max-age = "2d"
    expiration-time = "2020-08-22T13:31:48-08:00"
}
```

**Comment by megan07** [comment] 2019-12-13 23:58
hi @HectorLagos 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #4725  - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #4725  for updates?

Thanks!

**Closed by megan07** 2019-12-13 23:58 UTC
Labels: enhancement
