### ISSUE TITLE
google_storage_bucket_iam_member and google_storage_bucket_iam_binding

### ISSUE THREAD

**Issue by benbro** [terraform-providers/terraform-provider-google#820] opened 2017-12-05 21:56 UTC
Feature request to add google_storage_bucket_iam_member and google_storage_bucket_iam_binding resources.
gutil has IAM set [command](https://cloud.google.com/storage/docs/gsutil/commands/iam).

google_storage_bucket_acl uses legacy roles which aren't compatible with new APIs like signBlob.

### Terraform Version
v0.11.1

### Affected Resource(s)
- google_storage_bucket_iam_member (missing)
- google_storage_bucket_iam_binding (missing)

**Comment by rosbo** [comment] 2017-12-05 22:29
Duplicate of #481. Closing. FYI: I should be able to get to it this week.

**Closed by rosbo** 2017-12-05 22:29 UTC
