### ISSUE TITLE
Add support for `resource_policy_attachment` for `google_compute_region_disk`

### ISSUE THREAD

**Issue by craigwatson** [terraform-providers/terraform-provider-google#5357] opened 2020-01-09 10:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.3.0
+ provider.google-beta v3.3.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* google_compute_disk_resource_policy_attachment

### Terraform Configuration Files

```tf
resource "google_compute_region_disk" "disk" {
  name          = "data"
  type          = "pd-standard"
  size          = "10"
  region        = "europe-west2"
  replica_zones = ["europe-west2-a", "europe-west2-b"]
}

resource "google_compute_resource_policy" "backups" {
  name   = "backups"
  region = "europe-west2"

  snapshot_schedule_policy {

    schedule {
      weekly_schedule {
        day_of_weeks {
          day        = "SATURDAY"
          start_time = "03:00"
        }
      }
    }

    retention_policy {
      max_retention_days    = "30"
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }

    snapshot_properties {
      storage_locations = ["EU"]
      guest_flush       = true
    }
  }
}

resource "google_compute_disk_resource_policy_attachment" "backups" {
  name = google_compute_resource_policy.backups.name
  disk = google_compute_region_disk.disk.name
}
```

### Expected Behavior

* The `google_compute_disk_resource_policy_attachment` resource should allow multiple `zones` (or a single `region` to be specified to account for regional disks (the `zone` parameter is marked as "optional" in documentation).

### Actual Behavior

```
Error: Cannot determine zone: set in this resource, or set provider-level zone.
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/google/r/compute_region_disk.html
* https://www.terraform.io/docs/providers/google/r/compute_disk_resource_policy_attachment.html

**Comment by edwardmedia** [comment] 2020-01-09 21:02
@craigwatson it appears your default zone is not set to the ones you specify in other resources. There is no logic in the provider that will "auto-detect". If you use default values for all resources, this should be fine. I am closing this issue. If you think you need further discussion or assistance, please reopen this or create a new issue. Thanks

**Comment by craigwatson** [comment] 2020-01-09 21:05
@edwardmedia My point is that I'm using a **regional** disk, not **zonal** - the provider's zone shouldn't matter, because the disk is split among two zones - note the `google_compute_region_disk` resource.

**Comment by craigwatson** [comment] 2020-01-09 21:20
@edwardmedia @venkykuberan I don't seem to be able to re-open this issue, but I definitely feel that it's a bug or a feature deficiency - can you please take a look at my response above?

**Comment by venkykuberan** [comment] 2020-01-10 01:24
@craigwatson i have reopened the issue. I reproduced the issue. It seems bug to me as well as i am able to attach the backups schedule to region_disk on the cloud console. Before i conclude can you please provide me a little more detail about your config to have a better understanding. I see in your config you don't use any snapshot link for the region_disk. I am just curious what data does the disk have to backup ?

```
resource "google_compute_disk_resource_policy_attachment" "backups" {
  name = google_compute_resource_policy.backups.name
  disk = google_compute_region_disk.reg_disk.name
}
```
I see that `google_compute_disk_resource_policy_attachment` is looking up the default zone for the disk to attach which is an issue. I will keep this open. 

Please provide me the info. asked above.

**Comment by craigwatson** [comment] 2020-01-10 07:08
@venkykuberan the disk in the posted config above was just a random piece of code I wrote to prove the bug  - our actual code is a little more complex and involves nested modules.

In reality, the disk in question contains application data, which is then backed up by the snapshot policy, so it's a standard persistent "blank" (at the point of creation) disk with no source snapshot or image.

**Comment by venkykuberan** [comment] 2020-01-10 18:20
@craigwatson Thank you for the detail, I have moved this to bug list. It will get prioritized and worked on.

**Comment by chrisst** [comment] 2020-01-23 01:53
@craigwatson you are correct that `google_compute_disk_resource_policy_attachment ` will not work with region_disk's right now. We usually end up supporting the regional use cases by adding new resources rather, but this isn't 100% consistent as some resources do transparently support both.

Unfortunately because zone and region can be specified in environment variables or the provider block, it's hard to know what the correct url to construct is unless those fields are required on the resource itself. But requiring zone or region on this resource would be a breaking change for all the configs that have been inheriting this value. 

To avoid a breaking change to this resource I think it's best added as a new resource, `google_compute_region_disk_resource_policy_attachment`, similarly to the other `compute_region_*` resources.

**Comment by craigwatson** [comment] 2020-01-27 14:26
@chrisst thanks for the response and the clarification on documentation :)

@venkykuberan are you able to confirm if there's an ETA on the `google_compute_region_disk_resource_policy_attachment` being added to the provider?

**Closed** 2020-03-07 01:03 UTC
Labels: enhancement, new-resource, priority/0, size/M
