### ISSUE TITLE
Add `force_destroy` field for google_dns_managed_zone

### ISSUE THREAD

**Issue by ensonic** [terraform-providers/terraform-provider-google#2305] opened 2018-10-23 07:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently we need to write out own script to flush a managed zone before deletion:
https://gist.github.com/ensonic/78cd078e806cd2592a62b0e7994b0e8d

Similarly to the `google_storage_bucket` resource, we should have a force_destroy flag that we can set to delete all entries on destroy.

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration

```tf
resource "google_dns_managed_zone" "my-dns-zone" {
  name = "my-dns-zone"
  dns_name = "${var.domain}."
  description = "...."
  depends_on = ["google_project_service.dns"]
  force_destroy = true
}
```

### References

* #2050

**Comment by ensonic** [comment] 2018-10-23 07:49
If you agree that this is the way to go an maybe provide some pointers I can try to make a PR.

**Comment by danawillow** [comment] 2019-05-14 23:21
Closing as a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/1572

**Closed by danawillow** 2019-05-14 23:21 UTC
Labels: enhancement
