### ISSUE TITLE
Changing `workload_metadata_config` on `google_container_node_pool` forces replacement

### ISSUE THREAD

**Issue by eyalzek** [terraform-providers/terraform-provider-google#5937] opened 2020-03-20 12:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
v0.12.23

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```tf
resource "google_container_node_pool" "node_pool" {
  project  = var.project
  cluster  = google_container_cluster.cluster.id
  location = var.region

  initial_node_count = 0

  autoscaling {
    max_node_count = var.autoscaling.max
    min_node_count = var.autoscaling.min
  }

  management {
    auto_repair  = false
    auto_upgrade = false
  }

  node_config {
    disk_size_gb = 25
    disk_type    = "pd-ssd"
    image_type   = "COS"

    machine_type = "n1-standard-2"

    service_account = google_service_account.gke_default.email

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/userinfo.email",
    ]

    workload_metadata_config {
      node_metadata = "GKE_METADATA_SERVER"
    }
  }

  version = var.nodes_version
}
```

### Expected Behavior

changing the workload metadata config is possible inline (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_workload_identity_on_an_existing_cluster) with the command:
```
gcloud container node-pools update nodepool-name \
  --cluster=cluster-name \
  --workload-metadata-from-node=GKE_METADATA
```

### Actual Behavior

changing the value from `SECURE` -> `GKE_METADATA` forces a replacement of the resource:
```
         ~ workload_metadata_config {
              ~ node_metadata = "SECURE" -> "GKE_METADATA_SERVER" # forces replacement
            }
```

### Steps to Reproduce

1. `terraform apply` (the above config)

2. replace `GKE_METADATA` with `SECURE`

3. `terraform apply`

4. resource will be recreated

### References

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_workload_identity_on_an_existing_cluster

* #0000

**Comment by venkykuberan** [comment] 2020-03-20 17:41
`metadata` is set to `ForNew` in the node config schema which is causing the replacement.  I will move this one to code change bucket. will get prioritized and picked up to work .

**Comment by slevenick** [comment] 2020-03-26 19:34
Looks like a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/4041

Closing in favor of that request

**Closed by slevenick** 2020-03-26 19:34 UTC
Labels: bug
