### ISSUE TITLE
private sql_database_instance cannot be updated

### ISSUE THREAD

**Issue by samhagan** [terraform-providers/terraform-provider-google#2761] opened 2018-12-28 00:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
+ provider.google-beta v1.20.0
```

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
resource "google_project_service" "service_networking" {
  service            = "servicenetworking.googleapis.com"
  disable_on_destroy = false
}

resource "google_project_service" "sql" {
  service            = "sqladmin.googleapis.com"
  disable_on_destroy = false
}

resource "google_compute_network" "private_network" {
  name = "private-network"
}

resource "google_compute_global_address" "private_ip_address" {
  provider      = "google-beta"
  name          = "private-ip-address"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "${google_compute_network.private_network.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
  provider                = "google-beta"
  depends_on              = ["google_project_service.service_networking"]
  network                 = "${google_compute_network.private_network.self_link}"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.name}"]
}

resource "google_sql_database_instance" "instance" {
  depends_on = [
    "google_service_networking_connection.private_vpc_connection",
    "google_project_service.sql",
  ]

  name   = "private-instance-1"
  region = "us-central1"

  settings {
    tier = "db-f1-micro"

    maintenance_window {
      day          = 1
      hour         = 1
      update_track = "stable"
    }

    ip_configuration {
      ipv4_enabled    = false
      private_network = "${google_compute_network.private_network.self_link}"
    }
  }
}
```

### Debug Output

[Debug Output](https://gist.github.com/samhagan/759b1da0df74b765fb31b6d9e363b0e2)

### Expected Behavior

cloud SQL instance should have been created with `ipv4_enabled` set to false.

### Actual Behavior

After creation, running plan returns the following:
```
Terraform will perform the following actions:

  ~ google_sql_database_instance.instance
      settings.0.ip_configuration.0.ipv4_enabled: "true" => "false"
```

Trying to apply returns the following error:
```
* google_sql_database_instance.instance: Error, failed to update instance private-instance-1: googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation
```

### Steps to Reproduce

1. create a private sql instance using above config
1. run `terraform apply` after creation and you should get a plan to change `ipv4_enabled` from true to false. Apply will fail.

### Important Factoids

The issue appears to be that it is sending `ipConfiguration: {}` instead of:

```json
"ipConfiguration": {
    "ipv4Enabled": false,
    "authorizedNetworks": [],
    "requireSsl": false,
    "privateNetwork": "projects/<project>/global/networks/private-network"
}
```

### References

* #0000

**Comment by Chupaka** [comment] 2018-12-28 10:05
Please check the docs, "The IPv4 address cannot be disabled for Second Generation instances."

**Comment by samhagan** [comment] 2018-12-28 13:53
I believe the docs must be out of date, as I have confirmed that you can disabled ipv4 via the console and gcloud.

I selected `ipv4_enabled` as the example because it is the first issue you encounter when using the example: https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance. 

The general issue can be reproduced with the following:

1. using the configuration above, set `ipv4_enabled = true` and create the instance
2. try to modify anything (e.g. db size) and it will return the same error.

```
* google_sql_database_instance.instance: Error, failed to update instance private-instance-4: googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation

```

The issue is that it doesn't send the `privateNetwork` field, which cannot changed.
```json
"ipConfiguration": {
    "ipv4Enabled": true
},
```

Though I have confirmed that this issue is fixed v2.0.

**Comment by rileykarson** [comment] 2019-01-02 19:21
I can't reproduce this; this plan is succeeding when using the config above:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_sql_database_instance.instance
      settings.0.ip_configuration.0.ipv4_enabled: "true" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Does yours look identical?

**Comment by samhagan** [comment] 2019-01-02 20:58
Plan always works for me, but the apply fails. Does it apply correctly?

**Comment by rileykarson** [comment] 2019-01-02 21:35
Yep, it works correctly for me- I'm running off HEAD and not the release, though.

I think I've found why; my PUT looks like this:

```
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: ---[ REQUEST ]---------------------------------------
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: PUT /sql/v1beta4/projects/graphite-test-rileykarson/instances/private-instance-1423423452352z?alt=json&prettyPrint=false HTTP/1.1
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: Host: www.googleapis.com
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: User-Agent: google-api-go-client/0.5 Terraform/0.12.0 (+https://www.terraform.io) terraform-provider-google/dev
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: Content-Length: 464
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: Content-Type: application/json
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: Accept-Encoding: gzip
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: {
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:  "settings": {
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "activationPolicy": "ALWAYS",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "backupConfiguration": {
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "startTime": "06:00"
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   },
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "dataDiskSizeGb": "10",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "dataDiskType": "PD_SSD",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "ipConfiguration": {
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "ipv4Enabled": false,
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "privateNetwork": "projects/graphite-test-rileykarson/global/networks/private-network",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "requireSsl": false
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   },
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "maintenanceWindow": {
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "day": 1,
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "hour": 1,
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:    "updateTrack": "stable"
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   },
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "pricingPlan": "PER_USE",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "replicationType": "SYNCHRONOUS",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "settingsVersion": "2",
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "storageAutoResize": true,
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:   "tier": "db-f1-micro"
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google:  }
2019-01-02T11:14:32.244-0800 [DEBUG] plugin.terraform-provider-google: }
```

vs yours:

```
---[ REQUEST ]---------------------------------------
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: PUT /sql/v1beta4/projects/<project>/instances/private-instance-1?alt=json&prettyPrint=false HTTP/1.1
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: Host: www.googleapis.com
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: User-Agent: google-api-go-client/0.5 Terraform/0.11.7 (+https://www.terraform.io) terraform-provider-google/1.20.0
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: Content-Length: 2516
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: Content-Type: application/json
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: Accept-Encoding: gzip
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "backendType": "SECOND_GEN",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "connectionName": "<project>:us-central1:private-instance-1",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "databaseVersion": "MYSQL_5_6",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "etag": "74282b577b1988bf1a3905b62ed4d8dba14c67f2d96097b7b2088bffe5c01ebe",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "gceZone": "us-central1-a",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "instanceType": "CLOUD_SQL_INSTANCE",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "ipAddresses": [
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "ipAddress": "35.202.249.198",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "type": "PRIMARY"
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   },
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "ipAddress": "10.7.0.4",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "type": "PRIVATE"
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   }
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  ],
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "kind": "sql#instance",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "name": "private-instance-1",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "project": "<project>",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "region": "us-central1",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "selfLink": "https://www.googleapis.com/sql/v1beta4/projects/<project>/instances/private-instance-1",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "serverCaCert": {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "cert": "cert",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "certSerialNumber": "0",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "commonName": "C=US,O=Google\\, Inc,CN=Google Cloud SQL Server CA",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "createTime": "2018-12-27T23:21:10.053Z",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "expirationTime": "2028-12-24T23:22:10.053Z",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "instance": "private-instance-1",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "kind": "sql#sslCert",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "sha1Fingerprint": "e6219efe08e831791c3aca672031b1e38b32c2cf"
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  },
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "serviceAccountEmailAddress": "email",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "settings": {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "activationPolicy": "ALWAYS",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "backupConfiguration": {
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "startTime": "10:00"
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   },
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "dataDiskType": "PD_SSD",
2018-12-27T15:29:49.925-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "ipConfiguration": {},
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "locationPreference": {},
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "maintenanceWindow": {
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "day": 1,
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "hour": 1,
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:    "updateTrack": "stable"
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   },
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "pricingPlan": "PER_USE",
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "replicationType": "SYNCHRONOUS",
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "settingsVersion": "1",
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "storageAutoResize": true,
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:   "tier": "db-f1-micro"
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  },
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4:  "state": "RUNNABLE"
2018-12-27T15:29:49.926-0800 [DEBUG] plugin.terraform-provider-google_v1.20.0_x4: }
```

We had some weird Update behaviour before that I think is the issue - this will be fixed by https://github.com/terraform-providers/terraform-provider-google/pull/2203 (which despite being made a while ago has not made it into a release yet). It will come with `2.0.0` since it's a breaking change.

**Closed by rileykarson** 2019-01-02 21:35 UTC
Labels: bug
