### ISSUE TITLE
create_before_destroy lifecycle propagated to the dependent objects

### ISSUE THREAD

**Issue by Nmishin** [terraform-providers/terraform-provider-google#647] opened 2017-10-30 15:55 UTC
Hi there,
When I try to update my infrastructure - object in the google_storage_bucket_object created but deleted on the end of `terraform apply` circle. 
create_before_destroy = false for google_storage_bucket_object don't help.

### Terraform Version
Tested on Terraform v0.9.4 and Terraform v0.10.7

### Affected Resource(s)
- google_compute_instance_template
- google_storage_bucket_object

### Terraform Configuration Files
```hcl
variable "project" {
    description = "GCP project"
}
variable "region" {
    description = "GCP Region"
}

variable "machine_type" {
    description = "GCE Machine type"
}

provider "google" {
    project     = "${var.project}"
    region      = "${var.region}"
}

resource "google_compute_instance_template" "default" {
  name_prefix  = "instance-template-"

  machine_type         = "${var.machine_type}"

  disk {
    source_image = "source_image"
    auto_delete  = true
    boot         = true
  }

  network_interface {
    subnetwork_project = "subnetwork_project"
    subnetwork         = "subnetwork"
  }

  metadata {
    object = "${google_storage_bucket_object.test_object.name}"
  }
    
  lifecycle {
      create_before_destroy = true
  }

}

resource "google_compute_instance_group_manager" "instance_group_manager" {
  name               = "instance-group-manager"
  instance_template  = "${google_compute_instance_template.default.self_link}"
  base_instance_name = "instance-group-manager"
  zone               = "us-central1-f"
  target_size        = "1" 
}

resource "google_storage_bucket_object" "test_object" {
    name   = "test_object"
    bucket = "bucket"
    source = "${path.module}/test_object"
}
```

### Output
google_storage_bucket_object.test_object.deposed: Destroying... (ID: test_object)
google_storage_bucket_object.test_object.deposed: Destruction complete after 0s

### Expected Behavior
Old google_storage_bucket_object must be deleted, and new must be added.
Or add please explanation of create_before_destroy work to the documentation.

### Actual Behavior
New try to add but deleted at the end of `terraform apply`. 

### Steps to Reproduce
1. `terraform apply`
2.  Rename folder where you do `terraform apply`
3. `terraform apply` with new variable - for updating infrastructure

### Related comment about "deposed" state:
https://github.com/hashicorp/terraform/issues/10753#issuecomment-267638933

**Comment by paddycarver** [comment] 2017-11-09 20:28
Hey @Nmishin, thanks for the report! Sorry you're having issues. I'm trying to follow what's going on here, can you just confirm that this recap is accurate for me? And if it isn't, I'd love to be corrected, so we can get to the bottom of what's going on here.

1. You use the config above to try and create an instance group manager, an instance template, and a storage object.
2. You run Terraform apply.
3. The object is created.
4. You run Terraform apply again.
5. The object is destroyed.

This is certainly very bizarre, and should not be happening. Again, if I've gotten the actions taken and their results wrong, would love to be corrected.

If the above is correct, I'd love a debug log from the second apply: https://www.terraform.io/docs/internals/debugging.html

**Comment by paddycarver** [comment] 2017-11-09 21:05
So that last comment wasn't awesome. This time, trying to be clearer. I think I understand what you're doing, and have tried following the steps myself: https://asciinema.org/a/146770

In my case, things worked as they should. Are those the steps you're following? If not, can you tell me where I went wrong? Thanks!

**Comment by Nmishin** [comment] 2017-11-10 16:48
Hi @paddycarver, thank you for responding!
About you question: I try to update machine_type.

Yes, as I can understand - you forgot about two things:

1. google_storage_bucket_object should depend on the object with 
```
 lifecycle {
      create_before_destroy = true
  }
```
2. You create random object name for "google_storage_bucket", and even if you do not rename the folder - your object will be recreated. 

 As you can see in Output, google_storage_bucket_object.test_object have deposed state which told us ""Deposed" is the state a resource goes into when Terraform is dealing with create_before_destroy..."

**Comment by paddycarver** [comment] 2017-12-07 20:37
Hey @Nmishin, can you clarify what you mean by "create random object name"? Your config doesn't seem to be creating a random object name... it seems to be hardcoded in as "test_object"?

Also, how does your `storage_bucket_object` depend on the object? If you could show the exact config you're using, that would be really helpful in getting a reproduction of your problem so we can fix it.

Thanks!

**Comment by paddycarver** [comment] 2018-03-01 05:27
This hasn't gotten a response for some time, so I'm going to close it out. If someone runs into this issue, feel free to open a new issue!

**Closed by paddycarver** 2018-03-01 05:27 UTC
Labels: bug, waiting-response
