### ISSUE TITLE
google_compute_project_metadata: "Invalid value 'common_metadata'" after upgrade from v1.15

### ISSUE THREAD

**Issue by Chupaka** [terraform-providers/terraform-provider-google#3326] opened 2019-03-27 11:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

TFE 0.11.7
terraform-provider-google v2.3.0

### Affected Resource(s)

* google_compute_project_metadata

### Expected Behavior

After removing provider version restriction "~ 1.15.0" and queueing plan - no changes, no errors.

### Actual Behavior

```
Error refreshing state: 1 error(s) occurred:

* google_compute_project_metadata.default: 1 error(s) occurred:

* google_compute_project_metadata.default: google_compute_project_metadata.default: Error reading Project metadata for project "common_metadata": googleapi: Error 400: Invalid value 'common_metadata'. Values must match the following regular expression: '(?:(?:[-a-z0-9]{1,63}\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))', invalidParameter
```

### Steps to Reproduce

1. Upgrade from provider version 1.15 to 2.3
2. `terraform plan`

I thought it should be fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/1207

### References

* #2699 
* https://github.com/GoogleCloudPlatform/magic-modules/pull/1207

**Comment by benbro** [comment] 2019-04-09 22:21
I'm also getting this error. Any workaround?

**Comment by Chupaka** [comment] 2019-04-10 10:14
@emilymye maybe? As the author of https://github.com/GoogleCloudPlatform/magic-modules/pull/1207... :)

**Comment by Bob-Thomson** [comment] 2019-08-13 12:25
@benbro  there is a workaround yes, see original issue - https://github.com/terraform-providers/terraform-provider-google/issues/2699

**Comment by edwardmedia** [comment] 2020-04-07 22:59
I think this is no longer an issue. I have tested `google_compute_project_metadata` upgrade from **v.2.6.0** to **v3.16.0**, and no change is found in the plan. 
I am closing this issue. Please feel free to reopen if the issue is not resolved.

**Closed by edwardmedia** 2020-04-07 22:59 UTC
Labels: bug

**Comment by Chupaka** [comment] 2020-04-08 10:54
> I have tested google_compute_project_metadata upgrade from v.2.6.0 to v3.16.0

Could you please test the upgrade from v1.15, not v2.6?.. The initial problem is with v1.15...
