### ISSUE TITLE
Add `iot_device` resource to GCP IoT Core

### ISSUE THREAD

**Issue by techjacker** [terraform-providers/terraform-provider-google#5175] opened 2019-12-15 09:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
 [GCP IoT Core docs](https://cloud.google.com/iot/docs/how-tos/devices#creating_or_editing_a_device) on how to create a device.

Currently I'm having to do this via the CLI:
```console
$ gcloud iot devices create DEVICE_ID \
  --project=PROJECT_ID \
  --region=REGION \
  --registry=REGISTRY_ID \
  --public-key path=rsa_public.pem,type=rsa-pem
```

### New or Affected Resource(s)
* google_cloudiot_device

### Potential Terraform Configuration
```tf
locals {
  ca_private_key = "rsa_private_key.pem"
  ca_cert = "rsa_cert.pem"
}

resource "google_cloudiot_registry" "default-registry" {
  name = "default-registry"
  credentials {
    public_key_certificate = {
      format      = "X509_CERTIFICATE_PEM"
      certificate = file(local.ca_cert)
    }
  }
}

resource "google_cloudiot_device" "device-one" {
  name = "device-one"
  registry = google_cloudiot_registry.default-registry.id
  credentials {
    public_key_certificate = {
      format      = "X509_CERTIFICATE_PEM"
      certificate = tls_locally_signed_cert.device-one-cert.cert_pem
    }
  }
}

resource "tls_locally_signed_cert" "device-one-cert" {
  cert_request_pem   = file("cert_request.pem")
  ca_key_algorithm   = "RS256"
  ca_private_key_pem = file(local.ca_private_key)
  ca_cert_pem        = file(local.ca_cert)

  validity_period_hours = 48

  allowed_uses = [
    "data_encipherment",
    "digital_signature",
  ]
}
```

### References
Stemmed from: https://github.com/terraform-providers/terraform-provider-google/issues/5157

**Comment by danawillow** [comment] 2019-12-16 17:57
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/1495

**Closed by danawillow** 2019-12-16 17:57 UTC
Labels: enhancement
