### ISSUE TITLE
Feature Request: GCP Application Level Secrets Encryption for GKE

### ISSUE THREAD

**Issue by huang-jy** [terraform-providers/terraform-provider-google#3400] opened 2019-04-09 08:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There is a feature provided by Google for GKE clusters called Application Level Secrets Encryption: https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets

This however can only be enabled (at the moment) on creation of a cluster and only via the gcloud cli. There is no way at present to enable this using Terraform. I raised this as a GCP support ticket and they advised a feature request would be the best way forward.

Creating a cluster using the gcloud cli and then updating it using Terraform would likely tear the cluster down and rebuild it, losing the ALSE setting

### New or Affected Resource(s)

* google_container_cluster
* google_provider

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-central1"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count = 1

  # Setting an empty username and password explicitly disables basic auth
  master_auth {
    username = ""
    password = ""
  }

  secrets_encryption {
    key="/path/to/kms/key"
  }
}
```

**Comment by danawillow** [comment] 2019-05-14 21:17
This looks like a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3315 (but please correct me if not), closing.

**Closed by danawillow** 2019-05-14 21:17 UTC
Labels: enhancement

**Comment by danawillow** [comment] 2019-05-14 21:19
(and if it is the same feature, it was added in https://github.com/terraform-providers/terraform-provider-google-beta/pull/649)
