### ISSUE TITLE
google_container_cluster creating cluster in the wrong project

### ISSUE THREAD

**Issue by apenney** [terraform-providers/terraform-provider-google#1008] opened 2018-01-25 21:02 UTC
### Terraform Version

» terraform -v
Terraform v0.11.2
+ provider.google v1.5.0
+ provider.random v1.1.0

### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
```hcl
» cat kubernetes.tf
module "kubernetes" {
  source               = "../../modules/kubernetes"
  environment          = "development"
  image_type           = "ubuntu"
  machine_type         = "n1-standard-4"
  master_auth_password = "test"
  master_auth_username = "development"
  name                 = "development"
  node_count           = 1
  preemptible          = true
  project              = "${var.project_id}"
  service_account      = "kubernetes@${var.project_id}.iam.gserviceaccount.com"
  zone                 = "us-central1-a"

  additional_zones = [
    "us-central1-b",
    "us-central1-c"
  ]
}

This then calls:

» cat ../../modules/kubernetes/main.tf
variable "additional_zones" {
  type = "list"
}
variable "environment" {}
variable "image_type" {
  default = "ubuntu"
}
variable "machine_type" {
  default = "n1-standard-1"
}
variable "master_auth_password" {}
variable "master_auth_username" {}
variable "name" {}
variable "node_count" {}
variable "preemptible" {
  default = false
}
variable "project" {}
variable "service_account" {}
variable "zone" {}

variable "oauth_scopes" {
  default = [
    "https://www.googleapis.com/auth/compute",
    "https://www.googleapis.com/auth/devstorage.read_only",
    "https://www.googleapis.com/auth/logging.write",
    "https://www.googleapis.com/auth/monitoring",
  ]

}

resource "google_container_cluster" "primary" {
  name               = "${var.name}"
  additional_zones   = [ "${var.additional_zones}" ]
  initial_node_count = "${var.node_count}"
  project            = "${var.project}"
  zone               = "${var.zone}"

  master_auth {
    username = "${var.master_auth_username}"
    password = "${var.master_auth_password}"
  }

  node_config {
    image_type      = "${var.image_type}"
    machine_type    = "${var.machine_type}"
    oauth_scopes    = [ "${var.oauth_scopes}" ]
    preemptible     = "${var.preemptible}"
    service_account = "${var.service_account}"
    tags            = ["${var.environment}"]

    labels {
      Environment = "${var.environment}"
    }
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "05:00"
    }
  }

}

# The following outputs allow authentication and connectivity to the GKE Cluster.
output "client_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.client_certificate}"
}

output "client_key" {
  value = "${google_container_cluster.primary.master_auth.0.client_key}"
}

output "cluster_ca_certificate" {
  value = "${google_container_cluster.primary.master_auth.0.cluster_ca_certificate}"
}
```

### Debug Output
https://gist.github.com/apenney/b4f176ba802e3b73de9f2e9b20709924

### Expected Behavior
The cluster should be created in the "development" project.

### Actual Behavior
It tried to check the API status in the project that the backend is in.

I have:
```
provider "google" {
  project = "${var.project_id}"
  region  = "${var.region}"
}
```

As well, and project_id is right:

```
» ag project_id terraform.tfvars
4:project_id      = "development-e7d923ca"
```

I'm totally baffled!

**Comment by danawillow** [comment] 2018-01-25 21:19
Hey @apenney, sorry for the trouble! Would you mind getting some debug logs for me? You can do that by running `TF_LOG=DEBUG terraform apply`.

**Comment by apenney** [comment] 2018-01-25 22:30
https://gist.github.com/apenney/f0e462554c33b5e8746d61ac7ee0bfa2 - I redacted a couple of emails, etc, I don't think there's anything sensitive left in there (I hope!)

**Comment by danawillow** [comment] 2018-01-25 23:00
Hmm it looks like the logs got a bit clobbered at places and I think the request I'm looking for didn't make it in. Can you try again, this time redirecting the output in case that was what did it? `TF_LOG=DEBUG terraform apply 2>debug.txt`

**Comment by apenney** [comment] 2018-01-25 23:15
[debug.txt](https://github.com/terraform-providers/terraform-provider-google/files/1666019/debug.txt)

I was hoping to avoid certain bits of the output, but I don't want to kill your ability to troubleshoot so here's the entire unmodified output.

**Comment by danawillow** [comment] 2018-01-26 00:31
Thank you! I downloaded the file so if you want to remove it from here to make it less public feel free to do so.

So the answer is that the service account you're using to run Terraform is in the cota-terraform-admin project, and that project doesn't have the container API enabled. I don't know why it works out in GCP that the project the service account belongs to is the one that needs to have the API enabled (I assume both of them really do), but if you enable the API it'll create the cluster in the correct project.

I was able to repro both the problematic output and the solution with enabling the API, so I'm going to go ahead and close this issue but if enabling the API doesn't fix it let me know and I'll reopen!

**Closed by danawillow** 2018-01-26 00:31 UTC

**Comment by apenney** [comment] 2018-01-26 13:34
I just wanted to say thank you @danawillow for looking into this for me!  I definitely appreciate it.  I'll ask google what's up with that, because it's... definitely a little weird that it needs them in both projects, but it did work afterwards.  Weird stuff!

**Comment by kim0** [comment] 2018-04-26 14:16
Thanks @danawillow for helping out .. I was just banging my head on this for the past few hours. Very unexpected behavior indeed! @apenney Did Google guys ever explain what's up with that? Thanks!
