### ISSUE TITLE
Google Storage ACL not applied after object update

### ISSUE THREAD

**Issue by timwsuqld** [terraform-providers/terraform-provider-google#2213] opened 2018-10-10 04:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.8
+ provider.google v1.19.0
```

### Affected Resource(s)

* google_storage_object_acl
* google_storage_bucket_object

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "org_public" {
  name          = "org_public"
  location      = "US"
  storage_class = "MULTI_REGIONAL"
}

resource "google_storage_bucket_object" "bootstrap_linux" {
  name   = "bootstrap_linux.sh"
  source = "./scripts/bootstrap_linux.sh"
  bucket = "${google_storage_bucket.org_public.name}"
}

resource "google_storage_object_acl" "bootstrap_linux-acl" {
  bucket = "${google_storage_bucket.org_public.name}"
  object = "${google_storage_bucket_object.bootstrap_linux.name}"

  predefined_acl = "publicRead"
}
```

### Debug Output
When changing the bucket_object, it doesn't trigger that the object_acl needs to be reapplied.

```
data.terraform_remote_state.suqld_core_state: Refreshing state...
google_storage_bucket.org_public: Refreshing state... (ID: org_public)
google_storage_bucket_object.bootstrap_linux: Refreshing state... (ID: org_public-bootstrap_linux.sh)
google_storage_object_acl.bootstrap_linux-acl: Refreshing state... (ID: bootstrap_linux.sh-acl)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ google_storage_bucket_object.bootstrap_linux (new resource required)
      id:             "org_public-bootstrap_linux.sh" => <computed> (forces new resource)
      bucket:         "org_public" => "org_public"
      content_type:   "text/plain; charset=utf-8" => <computed>
      crc32c:         "FshAmA==" => <computed>
      detect_md5hash: "YTxGlR/gtM3nOD1QZG+QxA==" => "different hash" (forces new resource)
      md5hash:        "YTxGlR/gtM3nOD1QZG+QxA==" => <computed>
      name:           "bootstrap_linux.sh" => "bootstrap_linux.sh"
      source:         "../scripts/bootstrap_linux.sh" => "../scripts/bootstrap_linux.sh"
      storage_class:  "MULTI_REGIONAL" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behavior

After modifying `./scripts/bootstrap_linux.sh`, Terraform should update the object in the cloud storage bucket, and it should have the correct ACL

### Actual Behavior

The object is updated, but the ACL is no longer applied, and the object becomes private instead of public. Rerunning terraform doesn't detect that this ACL is no longer correct.

### Steps to Reproduce

1. `terraform apply`
2. Confirm that bootstrap_linux.sh in org_public bucket is actually public
3. Modify ./scripts/bootstrap_linux.sh
4. `terraform apply`
5. Confirm that bootstrap_linux.sh in org_public bucket has been updated, and is no longer public

**Comment by danawillow** [comment] 2018-10-10 17:07
@rileykarson, does this get fixed with the stuff you've been working on?

**Comment by paddycarver** [comment] 2018-10-10 19:29
I forget who I was talking to about it, or if I was just thinking about it, but couldn't we expand `predefined_acl` into the actual ACLs it represents, and set `predefined_acl` based on the actual ACLs returned from the server, so no matter which the user sets, we have both in state? Would that help in this case?

**Comment by rileykarson** [comment] 2018-10-10 19:50
That was me! I tried doing that, but I ended up running into something that made me decide against it. I forget what now - either we didn't have enough information to create all of the ACLs, or there was some technical limitation. I can revisit it if you feel strongly about this, although I'd like to do that as a followup to #2187 instead of part of it if I do.

It's worth noting that this would lead to needing 2 `terraform apply`'s in this case. It doesn't solve the underlying issue.

**Comment by paddycarver** [comment] 2018-10-10 20:37
I am 1000% willing to believe my half-baked idea did not work as intended, and I do not feel strongly about making you investigate further if you've already investigated and decided it was untenable. I believe you. :D

**Comment by timwsuqld** [comment] 2018-10-10 23:49
Not really knowing the internals, but can we interpolate on 2 fields, md5sum and name?

**Comment by rileykarson** [comment] 2018-10-15 15:30
Oh, I'm sorry! This slipped through the cracks for me. I'd like to avoid needing to interpolate on 2 fields here; ideally interpolating on `name` will just work how we expect. I'll track https://github.com/hashicorp/terraform/issues/19052 until we get closer to 2.0.0, and if nothing comes of it when it's almost time to cut a release, I have a couple solutions in mind.

**Comment by JackDavidson** [comment] 2019-01-09 22:22
@rileykarson Any updates on this? This is a problem for me, and I cant figure out any workaround. Do you know of any workarounds for now?

**Closed** 2019-01-23 21:23 UTC
Labels: bug, upstream-terraform

**Comment by drigz** [comment] 2019-02-21 16:24
@rileykarson Am I using the workaround wrong? I find that it only works every second time:

```
resource "google_storage_object_access_control" "public_rule" {
  object = "${google_storage_bucket_object.object.output_name}"
  bucket = "${google_storage_bucket.bucket.name}"
  role   = "READER"
  entity = "allUsers"
}

resource "google_storage_bucket" "bucket" {
  name = "my-test-bucket-9835"
}

 resource "google_storage_bucket_object" "object" {
  name   = "public-object"
  bucket = "${google_storage_bucket.bucket.name}"
  source = "hello.txt"
}
```

Repeated changes to hello.txt:

```
while true; do echo $RANDOM > hello.txt && terraform apply -auto-approve | grep Apply.complete; sleep 5; done
Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

"2 added" means that the ACL has been correctly recreated, but "1 added" means that it has not. In the end, I worked around this by making the bucket and its contents public by using IAM:

```
resource "google_storage_bucket_iam_member" "bucket-acl" {
  bucket = "${google_storage_bucket.bucket.name}"
  role   = "roles/storage.objectViewer"
  member = "allUsers"
}
```
