### ISSUE TITLE
Empty taint config block when using nvidia.com/gpu key on GKE

### ISSUE THREAD

**Issue by michal0A** [terraform-providers/terraform-provider-google#4520] opened 2019-09-23 11:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.8
+ provider.google v2.15.0
+ provider.google-beta v2.15.0

### Affected Resource(s)

google_container_node_pool

### Terraform Configuration Files
```
resource "google_container_node_pool" "gpu_node_pool" {
  provider = "google-beta"

  name     = "gpu_node_pool"

  zone   = "${var.zone}"
  cluster  = "${google_container_cluster.cluster.name}"

  node_config {
    machine_type     = "n1-standard-4"

    guest_accelerator {
      type  = "nvidia-tesla-k80",
      count = 1
    }

    taint {
      key    = "nvidia.com/gpu"
      value  = "present"
      effect = "NO_SCHEDULE"
    }
  }
}

```
### Debug Output
```
2019/09/23 12:34:56 [WARN] Provider "google-beta" produced an invalid plan for module.research.module.gcp_node_pool.google_container_node_pool.node_pools[2], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .management[0].auto_repair: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .node_config[0].preemptible: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .node_config[0].taint[1].effect: planned value cty.NullVal(cty.String) does not match config value cty.StringVal("NO_SCHEDULE")
      - .node_config[0].taint[1].key: planned value cty.NullVal(cty.String) does not match config value cty.StringVal("nvidia.com/gpu")
      - .node_config[0].taint[1].value: planned value cty.NullVal(cty.String) does not match config value cty.StringVal("present")
```
### Expected Behavior
```
+ taint {
     + effect = "NO_SCHEDULE"
     + key    = "nvidia.com/gpu"
     + value  = "present"
}
```
### Actual Behavior
```
+ taint {}
```
### Steps to Reproduce

Apply the configuration defined above with:

1. `terraform apply`

### Important Factoids
it works for anything else in "key" field. Even "nvidia.com/gpu " "works", of course it is not valid later during api validation but at least this outpus looks right:

```
+ taint {
     + effect = "NO_SCHEDULE"
     + key    = "nvidia.com/gpu "
     + value  = "present"
}
```

### References

I guess this one is related:

https://github.com/terraform-providers/terraform-provider-google/issues/2295

* #0000

**Comment by rileykarson** [comment] 2019-09-23 20:44
This will end up overlapping a lot with https://github.com/terraform-providers/terraform-provider-google/issues/4168, closing as a duplicate of that.

**Closed by rileykarson** 2019-09-23 20:44 UTC
Labels: bug
