### ISSUE TITLE
Perpetual diff with google_compute_instance's network_interface.0.*

### ISSUE THREAD

**Issue by mioi** [terraform-providers/terraform-provider-google#1058] opened 2018-02-07 18:15 UTC
### Terraform Version
v0.11.3
google provider v1.2.0

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl

# var.subnetwork is the name of the subnetwork (i.e. "prod-us-west1")

resource "google_compute_address" "address" {
  name   = "z-test-instance-addr"
  region = "us-west1"
}

resource "google_compute_instance" "instance" {
  count = "1"

  boot_disk {
    initialize_params {
      image = "${var.image}"
    }
  }

  machine_type = "${var.machine_type}"

  name = "z-test-instance1"

  zone = "${var.zone}"

  network_interface {
    subnetwork = "${var.subnetwork}"

    access_config = {
      nat_ip = "${google_compute_address.address.address}"
    }
  }

  tags = "${var.tags}"

  lifecycle {
    ignore_changes = ["boot_disk.#", "boot_disk.0.initialize_params.#", "boot_disk.0.initialize_params.0.image", "boot_disk.0.disk_encryption_key_sha256", "boot_disk.0.auto_delete"]
  }

  can_ip_forward = "${var.can_ip_forward}"

  service_account {
    # email intentionally blank to use default service account
    scopes = ["${var.scopes}"]
  }
}
```

### Expected Behavior
Doing a `plan` shows:
```
  ~ google_compute_instance.instance
      network_interface.#:                                 "1" => "1"
      network_interface.0.access_config.#:                 "1" => "1"
      network_interface.0.access_config.0.assigned_nat_ip: "35.205.231.113" => <computed>
      network_interface.0.access_config.0.nat_ip:          "35.205.231.113" => "35.205.231.113"
      network_interface.0.address:                         "10.0.0.1" => <computed>
      network_interface.0.name:                            "nic0" => <computed>
      network_interface.0.subnetwork:                      "https://www.googleapis.com/compute/v1/projects/z-test-project/regions/us-west1/subnetworks/prod-us-west1" => "prod-us-west1"
      network_interface.0.subnetwork_project:              "z-test-project" => <computed>
```
Doing an `apply` successfully deletes and recreates the access config, but doing another `plan` shows the same plan output. Expected behavior is that a subsequent `plan` would show no changes.

### Actual Behavior
Doing another `plan` after an `apply` shows the same plan output.

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`

### Important Factoids
It isn't clear when this started happening. i noticed it after upgrading to Terraform v0.11.3 from v0.10.6, but was able to recreate this behavior going back to v0.10.6. The version of the google provider hasn't changed, although I tried doing a `plan` with the most recent version (1.5.0) and that didn't seem to help either.

### References
- https://github.com/terraform-providers/terraform-provider-google/issues/371
- https://github.com/terraform-providers/terraform-provider-google/pull/290

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment] 2018-06-01 15:05
We're seeing this issue as well at @travis-ci. We are seeing the `nat_ip` change every time we run `plan`, `apply`. Unfortunately this breaks all network connections, which is a serious issue for us.

We are running terraform v0.11.7, and google provider v1.13.0.

**Comment by ndmckinley** [comment] 2018-06-01 15:20
Gotcha.  Looks like the result of inconsistently using the `self_link` or `name` of the subnetwork there - I bet that's a quick fix, let me take a look.

**Comment by ndmckinley** [comment] 2018-06-01 15:31
Hm, odd, looks like we already have a `DiffSuppressFunc` that should have taken care of that ... I will need to investigate further.

**Comment by ndmckinley** [comment] 2018-06-01 20:42
Interesting, I can't reproduce locally.  Can you send me the debug logs?

**Comment by danawillow** [comment] 2018-06-12 20:50
This is the same issue as #988 and a few others that are caused by https://github.com/hashicorp/terraform/issues/18209. In the interest of not having too many open bugs with the same root cause, I'm going to go ahead and close this out. Thanks for the report!

**Closed by danawillow** 2018-06-12 20:50 UTC
Labels: bug
