### ISSUE TITLE
Finish "Mark GKE Workload Identity config as GA" PR.

### ISSUE THREAD

**Issue by ndmckinley** [terraform-providers/terraform-provider-google#6329] opened 2020-05-09 03:54 UTC
Finish https://github.com/GoogleCloudPlatform/magic-modules/pull/3453 - "Mark GKE Workload Identity config as GA"

**Comment by danawillow** [comment] 2020-05-11 16:53
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5916?

**Comment by ndmckinley** [comment] 2020-05-11 17:39
Fixing this will also close that one, but I think it's worth having an issue to say "this PR is abandoned but useful, finish it up" - your call.

**Closed** 2020-06-01 18:05 UTC
Labels: enhancement, size/XS
