### ISSUE TITLE
google_storage_bucket import requires compute engine API

### ISSUE THREAD

**Issue by saturnism** [terraform-providers/terraform-provider-google#3615] opened 2019-05-11 19:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.0.0
```

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "tf-gcs-store" {
  name = "${var.terraform_backend_bucket}"
  location = "US"
  project = "${google_project.infrastructure.project_id}"
  storage_class = "MULTI_REGIONAL"
  versioning = {
    enabled = true
  }
}
```

### Debug Output

```
$ terraform import google_storage_bucket.tf-gcs-store ...

google_storage_bucket.tf-gcs-store: Refreshing state... (ID: ...)

Error: google_storage_bucket.tf-gcs-store (import id: ...): 1 error(s) occurred:

* import google_storage_bucket.tf-gcs-store result: ...: google_storage_bucket.tf-gcs-store: googleapi: Error 403: Project 1007969183195 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

```

### Expected Behavior

Creating Google Cloud Storage resource didn't require Compute Engine API. Importing shouldn't require it either.

### Actual Behavior

Importing GCS bucket requires Compute Engine API enabled.

### Steps to Reproduce

```
$ terraform import google_storage_bucket.tf-gcs-store ...
```

### References

* #0000

**Comment by Chupaka** [comment] 2019-05-11 20:39
Please upgrade your provider plugin first: https://github.com/terraform-providers/terraform-provider-google/issues/3222

**Comment by emilymye** [comment] 2019-05-13 21:39
As mentioned, this seems to be a duplicate of an issue we've already fixed and should be fixed by upgrading. I'm going to close this issue out but please let us know if you think there is more or differences with your issue!

**Closed by emilymye** 2019-05-13 21:39 UTC
Labels: bug
