### ISSUE TITLE
Terraform fails creating an empty VPC SC bridge perimeter

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#4792] opened 2019-11-01 09:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.9
+ provider.google v2.14.0

### Affected Resource(s)

* google_access_context_manager_service_perimeter

### Terraform Configuration Files

```tf
resource "google_access_context_manager_service_perimeter" "bridge_example" {
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/bridge_example"
  title          = "bridge_example"
  perimeter_type = "PERIMETER_TYPE_BRIDGE"
  status {
  }
  lifecycle {
    ignore_changes = [ "status[0].resources" ]
  }
}
```

### Expected Behavior

It should create the bridge perimeter
It only works if there's at least 1 project mentioned in the resources array within the status block.
However, within GCP you can create a bridge without any projects in it, so I expect Terraform to be able to do this as well.

### Actual Behavior

The following error is printed by Terraform:
```
Error: Error creating ServicePerimeter: googleapi: Error 400: A Service Perimeter without dry_run enabled must have a valid 'status' set, but no 'status' was supplied

  on bridge_example.tf line 1, in resource "google_access_context_manager_service_perimeter" "bridge_example":
   1: resource "google_access_context_manager_service_perimeter" "bridge_example" {
```

### Steps to Reproduce

Run terraform apply against the example tf file provided above.

**Comment by rolandkool** [comment] 2019-11-01 09:41
Forgot to mention, creating a regular perimeter without any projects works fine. However, in that case the restricted_services and access_levels array will be populated with some values.

On a bridge perimeter these two options can't be configured.

**Comment by danawillow** [comment] 2019-11-04 17:35
Hi @rolandkool, when you get a chance can you please post the debug output (https://www.terraform.io/docs/internals/debugging.html) as per the issue template?

**Comment by rolandkool** [comment] 2019-12-06 15:00
@danawillow https://gist.github.com/rolandkool/f1f507d60e90ec78b837760396f4495e (sorry for the delay)

**Comment by danawillow** [comment] 2019-12-11 03:06
Thanks! Since I'm not super familiar with what service perimeter bridges do, what's the use case for leaving an empty status?

**Comment by rolandkool** [comment] 2019-12-11 11:55
On a bridge, you cannot set access levels or enable APIs, so those are empty by default. 
Because of a dependency issue between bridges and regular perimeters, it is impossible to manage project resources in perimeters: to add a project to a regular and bridge perimeter, first it needs to be added to the regular perimeter before it can be added to the bridge. For removing, it is the other way around. 

So we would like to just manage the bridge perimeters, but without any projects in it. Our current workaround is to do an import when the bridge contains at least 1 project.

Hope that clarifies it a bit.

**Comment by danawillow** [comment] 2019-12-17 23:37
https://github.com/terraform-providers/terraform-provider-google/issues/4509 is currently being worked on to allow adding a project to a perimeter separately from the perimeter resource. Would that obsolete this, or would this still be an issue if that separate resource is added?

**Comment by rolandkool** [comment] 2019-12-19 11:14
Yes that would definitely help. Would be great if that also solves the dependency issue.

**Comment by danawillow** [comment] 2019-12-19 21:03
Cool! I think there's a chance that we'll still need this once that's done, so I'll keep this open for the time being and check back again later.

**Comment by danawillow** [comment] 2020-01-27 23:40
Looking at this again. I was able to create a bridge with nothing in it by omitting the status field completely. Does that work for you, @rolandkool, or am I missing something?

**Comment by rolandkool** [comment] 2020-02-01 10:54
Yes, that should work for us. Which provider version will include the fix?

**Comment by danawillow** [comment] 2020-02-03 21:56
I believe it should be doable at whatever version of the provider the service perimeter resource first appears in- I didn't make any changes to the provider to get it working. Have you gotten a chance to try it?

To clarify, instead of:
```
resource "google_access_context_manager_service_perimeter" "bridge_example" {
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/bridge_example"
  title          = "bridge_example"
  perimeter_type = "PERIMETER_TYPE_BRIDGE"
  status {
  }
  lifecycle {
    ignore_changes = [ "status[0].resources" ]
  }
}
```
my config looks like:
```
resource "google_access_context_manager_service_perimeter" "bridge_example" {
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/bridge_example"
  title          = "bridge_example"
  perimeter_type = "PERIMETER_TYPE_BRIDGE"
}
```

**Comment by rtoma** [comment] 2020-03-28 15:13
Hi Dana, I can confirm removing the empty `status {... }` did the trick for us (reporter is team mate).

**Comment by danawillow** [comment] 2020-03-30 16:19
Great! Closing this out, then.

**Closed by danawillow** 2020-03-30 16:19 UTC
Labels: bug
