### ISSUE TITLE
Unable to switch address from an instance to another

### ISSUE THREAD

**Issue by migibert** [terraform-providers/terraform-provider-google#1183] opened 2018-03-12 16:09 UTC
Hi there,

I am facing some problems when switching google_compute_address resource from an instance to another. 

My use case is pretty simple: we have an instance with a public IP and we want to update it without downtime (but for simplicity, we don't want to set up a load balancer or something like that). So we created a second instance using terraform.

Now, our two instances are tested and correct, we want to switch the public IP to the second instance, so I remove the nat_ip property from first instance access_config block and add add the same nat_ip property to seconf instance access_config block.

Sadly it fails and terraform says that the address is already in use. I found https://github.com/hashicorp/terraform/issues/3841 that seem to be the same problem I am facing.

The only workaround I found from the moment is to switch IP manually in Google Cloud Console.

### Terraform Version
Terraform v0.11.3
+ provider.google v1.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance
- google_compute_address

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
First step:
```hcl
resource "google_compute_address" "address" {
  name = "address"
}

resource "google_compute_instance" "instance-1" {
  name = "instance-1"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
        nat_ip = "${google_compute_address.address.address}"
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}

resource "google_compute_instance" "instance-2" {
  name = "instance-2"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}
```
Second step:
```hcl
resource "google_compute_address" "address" {
  name = "address"
}

resource "google_compute_instance" "instance-1" {
  name = "instance-1"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {        
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}

resource "google_compute_instance" "instance-2" {
  name = "instance-2"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
        nat_ip = "${google_compute_address.address.address}"
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}
```
### Debug Output
Error: Error applying plan:

1 error(s) occurred:
* google_compute_instance.instance-2: 1 error(s) occurred:
* google_compute_instance.instance-2: External IP address: ***.***.***.*** is already in-use.

### Expected Behavior
Public address should have been affected from first instance (instance-1) to the second one (instance-2)

### Actual Behavior
Terraform failed 

### Steps to Reproduce
Use the first file I added before and
`terraform apply`

Use the second file I added before and
`terraform apply`

### References
https://github.com/hashicorp/terraform/issues/3841

**Comment by ndmckinley** [comment] 2018-03-13 19:13
That makes sense!  You should definitely be able to do that, but from terraform's perspective, of course, this is a cross-resource unstated dependency.  It doesn't know that it needs to wait for the `instance-1` change to finish before attempting the `instance-2` change.  Let me see what I can do.  :)

**Comment by ndmckinley** [comment] 2018-03-14 01:17
Hm, interesting - when I remove the `nat_ip` section from `instance-1`, it doesn't schedule `instance-1` for a change.  Wonder what's going on there!  I'm on it.

**Comment by ndmckinley** [comment] 2018-03-14 01:33
Ah!  It needs something else to change to.  Okay, here's my solution: you use `depends_on` to make sure that this change happens in the order you're hoping for, like so:

Step 1:
```
resource "google_compute_address" "address" {
  name = "address"
  region = "europe-west1"
}

resource "google_compute_instance" "instance-1" {
  name = "instance-1"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
        nat_ip = "${google_compute_address.address.address}"
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}

resource "google_compute_instance" "instance-2" {
  name = "instance-2"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}
```

Step 2:
```
resource "google_compute_address" "address" {
  name = "address"
  region = "europe-west1"
}

resource "google_compute_instance" "instance-1" {
  name = "instance-1"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
}

resource "google_compute_instance" "instance-2" {
  name = "instance-2"
  machine_type = "f1-micro"
  zone = "europe-west1-d"

  network_interface {
    network = "default"
    access_config {
        nat_ip = "${google_compute_address.address.address}"
    }
  }

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  depends_on = ["google_compute_instance.instance-1"]
}
```

And what will happen is that `instance-1` will drop `address`, where `instance-2` will wait for the `instance-1` change then pick up `address`.  If you want to swap them back in the future, you do roughly the same thing - move the `access_config` block up to `instance-1` and move the `depends_on` to be that `instance-1` depends on `instance-2`.  Note that you *do* have to remove the entire `access_config` block to trigger the change which will free up `address`.

Closing because no code change is necessary (or possible) to support this better.  Re-open if this doesn't help!

**Closed by ndmckinley** 2018-03-14 01:33 UTC

**Comment by ndmckinley** [comment] 2018-03-14 01:35
One more note to help validate the solution: this is the output you get from Terraform when you make those swaps:

```
Terraform will perform the following actions:

  ~ google_compute_instance.instance-1
      network_interface.0.access_config.#:        "0" => "1"
      network_interface.0.access_config.0.nat_ip: "" => "35.187.21.127"

  ~ google_compute_instance.instance-2
      network_interface.0.access_config.#:        "1" => "0"
```

**Comment by jeduden** [comment] 2020-03-19 15:13
This doesn't sound like a proper solution. Since the only reason for the dependency with instance-1 to exist is that it had the ip address in the past associated with it.

I think, a concept on address is missing. Something like: 'it can only have a single owner'. Terraform should figure out that the owner changed, and then use this property to ensure that this change can be applied without manually inserting the dependency.

Since the issue is quite old, is there now a better solution available ?

**Comment by ndmckinley** [comment] 2020-03-19 16:14
I agree that this solution feels incomplete.  The issue is in the core planner of Terraform, which we cannot control in our provider.  We have an open issue against Terraform core to enable us to build better solutions, but for now, this is what we've got, unfortunately.
