### ISSUE TITLE
Add `name_prefix` property to `google_sql_database_instance`

### ISSUE THREAD

**Issue by evandbrown** [terraform-providers/terraform-provider-google#389] opened 2017-09-05 22:11 UTC
`google_sql_database_instance` makes the `name` property optional to allow for dynamic name generation (thus avoiding restrictions on name reuse in the downstream API). It would be awesome to support a `name_prefix` property to allow control of the prefix. The AWS launch config resource does something similar: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#name_prefix

**Comment by danawillow** [comment] 2017-09-06 13:48
Closing as duplicate of #98, thanks for the report Evan!

**Closed by danawillow** 2017-09-06 13:48 UTC
