### ISSUE TITLE
resource google_compute_vpn_tunnel doesn't seem to work as intended anymore

### ISSUE THREAD

**Issue by nlopes** [terraform-providers/terraform-provider-google#2336] opened 2018-10-25 19:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.10
+ provider.google v1.19.1
+ provider.google-beta v1.19.0
+ provider.random v2.0.0
+ provider.template v1.0.0

### Affected Resource(s)

* google_compute_vpn_tunnel

### Terraform Configuration Files

```tf
resource "google_compute_vpn_tunnel" "tunnel" {
  name          = "tunnel-${count.index + 1}"
  count         = "${length(var.peer_ip)}"
  region        = "${var.region}"
  project       = "${var.project_id}"
  peer_ip       = "${element(var.peer_ip, count.index)}"
  shared_secret = "${element(var.psk, count.index)}"

  target_vpn_gateway = "${google_compute_vpn_gateway.gateway.self_link}"
  ike_version        = "${var.ike_version}"

  depends_on = [
    "google_compute_forwarding_rule.esp",
    "google_compute_forwarding_rule.udp500",
    "google_compute_forwarding_rule.udp4500",
  ]

  # If we have any BGP variables, then we'll need a router
  # Concatenating the resource list with an empty list prevents us from hitting
  # the terraform non-lazy conditional evaluation, which will otherwise error
  # whenever you don't have any routers.
  router = "${length(var.bgp_peer_ip) == 0 ? "" : element(concat(google_compute_router.router.*.self_link, list("")), count.index)}"

  # If we have any BGP variables, then we need no selector. This is a crazy hack
  # to send no local or remote traffic selector whenever we're trying to
  # configure BGP. It's real ugly and we should get rid of it as soon as
  # terraform supports conditional nulls, which is scheduled for v12.
  local_traffic_selector = ["${compact(split(" ", "${length(var.bgp_peer_ip) == 0 ? data.google_compute_subnetwork.subnetwork.ip_cidr_range : ""}"))}"]

  remote_traffic_selector = ["${compact(split(" ", "${length(var.bgp_peer_ip) == 0 ? var.peer_network : ""}"))}"]
}
```

### Debug Output
```
-/+ module.vpn.google_compute_vpn_tunnel.tunnel[0] (new resource required)
      id:                                 "tunnel-1" => <computed> (forces new resource)
      creation_timestamp:                 "2018-10-25T11:47:45.183-07:00" => <computed>
      detailed_status:                    "Allocating resources. VPN tunnel will start soon." => <computed>
      ike_version:                        "1" => "1"
      label_fingerprint:                  "42WmSpB8rSM=" => <computed>
      local_traffic_selector.#:           "1" => "0" (forces new resource)
      local_traffic_selector.1080289494:  "0.0.0.0/0" => "" (forces new resource)
      name:                               "tunnel-1" => "tunnel-1"
      peer_ip:                            "<correct peer ip, masked>" => "<correct peer ip, masked>"
      project:                            "project" => "project"
      region:                             "europe-west4" => "europe-west4"
      remote_traffic_selector.#:          "1" => "0" (forces new resource)
      remote_traffic_selector.1080289494: "0.0.0.0/0" => "" (forces new resource)
      router:                             "https://www.googleapis.com/compute/v1/projects/project/regions/europe-west4/routers/router-tunnel-1" => "https://www.googleapis.com/compute/v1/projects/project/regions/europe-west4/routers/router-tunnel-1"
      self_link:                          "https://www.googleapis.com/compute/v1/projects/project/regions/europe-west4/vpnTunnels/tunnel-1" => <computed>
      shared_secret:                      <sensitive> => <sensitive> (attribute changed)
      shared_secret_hash:                 "asfg" => <computed>
      target_vpn_gateway:                 "https://www.googleapis.com/compute/v1/projects/project/regions/europe-west4/targetVpnGateways/gw" => "https://www.googleapis.com/compute/v1/projects/project/regions/europe-west4/targetVpnGateways/gw"
```
### Expected Behavior

Nothing. We should see no change when we do an apply right after an apply.

### Actual Behavior

As seen in the output, the local_traffic_selector and remote_traffic_selector seem to be modified.
This is odd, as it should find absolutely no change.

We think it is due to a change in how the vpnTunnel api works. It seems that since a few days/hours ago, Google stopped accepting a `router` and a `local_traffic_selector` to be defined and so we worked around it. But then, when queried, it sends back the internal state, which is different from what we provide in the terraform config.

The following error, that we saw before implementing the "hack" you can read in the code above, is why we think this is the case:
```
* google_compute_vpn_tunnel.tunnel.0: Error creating VpnTunnel: googleapi: Error 400: Invalid value for field 'resource.localTrafficSelector[0]': '0.0.0.0/0'. Cannot set both local traffic selector and router fields., invalid
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We think it is due to a change in how the vpnTunnel api works. It seems that since a few days/hours ago, Google stopped accepting a `router` and a `local_traffic_selector` to be defined and so we worked around it. But then, when queried, it sends back the internal state, which is different from what we provide in the terraform config.

### References

**Comment by chrisst** [comment] 2018-10-27 00:30
@nlopes can you set the env variable TF=DEBUG and run your command to set up the vpn tunnel again and provide the output? This will show you what is actually being submitted to the google cloud api in the background. I suspect that your work around for the GCP error was to cause a condition in Terraform where one of your computed values isn't getting set the first time around. 

If I had to guess the dependency resolution might not be correctly happening for `${length(var.bgp_peer_ip) == 0 ? data.google_compute_subnetwork.subnetwork.ip_cidr_range : ""}` as you have embedded the dependency inside code.

**Comment by nlopes** [comment] 2018-11-07 13:59
Apologies for the tardiness on this reply @chrisst. You can find the run with TF=DEBUG at https://gist.github.com/nlopes/b76f75667bb4173599b516ed90e694ec
 I've removed the sensitive info but otherwise should give you all the data you need.

**Comment by lawrencejones** [comment] 2018-11-08 21:12
Hey @chrisst, I think the problem we have here is that the Google API is returning a local and remote traffic selector for our tunnel, even though we never send one.

You can see from our logs that when we create the VPN tunnel, we send the following:

```
---[ REQUEST ]---------------------------------------
POST /compute/beta/projects/<sensitive>/regions/europe-west4/vpnTunnels?alt=json HTTP/1.1
Host: www.googleapis.com
User-Agent: Terraform/0.11.7 (+https://www.terraform.io)
Content-Length: 394
Content-Type: application/json
Accept-Encoding: gzip

{
 "ikeVersion": 1,
 "name": "tunnel-tunnel-1",
 "peerIp": "<senstive>",
 "region": "projects/<sensitive>/global/regions/europe-west4",
 "router": "https://www.googleapis.com/compute/v1/projects/<sensitive>/regions/europe-west4/routers/tunnel-router-tunnel-1",
 "sharedSecret": "<sensitive>",
 "targetVpnGateway": "projects/<sensitive>/regions/europe-west4/targetVpnGateways/tunnel"
}
```

You'll notice that the local and remote traffic selector arrays are omitted. This is by design, as the API client specifies omitempty:

```
	// RemoteTrafficSelector: Remote traffic selectors to use when
	// establishing the VPN tunnel with peer VPN gateway. The value should
	// be a CIDR formatted string, for example: 192.168.0.0/16. The ranges
	// should be disjoint. Only IPv4 is supported.
	RemoteTrafficSelector []string `json:"remoteTrafficSelector,omitempty"`
```

> As Norberto mentioned, when we send a remote/local selector while we have a router configured, the Google API rejects our request with a 400. This behaviour changed during development and is what we suspect broke our code.

What we get back from the Google API then includes a local and remote traffic selector:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{
 "kind": "compute#vpnTunnel",
 "id": "1792332589781916132",
 "creationTimestamp": "2018-11-07T09:55:23.295-08:00",
 "name": "mytunnel-tunnel-1",
 "description": "",
 "region": "https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west4",
 "targetVpnGateway": "https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west4/targetVpnGateways/mytunnel",
 "router": "https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west4/routers/mytunnel-router-tunnel-1",
 "peerIp": "<address>",
 "sharedSecret": "*************",
 "sharedSecretHash": "",
 "status": "ESTABLISHED",
 "selfLink": "https://www.googleapis.com/compute/v1/projects/<project>/regions/europe-west4/vpnTunnels/mytunnel-tunnel-1",
 "ikeVersion": 1,
 "detailedStatus": "Tunnel is up and running.",
 "localTrafficSelector": [
  "0.0.0.0/0"
 ],
 "remoteTrafficSelector": [
  "0.0.0.0/0"
 ]
}
```

This then triggers the terraform resource to try recreating everything.

---

So we have two solutions to our problem here. We can either add a `DiffSuppressFunc` that ensures we ignore remote and local traffic selectors (provided they are default values of `0.0.0.0/0`) whenever a router is configured, or we can go back to Google and ask them to make their API reflect what they'll accept as a request.

I'm marginally in favour of asking the GCP team to change the API, as I think this behaviour is surprising and leads to problems (as demonstrated by this issue). We're happy to implement the former if that is otherwise impractical though!

**Comment by chrisst** [comment] 2018-11-12 22:49
The GCP changes to disallow `router` and `local_traffic_selector` make sense to be based on my reading of https://cloud.google.com/vpn/docs/concepts/choosing-networks-routing . It looks like by defining a router you are not going to be using "Policy based routing" which is the only type of VPN tunnel that will allow you to specify a `local_traffic_selector`. When using dynamic routing or a route based VPN both traffic selectors should be set to "0.0.0.0/0" and this is why we have set them both to optional/computed.

When I spin up a simplified `google_compute_vpn_tunnel` it sends the create request without sending the traffic selectors as expected, the responses comes back with the "0.0.0.0/0" and ends up with both traffic selectors in state but as computed values so they don't trigger a diff. 

I think the reason you are seeing the diff being triggered is because of the code that's trying to dynamically specify the traffic selectors based on the contents of other variables. After that line of code is resolved you end up with the equivalent of `remote_traffic_selector = []` which is different then what is in state and thus terraform is trying to fix it. If you don't wish to update the traffic selectors you should omit the property completely from your config or trying using separate templates for dynamic vs policy based VPNs.

**Comment by lawrencejones** [comment] 2018-12-10 11:02
Hey @chrisst, thanks with your help on this one- it does appear to be a subtlety with terraform default/empty values that caused this permadiff. Going to close the issue now as we have a module working fine that doesn't do any fancy stuff with interpolation.

Thanks again!

**Closed** 2018-12-10 16:57 UTC
Labels: bug
