### ISSUE TITLE
Cloud DNS: Support for Private DNS Zones

### ISSUE THREAD

**Issue by sakajunquality** [terraform-providers/terraform-provider-google#2325] opened 2018-10-24 03:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google recently announced that Cloud DNS Private DNS Zones:
https://cloud.google.com/blog/products/networking/introducing-private-dns-zones-resolve-to-keep-internal-networks-concealed

It would be extremely helpful if provider Google enables to create private DNS Zones.

### New or Affected Resource(s)

* google_dns_managed_zone

**Comment by pdecat** [comment] 2018-10-25 09:20
Same as #870 I guess.

**Comment by chrisst** [comment] 2018-10-25 16:33
Closing as duplicate of the older bug. Please feel free to subscribe to #870

**Closed by chrisst** 2018-10-25 16:33 UTC
Labels: beta-feature, enhancement
