### ISSUE TITLE
GKE NodePool  incorrectly infers cluster location from it's own location

### ISSUE THREAD

**Issue by redbaron** [terraform-providers/terraform-provider-google#4298] opened 2019-08-20 12:46 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Provider version 2.13.0

### Affected Resource(s)

* google_container_node_pool

### Expected Behavior

Cluster location is inferred or allowed to be specified explicitly

### Actual Behavior

Cluster location is inferred from nodepool, but they are not linked: cluster can be regional , while nodepool can be limited to a single zone.

### References

- Problematic code: https://github.com/terraform-providers/terraform-provider-google/blob/0cd8e8dfde9eb1029958dc8adb312e32a908d18a/google/resource_container_node_pool.go#L190-L197
- Can potentially be resolved with  https://github.com/terraform-providers/terraform-provider-google/issues/3992

* #0000

**Comment by rileykarson** [comment] 2019-08-20 19:58
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3992

**Closed by rileykarson** 2019-08-20 19:58 UTC
Labels: bug
