### ISSUE TITLE
Users added manually via console are remove when running terraform

### ISSUE THREAD

**Issue by rajdhandus** [terraform-providers/terraform-provider-google#2089] opened 2018-09-20 19:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.7
+ provider.google v1.18.0
+ provider.template v1.0.0

### Affected Resource(s)

* google_project_iam_policy

### Terraform Configuration Files

```tf

resource "google_service_account" "service-account-hal" {
  account_id   = "halyard-service-account"
  display_name = "halyard-service-account"
}

# Creating GCR service account

resource "google_service_account" "service-account-gcr" {
  account_id   = "gcr-service-account"
  display_name = "gcr-service-account"
}

# Creating GCS service account
resource "google_service_account" "service-account-gcs" {
  account_id   = "gcs-service-account"
  display_name = "gcs-service-account"
}

# SA Policy Binding
data "google_iam_policy" "sa-policy-binding" {
  binding {
    role = "roles/browser"

    members = [
      "serviceAccount:${google_service_account.service-account-gcs.account_id}@${var.project_name}.iam.gserviceaccount.com",
      "serviceAccount:${google_service_account.service-account-gcr.account_id}@${var.project_name}.iam.gserviceaccount.com",
    ]
  }

  binding {
    role = "roles/storage.objectViewer"

    members = [
      "serviceAccount:${google_service_account.service-account-gcs.account_id}@${var.project_name}.iam.gserviceaccount.com",
      "serviceAccount:${google_service_account.service-account-gcr.account_id}@${var.project_name}.iam.gserviceaccount.com",
    ]
  }

  binding {
    role = "roles/storage.admin"

    members = [
      "serviceAccount:${google_service_account.service-account-gcs.account_id}@${var.project_name}.iam.gserviceaccount.com",
      "serviceAccount:${google_service_account.service-account-gcr.account_id}@${var.project_name}.iam.gserviceaccount.com",
      "serviceAccount:${google_service_account.service-account-hal.account_id}@${var.project_name}.iam.gserviceaccount.com",
    ]
  }

  binding {
    role    = "roles/container.admin"
    members = ["serviceAccount:${google_service_account.service-account-hal.account_id}@${var.project_name}.iam.gserviceaccount.com"]
  }

  binding {
    role    = "roles/iam.serviceAccountKeyAdmin"
    members = ["serviceAccount:${google_service_account.service-account-hal.account_id}@${var.project_name}.iam.gserviceaccount.com"]
  }
}

# SA Policy
resource "google_project_iam_policy" "sa-policy" {
  project     = "${google_storage_bucket.halyard-bucket.project}"
  policy_data = "${data.google_iam_policy.sa-policy-binding.policy_data}"
}
```

### Expected Behavior

All User added via console should be present as they are not created using terraform

### Actual Behavior

Running terraform removed users if they are not added at a specific time sequence.

### Steps to Reproduce

1. `terraform apply`
User A added
2. `terraform destroy`
User B added
3. `terraform refresh`

User A doesn't stick
User B sticks

**Comment by paddycarver** [comment] 2018-09-20 20:02
As mentioned in [the docs](https://www.terraform.io/docs/providers/google/r/google_project_iam.html), `google_project_iam_policy` will overwrite your entire policy, and destroy will reset it to an empty policy. If this is not the behaviour you want, you want `google_project_iam_binding` or `google_project_iam_member`.

Closing this as working as intended, but if I've somehow misunderstood, please feel free to reply, and we can reopen and investigate.

**Closed by paddycarver** 2018-09-20 20:02 UTC
Labels: bug
