### ISSUE TITLE
dynamic block validation error triggering since 3.20 release

### ISSUE THREAD

**Issue by sleterrier** [terraform-providers/terraform-provider-google#6296] opened 2020-05-05 16:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
terraform -v
Terraform v0.12.24
+ provider.google v3.20.0
```

### Affected Resource(s)

* google_compute_firewall

### Terraform Configuration Files

```tf
terraform {
  required_version = "~> 0.12.7"

  required_providers {
    #google = "<= 3.19"
    google = ">= 3.20"
  }
}

provider "google" {}

variable "rules" {
  default     = {}
  type        = any
}

resource "google_compute_firewall" "rule" {
  for_each = var.rules

  description             = lookup(each.value, "description", null)
  destination_ranges      = lookup(each.value, "destination_ranges", null)
  direction               = upper(lookup(each.value, "direction", null))
  disabled                = lookup(each.value, "disabled", false)
  enable_logging          = lookup(each.value, "enable_logging", false)
  name                    = each.key
  network                 = "test"
  priority                = lookup(each.value, "priority", null)
  project                 = "project-id"
  source_ranges           = lookup(each.value, "source_ranges", null)
  source_service_accounts = lookup(each.value, "source_service_accounts", null)
  target_service_accounts = lookup(each.value, "target_service_accounts", null)
  source_tags             = lookup(each.value, "source_tags", null)
  target_tags             = lookup(each.value, "target_tags", null)

  dynamic "allow" {
    for_each = lookup(each.value, "allow", {})

    content {
      ports    = allow.value
      protocol = allow.key
    }
  }

  dynamic "deny" {
    for_each = lookup(each.value, "deny", {})

    content {
      ports    = deny.value
      protocol = deny.key
    }
  }
}
```

### Debug Output

[TF_LOG=DEBUG output](https://gist.github.com/sleterrier/9acac761fd7c0cde438876fe08c1fbac)

### Expected Behavior

The apply should just run without generating any changes.

### Actual Behavior

```
Error: "allow": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on main.tf line 17, in resource "google_compute_firewall" "rule":
  17: resource "google_compute_firewall" "rule" {

Error: "deny": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on main.tf line 17, in resource "google_compute_firewall" "rule":
  17: resource "google_compute_firewall" "rule" {
```

### Steps to Reproduce

1. `terraform init` + `terraform apply` : it fails.
2. Comment `google = ">= 3.20"` requirement and uncomment `google = "<= 3.19" `
3. `terraform init` + `terraform apply`: it works.

### Reference
- Sounds like #6295 describes the same issue.

**Comment by edwardmedia** [comment] 2020-05-06 16:26
@sleterrier can you post your rules with the default values?

**Comment by hwchiu** [comment] 2020-05-06 18:55
I met the same issue and can reproduce it with the following setting.
main.tf
```
terraform {
  required_providers {
    google = "3.20"
  }
}

resource "google_compute_firewall" "custom" {
  for_each                = var.custom_rules
  name                    = each.key
  description             = each.value.description
  direction               = each.value.direction
  network                 = var.network
  source_ranges           = each.value.direction == "INGRESS" ? each.value.ranges : null
  destination_ranges      = each.value.direction == "EGRESS" ? each.value.ranges : null
  source_tags             = each.value.use_service_accounts || each.value.direction == "EGRESS" ? null : each.value.sources
  source_service_accounts = each.value.use_service_accounts && each.value.direction == "INGRESS" ? each.value.sources : null
  target_tags             = each.value.use_service_accounts ? null : each.value.targets
  target_service_accounts = each.value.use_service_accounts ? each.value.targets : null
  disabled                = lookup(each.value.extra_attributes, "disabled", false)
  priority                = lookup(each.value.extra_attributes, "priority", 1000)
  enable_logging          = lookup(each.value.extra_attributes, "enable_logging", null)

  dynamic "allow" {
    for_each = [for rule in each.value.rules : rule if each.value.action == "allow"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }

  dynamic "deny" {
    for_each = [for rule in each.value.rules : rule if each.value.action == "deny"]
    iterator = rule
    content {
      protocol = rule.value.protocol
      ports    = rule.value.ports
    }
  }
}

```

```bash=
╰─$ terraform init    

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "google" (hashicorp/google) 3.20.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╰─$ terraform validate

Error: "deny": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on main.tf line 7, in resource "google_compute_firewall" "custom":
   7: resource "google_compute_firewall" "custom" {



Error: "allow": only one of `allow,deny` can be specified, but `allow,deny` were specified.

  on main.tf line 7, in resource "google_compute_firewall" "custom":
   7: resource "google_compute_firewall" "custom" {
```

Pass the validation once we roll back to 3.19.

**Comment by edwardmedia** [comment] 2020-05-07 00:13
Yes I can repro this issue as well.

**Comment by onetwopunch** [comment] 2020-05-07 17:57
@ndmckinley I can take this issue if you don't mind re-assigning?

**Comment by morgante** [comment] 2020-05-07 17:59
I assume this will likely be fixed by #6295.

**Comment by ndmckinley** [comment] 2020-05-07 18:00
Yes, feel free to validate that you're still having trouble at head, and if so, we'd be happy to have your help.  :)

**Comment by onetwopunch** [comment] 2020-05-07 19:23
@morgante is correct https://github.com/terraform-providers/terraform-provider-google/pull/6286 seems to fix it.

**Comment by danawillow** [comment] 2020-05-07 19:41
Closing since we've validated the fix and it'll be in the next release.

**Closed by danawillow** 2020-05-07 19:41 UTC
Labels: bug
