### ISSUE TITLE
google_bigquery_dataset_iam_member

### ISSUE THREAD

**Issue by hden** [terraform-providers/terraform-provider-google#5520] opened 2020-01-28 01:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Provides a non-authoritative ways to manage access to a dataset. If https://github.com/terraform-providers/terraform-provider-google/issues/3929 cannot be solved at SDK level, at least we can create or own solutions.

```tf
# variables.tf
variable "owners" {
  type    = set(string)
  default = []
}

# main.tf
resource "google_bigquery_dataset" "temp" {
  dataset_id = "temp"
  project    = data.google_project.project.project_id
}

resource "google_project_iam_member" "owner" {
  for_each = var.owners
  dataset  = google_bigquery_dataset.temp.dataset_id
  role     = "roles/owner"
  member   = each.value
}
```

### New or Affected Resource(s)

* google_bigquery_dataset_iam_member

### Potential Terraform Configuration

```tf
resource "google_bigquery_dataset_iam_member" "editor" {
  dataset = "your-bigquery-dataset"
  member  = "user:jane@example.com"
  role    = "roles/editor"
}
```

### References

* https://github.com/terraform-providers/terraform-provider-google/issues/3929
* https://github.com/terraform-providers/terraform-provider-google/issues/2051

**Comment by danawillow** [comment] 2020-02-03 17:39
Bigquery APIs don't implement IAM the same way as the resources where you see the *_iam_member resources so we wouldn't be able to do exactly that, but there is already a FR open for breaking the `access` block into its own resource, so marking this as a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/2686.

**Comment by danawillow** [comment] 2020-04-10 21:49
Reopening to try to get resources in the traditional iam formats as well

**Closed** 2020-06-08 23:19 UTC
Labels: enhancement, priority/2, size/M

**Comment by preston-hf** [comment] 2020-06-16 19:47
How does this differ from the `bigquery_dataset_access` resource?

**Comment by slevenick** [comment] 2020-06-16 20:42
Only in the structure to make it act similarly to other `*_iam` resources. `bigquery_dataset_access` would be the preferred way to handle this as it allows assigning access to `view`s

**Comment by danawillow** [comment] 2020-06-16 20:53
@slevenick worth adding something in the docs that explains when to use which resource type?

**Comment by simonvanderveldt** [comment] 2020-07-08 09:55
What does the change introduced in #6553 do exactly? I haven't been able to find any documentation about IAM supporting BigQuery, AFAIK access can only be managed on the dataset itself, see https://cloud.google.com/bigquery/docs/dataset-access-controls

**Comment by slevenick** [comment] 2020-07-10 15:37
@simonvanderveldt the change fits the dataset access controls to the standard terraform IAM binding/member/policy format. Access is still managed on the dataset itself, but this makes it a little more familiar
