### ISSUE TITLE
CloudSQL and private_ip - Update an existing instance

### ISSUE THREAD

**Issue by emas80** [terraform-providers/terraform-provider-google#2902] opened 2019-01-21 12:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.11.11
Google Provider and Google Provider Beta 1.20.0

### Affected Resource(s)

*  google_sql_database_instance

### Terraform Configuration Files

The example code for CloudSQL database found at https://www.terraform.io/docs/providers/google/r/sql_database_instance.html
First, I create a CloudSQL database without the "private_ip" section, and then I run a second time terraform apply with the "private_ip" section.
Terraform would like to add the VPC peering and it would also like to add the private_ip network. Everything seems correct.

First terraform configuration file
```tf
resource "google_sql_database_instance" "master" {
  name = "master-instance"
  database_version = "POSTGRES_9_6"
  region = "us-central1"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
    ip_configuration {
        ipv4_enabled = "true"
    }
  }
}
```
Adding the private ip

```tf
resource "google_compute_network" "private_network" {
    name       = "private-network"
}

resource "google_compute_global_address" "private_ip_address" {
    name          = "private-ip-address"
    purpose       = "VPC_PEERING"
    address_type = "INTERNAL"
    prefix_length = 16
    network       = "${google_compute_network.private_network.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
    provider      = "google-beta"
    network       = "${google_compute_network.private_network.self_link}"
    service       = "servicenetworking.googleapis.com"
    reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.name}"]
}

resource "google_sql_database_instance" "master" {
  depends_on = ["google_service_networking_connection.private_vpc_connection"]

  name = "master-instance-1"
  database_version = "POSTGRES_9_6"
  region = "us-central1"

  settings {
    # Second-generation instance tiers are based on the machine
    # type. See argument reference below.
    tier = "db-f1-micro"
    ip_configuration {
        ipv4_enabled = "true"
        private_network = "${google_compute_network.private_network.self_link}"
    }
  }
}
``

### Expected Behavior

I am expecting to see the private ip attached to my CloudSQL instance.

### Actual Behavior

Nothing. No errors, VPC peering resource has been created, but the private ip checkbox in the UI is not checked.

### Steps to Reproduce

Create a CloudSQL database without the private ip, and then try to adding the private ip.

### References
* https://github.com/terraform-providers/terraform-provider-google/issues/2897 (closed)

**Comment by larsha** [comment] 2019-01-21 18:36
I'm seeing exactly the same issue. I ran the apply with TRACE logging and I did see that the PUT request didn't had any `private_network` section in it so nothing will be changed. Definitely some bug here.

**Comment by mackoftrack** [comment] 2019-01-24 17:57
After having enabled Private IP via the console, and updates to the google_sql_database_instance.db_instance via terraform seems to fail with the following error:

`googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation`

**Comment by larsha** [comment] 2019-01-24 21:16
@mackoftrack It might not be related, regarding to Google documentation of Cloud SQL: "After you configure a Cloud SQL instance to use private IP, you cannot remove private IP capability from that instance.". So depending on what updates you're doing you might hitting that?

**Comment by mackoftrack** [comment] 2019-01-24 21:42
@larsha Could be. I'm really not sure, but terraform is broken for me after having enabled private IP. Not sure how to get around this.

**Comment by larsha** [comment] 2019-01-24 21:44
@mackoftrack Have you tried running `terraform refresh` to reconcile the state with the real infrastructure?

**Comment by mackoftrack** [comment] 2019-01-24 21:48
@larsha Yes I have. It did not resolve the issue.

**Comment by larsha** [comment] 2019-01-24 21:50
@mackoftrack Then I agree, it sounds like you're hitting this issue.

**Comment by paulvalla** [comment] 2019-01-29 01:19
To create a private cloud sql instance, you need to use the google beta provider in the declaration of the `google_sql_database_instance` resource.  

`provider      = "google-beta"`

Once you've done that, delete this resource from your state and re-import it using:

```
# https://www.terraform.io/docs/commands/state/rm.html 
terraform state rm google_sql_database_instance.master
terraform import google_sql_database_instance.master projects/{{project}}/instances/{{name}}
```

**Comment by mackoftrack** [comment] 2019-01-29 17:31
I just tried what you suggested, but I get the same error after trying to apply a plan:

> Error, failed to update instance myinstance: googleapi: Error 400: This operation isn"t valid for this instance., invalidOperation

**Comment by rileykarson** [comment] 2019-01-29 18:39
Hey @mackoftrack! Can you include debug logs of a run where you try and make an existing public instance private and get that error? We're getting an error from the API, and intuitively it should work, although there's a chance we've missed a nuance somewhere.

**Comment by mackoftrack** [comment] 2019-01-29 20:01
https://gist.github.com/mackoftrack/7f3893e4eda4f3ee4e60cba95850fc16

**Comment by mackoftrack** [comment] 2019-01-29 20:40
```
resource "google_sql_database_instance" "db_instance" {
  provider = "google-beta"
  name = "${var.db_instance_name}"
  region = "${var.region}"
  settings {
    tier = "${var.db_tier}"
    disk_size = "${var.db_disk_size}"
    ip_configuration {
      ipv4_enabled = "true"
      authorized_networks = [
        "${data.null_data_source.ip_auth.*.outputs}"
      ]
      private_network = "${var.db_private_network}"
    }
    database_flags {
      name = "default_time_zone"
      value = "-08:00"
    }
    database_flags {
      name = "sql_mode"
      value = "STRICT_TRANS_TABLES"
    }
    backup_configuration {
      enabled = "${var.db_enable_backups}"
      start_time = "${var.db_backup_time}"
    }
  }
  database_version = "${var.db_mysql_version}"
}

data "null_data_source" "ip_auth" {
  count = "${length(var.db_ip_auth)}"

  inputs = {
    name  = "${element(split(",",var.db_ip_auth[count.index]),0)}"
    value = "${element(split(",",var.db_ip_auth[count.index]),1)}"
  }
}
```

**Comment by rileykarson** [comment] 2019-01-29 20:49
Thanks! And can you confirm that `var.db_private_network` has a value set that isn't `""`? We would expect the current request being sent to be sent if that value was empty but present.

**Comment by mackoftrack** [comment] 2019-01-29 21:38
Yes it is set to the `self_link` of the `google_compute_network`

**Comment by rileykarson** [comment] 2019-01-30 19:03
Huh, I was able to reproduce it locally; ends up I had a development version of the provider installed and it was fixed there.

So, this is present in `1.20.0` and below, and will be fixed in `2.0.0` as it's fixed at HEAD. I can't spot 100% what the fix was because our branch history from `1.19.0` -> `1.20.0` -> `2.0.0` (HEAD today) is pretty funky, but I suspect it was this: https://github.com/terraform-providers/terraform-provider-google/pull/2509.

Additionally, I filed https://github.com/terraform-providers/terraform-provider-google/issues/2964 for some unhelpful behaviour on Terraform's part when going private -> public that I encountered.

**Closed by rileykarson** 2019-01-30 19:03 UTC
Labels: bug

**Comment by mackoftrack** [comment] 2019-01-30 19:39
Thanks @rileykarson

**Comment by mackoftrack** [comment] 2019-01-31 00:11
@rileykarson any chance for a `1.20.1` hotfix or do we have to wait until the next release?

**Comment by rileykarson** [comment] 2019-01-31 00:31
Unfortunately we're almost definitely going to have to wait out `2.0.0` on this one :(
