### ISSUE TITLE
google_compute_network_endpoint_group serverless support

### ISSUE THREAD

**Issue by preston-hf** [terraform-providers/terraform-provider-google#6750] opened 2020-07-07 15:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

google_compute_network_endpoint_group should support adding Cloud Run, Cloud Functions, and App Engine services to the NEG.

### New or Affected Resource(s)

* google_compute_network_endpoint_group

### Potential Terraform Configuration

```tf
resource "google_compute_network_endpoint_group" "neg_cloud_run" {
  name         = "my-lb-neg"
  network_endpoint_type = "SERVERLESS"
  region         = "us-central1"
  cloud_run {
    service = "myservicename"
    tag = "revension-0010" # Optional
    url_mask = ".example.com/"
  }
}

resource "google_compute_network_endpoint_group" "neg_gae" {
  name         = "my-lb-neg"
  network_endpoint_type = "SERVERLESS"
  region         = "us-central1"
  app_engine {
    service = "myservicename"
    version = "202007071054" # Optional, default to latest
    url_mask = "-dot-appname.appspot.com/"
  }
}

resource "google_compute_network_endpoint_group" "neg_gcf" {
  name         = "my-lb-neg"
  network_endpoint_type = "SERVERLESS"
  region         = "us-central1"
  cloud_function {
    service = "myservicename"
    version = "202007071054" # Optional, default to latest
    url_mask = "/"
  }
}
```

### References
[API Docs](https://cloud.google.com/compute/docs/reference/rest/beta/networkEndpointGroups/insert#request-body)
[Overview](https://cloud.google.com/load-balancing/docs/negs/serverless-neg-concepts)
[Walkthrough](https://cloud.google.com/load-balancing/docs/negs/setting-up-serverless-negs)

**Comment by danawillow** [comment] 2020-07-07 16:26
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/6749

**Closed by danawillow** 2020-07-07 16:26 UTC
Labels: enhancement

**Comment by preston-hf** [comment] 2020-07-07 16:57
Beat me by 5 minutes! Might make sense to copy the examples over, I put a little more time into them :)

**Comment by Sytten** [comment] 2020-07-07 17:51
Done @preston-hf. I still think it makes more sense to create a new resource since they created a new one for the external URL (`google_compute_global_network_endpoint_group`).

**Comment by danawillow** [comment] 2020-07-07 19:17
We'll probably end up just adding it into the existing resource since that lines up with the API (which has separate endpoints for global and regional neg, but not for serverless vs not)
