### ISSUE TITLE
ignored attached_disk causes empty diff, but still a plan

### ISSUE THREAD

**Issue by mberhault** [terraform-providers/terraform-provider-google#3724] opened 2019-05-25 07:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.0
+ provider.google v2.7.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
resource "google_compute_instance" "nodes" {
  count        = var.size
  name         = format("%s-node-%04d", var.region, count.index)
  zone         = data.google_compute_zones.available.names[count.index % length(data.google_compute_zones.available.names)]
  project      = var.project
  machine_type = var.machine_type

  # Tags: the "cockroachdb-node" tag is used to whitelist all instances in the firewall rules.
  tags                    = [var.project, var.region, "cockroachdb-node"]
  metadata_startup_script = "echo -n \"${file("trusted_ssh_user_ca.pub")}\" | sudo tee /etc/ssh/trusted_ssh_user_ca.pub; /home/cockroach/make_disks.sh"

  scheduling {
    on_host_maintenance = "MIGRATE"
  }

  # Boot disk with CockroachDB base image.
  boot_disk {
    initialize_params {
      image = local.image_link
    }
  }

  network_interface {
    subnetwork = local.subnetwork
    access_config {
      // Ephemeral external IP.
    }
  }

  service_account {
    scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }

  # Workaround for attached_disk conflicting with the separate resource.
  # https://github.com/terraform-providers/terraform-provider-google/issues/2098
  lifecycle {
    ignore_changes = [attached_disk]
  }
}

# Persistent disks are managed separately from the instance. This allows instance modification
# while preserving the attached disk.
resource "google_compute_disk" "node_volumes" {
  count = var.size
  name  = format("%s-volume-%04d", var.region, count.index)
  zone  = data.google_compute_zones.available.names[count.index % length(data.google_compute_zones.available.names)]
  type  = "pd-ssd"
  size  = var.disk_size
}

# Attached disk links a persistent disk with its instance.
resource "google_compute_attached_disk" "volume_attachment" {
  count    = var.size
  disk     = google_compute_disk.node_volumes[count.index].self_link
  instance = google_compute_instance.nodes[count.index].self_link
}
```

### Debug Output

[debug output](https://gist.github.com/mberhault/9ae289d02b8986d6cd80a419bced12c6)

### Expected Behavior

Expected an empty plan (such as what happens when changing the lifecycle rule to `ignore_changes = all`:
```
No changes. Infrastructure is up-to-date.
```

Removing the `ignore_changes` field entirely produces the expected diff (due to the attached disks being managed by an attachment instead of within the google_compute_instance):
```
<the previous 8 instances show the same thing>
  # module.gcp_us-west1.google_compute_instance.nodes[2] will be updated in-place
  ~ resource "google_compute_instance" "nodes" {
        can_ip_forward          = false
        cpu_platform            = "Intel Broadwell"
        deletion_protection     = false
        guest_accelerator       = []
        id                      = "us-west1-node-0002"
        instance_id             = "8245561779933686984"
        label_fingerprint       = "42WmSpB8rSM="
        labels                  = {}
        machine_type            = "n1-standard-2"
        metadata                = {}
        metadata_fingerprint    = "y-D-N-Dn4SQ="
        metadata_startup_script = "echo -n \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9nVYP55cK6uty8fLXZGRGIr83q7/s4lNyJSEG7RucYqMli60mggLoSXx3tGNLKsnaQlYM1rDX1YlXRdcdKbZX0xaJzrjoddtpzKp52Lyx8SKEMrv/nNyP/DfEja+ILGVN8+5NWGNMDNZ28enWNDv5eY6XcACdT4oVxN7S1ot/Z11KiZo0kxFjdFgeeyHPBQziN2Bdtuv6Ve0tGuf+frkKvjKB7QevZ3Ykz/uonvscsNRduSkHuHL1XWxvlTU+pzZ5oUBXcPaMpHK4bJiMJj/+4odofkbuk/5o+A5E1lZK/nDQXO0vZEriGSzfq/TRkEeZrcfSXTdOBvaH7DCDcSDX8iibk1GFK4MOObOCnEpP+OIjcekNXm6Y+yzMPc8cUt5iLD4gyY0DEzStGNy5QkOxeuPGwdOO9BDoe7NC1P7iuzFMmDZYJ4WnHCt7oiQgj+QT5rrBibO7423I8YnWP/v8IasANpVQiCg4k67LF4TAb2SjHikmTUC0IaNAyXQnp/zBOZJX9IsQX2l/aktdgJn2vsDVL6gaBwFzu9a9mVVrIHOxJ0Ho9sY1LLgYHRP5D+6NrliOarUJrMufZz5n+8zePgWDb8xqAvxrhgaxhGaAD1I5DMQnLKglJ0QdYu1k4G7rC0vcN7sxvXXPuUDXrwoRcaOdoR6PNCgl0PQ6JjM6ZQ==\n\" | sudo tee /etc/ssh/trusted_ssh_user_ca.pub; /home/cockroach/make_disks.sh"
        name                    = "us-west1-node-0002"
        project                 = "cockroach-brave-beaver"
        self_link               = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/instances/us-west1-node-0002"
        tags                    = [
            "cockroach-brave-beaver",
            "cockroachdb-node",
            "us-west1",
        ]
        tags_fingerprint        = "eK3qmZl9bCc="
        zone                    = "us-west1-c"

      - attached_disk {
          - device_name = "persistent-disk-1" -> null
          - mode        = "READ_WRITE" -> null
          - source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/disks/us-west1-volume-0002" -> null
        }

        boot_disk {
            auto_delete = true
            device_name = "persistent-disk-0"
            source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/disks/us-west1-node-0002"

            initialize_params {
                image = "https://www.googleapis.com/compute/v1/projects/cockroach-staging-images/global/images/cockroachdb-ubuntu-1804-2019-04-09-150532"
                size  = 10
                type  = "pd-standard"
            }
        }

        network_interface {
            name               = "nic0"
            network            = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/global/networks/default"
            network_ip         = "10.138.0.3"
            subnetwork         = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/regions/us-west1/subnetworks/default"
            subnetwork_project = "cockroach-brave-beaver"

            access_config {
                nat_ip       = "34.83.117.250"
                network_tier = "PREMIUM"
            }
        }

        scheduling {
            automatic_restart   = true
            on_host_maintenance = "MIGRATE"
            preemptible         = false
        }

        service_account {
            email  = "1023664838061-compute@developer.gserviceaccount.com"
            scopes = [
                "https://www.googleapis.com/auth/cloud-platform",
            ]
        }

        timeouts {}
    }

Plan: 0 to add, 9 to change, 0 to destroy.
```

### Actual Behavior

Terraform wants to update the instances, but shows no diff:
```
<the previous 8 instances show the same thing>

  # module.gcp_us-west1.google_compute_instance.nodes[2] will be updated in-place
  ~ resource "google_compute_instance" "nodes" {
        can_ip_forward          = false
        cpu_platform            = "Intel Broadwell"
        deletion_protection     = false
        guest_accelerator       = []
        id                      = "us-west1-node-0002"
        instance_id             = "8245561779933686984"
        label_fingerprint       = "42WmSpB8rSM="
        labels                  = {}
        machine_type            = "n1-standard-2"
        metadata                = {}
        metadata_fingerprint    = "y-D-N-Dn4SQ="
        metadata_startup_script = "echo -n \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9nVYP55cK6uty8fLXZGRGIr83q7/s4lNyJSEG7RucYqMli60mggLoSXx3tGNLKsnaQlYM1rDX1YlXRdcdKbZX0xaJzrjoddtpzKp52Lyx8SKEMrv/nNyP/DfEja+ILGVN8+5NWGNMDNZ28enWNDv5eY6XcACdT4oVxN7S1ot/Z11KiZo0kxFjdFgeeyHPBQziN2Bdtuv6Ve0tGuf+frkKvjKB7QevZ3Ykz/uonvscsNRduSkHuHL1XWxvlTU+pzZ5oUBXcPaMpHK4bJiMJj/+4odofkbuk/5o+A5E1lZK/nDQXO0vZEriGSzfq/TRkEeZrcfSXTdOBvaH7DCDcSDX8iibk1GFK4MOObOCnEpP+OIjcekNXm6Y+yzMPc8cUt5iLD4gyY0DEzStGNy5QkOxeuPGwdOO9BDoe7NC1P7iuzFMmDZYJ4WnHCt7oiQgj+QT5rrBibO7423I8YnWP/v8IasANpVQiCg4k67LF4TAb2SjHikmTUC0IaNAyXQnp/zBOZJX9IsQX2l/aktdgJn2vsDVL6gaBwFzu9a9mVVrIHOxJ0Ho9sY1LLgYHRP5D+6NrliOarUJrMufZz5n+8zePgWDb8xqAvxrhgaxhGaAD1I5DMQnLKglJ0QdYu1k4G7rC0vcN7sxvXXPuUDXrwoRcaOdoR6PNCgl0PQ6JjM6ZQ==\n\" | sudo tee /etc/ssh/trusted_ssh_user_ca.pub; /home/cockroach/make_disks.sh"
        name                    = "us-west1-node-0002"
        project                 = "cockroach-brave-beaver"
        self_link               = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/instances/us-west1-node-0002"
        tags                    = [
            "cockroach-brave-beaver",
            "cockroachdb-node",
            "us-west1",
        ]
        tags_fingerprint        = "eK3qmZl9bCc="
        zone                    = "us-west1-c"

        attached_disk {
            device_name = "persistent-disk-1"
            mode        = "READ_WRITE"
            source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/disks/us-west1-volume-0002"
        }

        boot_disk {
            auto_delete = true
            device_name = "persistent-disk-0"
            source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/us-west1-c/disks/us-west1-node-0002"

            initialize_params {
                image = "https://www.googleapis.com/compute/v1/projects/cockroach-staging-images/global/images/cockroachdb-ubuntu-1804-2019-04-09-150532"
                size  = 10
                type  = "pd-standard"
            }
        }

        network_interface {
            name               = "nic0"
            network            = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/global/networks/default"
            network_ip         = "10.138.0.3"
            subnetwork         = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/regions/us-west1/subnetworks/default"
            subnetwork_project = "cockroach-brave-beaver"

            access_config {
                nat_ip       = "34.83.117.250"
                network_tier = "PREMIUM"
            }
        }

        scheduling {
            automatic_restart   = true
            on_host_maintenance = "MIGRATE"
            preemptible         = false
        }

        service_account {
            email  = "1023664838061-compute@developer.gserviceaccount.com"
            scopes = [
                "https://www.googleapis.com/auth/cloud-platform",
            ]
        }

        timeouts {}
    }

Plan: 0 to add, 9 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create a VM with attached disk on terraform 0.11, with `ignore_changes = ["attached_disk"]`
1. Upgrade terraform to 0.12, upgrade provider, update config, etc...
1. `terraform plan` or `terraform apply`.

I have not attempted a reproduction. I do not know if this is due to the 0.11 to 0.12 upgrade.

**Comment by mberhault** [comment] 2019-05-25 08:26
Quick update: I applied the plan on just one instance (to minimize VM recreations).
```
$ terraform apply --target="module.gcp_europe-west4.google_compute_instance.nodes[2]"

module.gcp_base.data.google_project.images_project: Refreshing state...
module.gcp_base.google_project.gcp_project: Refreshing state... [id=cockroach-brave-beaver]
module.gcp_base.google_project_service.project: Refreshing state... [id=cockroach-brave-beaver/compute.googleapis.com]
module.gcp_base.google_project_service.dns_service: Refreshing state... [id=cockroach-brave-beaver/dns.googleapis.com]
module.gcp_base.google_project_iam_member.images_project_iam: Refreshing state... [id=858487433075/roles/compute.imageUser/serviceAccount:1023664838061@cloudservices.gserviceaccount.com]
module.gcp_base.google_compute_http_health_check.health_check: Refreshing state... [id=cockroach-http-health-check]
module.gcp_base.google_dns_managed_zone.cluster_zone: Refreshing state... [id=brave-beaver]
module.gcp_europe-west4.data.google_compute_zones.available: Refreshing state...
module.gcp_europe-west4.google_compute_instance.nodes[2]: Refreshing state... [id=europe-west4-node-0002]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.gcp_europe-west4.google_compute_instance.nodes[2] will be updated in-place
  ~ resource "google_compute_instance" "nodes" {
        can_ip_forward          = false
        cpu_platform            = "Intel Skylake"
        deletion_protection     = false
        guest_accelerator       = []
        id                      = "europe-west4-node-0002"
        instance_id             = "4362623280893144308"
        label_fingerprint       = "42WmSpB8rSM="
        labels                  = {}
        machine_type            = "n1-standard-2"
        metadata                = {}
        metadata_fingerprint    = "y-D-N-Dn4SQ="
        metadata_startup_script = "echo -n \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9nVYP55cK6uty8fLXZGRGIr83q7/s4lNyJSEG7RucYqMli60mggLoSXx3tGNLKsnaQlYM1rDX1YlXRdcdKbZX0xaJzrjoddtpzKp52Lyx8SKEMrv/nNyP/DfEja+ILGVN8+5NWGNMDNZ28enWNDv5eY6XcACdT4oVxN7S1ot/Z11KiZo0kxFjdFgeeyHPBQziN2Bdtuv6Ve0tGuf+frkKvjKB7QevZ3Ykz/uonvscsNRduSkHuHL1XWxvlTU+pzZ5oUBXcPaMpHK4bJiMJj/+4odofkbuk/5o+A5E1lZK/nDQXO0vZEriGSzfq/TRkEeZrcfSXTdOBvaH7DCDcSDX8iibk1GFK4MOObOCnEpP+OIjcekNXm6Y+yzMPc8cUt5iLD4gyY0DEzStGNy5QkOxeuPGwdOO9BDoe7NC1P7iuzFMmDZYJ4WnHCt7oiQgj+QT5rrBibO7423I8YnWP/v8IasANpVQiCg4k67LF4TAb2SjHikmTUC0IaNAyXQnp/zBOZJX9IsQX2l/aktdgJn2vsDVL6gaBwFzu9a9mVVrIHOxJ0Ho9sY1LLgYHRP5D+6NrliOarUJrMufZz5n+8zePgWDb8xqAvxrhgaxhGaAD1I5DMQnLKglJ0QdYu1k4G7rC0vcN7sxvXXPuUDXrwoRcaOdoR6PNCgl0PQ6JjM6ZQ==\n\" | sudo tee /etc/ssh/trusted_ssh_user_ca.pub; /home/cockroach/make_disks.sh"
        name                    = "europe-west4-node-0002"
        project                 = "cockroach-brave-beaver"
        self_link               = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/europe-west4-c/instances/europe-west4-node-0002"
        tags                    = [
            "cockroach-brave-beaver",
            "cockroachdb-node",
            "europe-west4",
        ]
        tags_fingerprint        = "4D2o_xWH9Vs="
        zone                    = "europe-west4-c"

        attached_disk {
            device_name = "persistent-disk-1"
            mode        = "READ_WRITE"
            source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/europe-west4-c/disks/europe-west4-volume-0002"
        }

        boot_disk {
            auto_delete = true
            device_name = "persistent-disk-0"
            source      = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/zones/europe-west4-c/disks/europe-west4-node-0002"

            initialize_params {
                image = "https://www.googleapis.com/compute/v1/projects/cockroach-staging-images/global/images/cockroachdb-ubuntu-1804-2019-04-09-150532"
                size  = 10
                type  = "pd-standard"
            }
        }

        network_interface {
            name               = "nic0"
            network            = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/global/networks/default"
            network_ip         = "10.164.0.4"
            subnetwork         = "https://www.googleapis.com/compute/v1/projects/cockroach-brave-beaver/regions/europe-west4/subnetworks/default"
            subnetwork_project = "cockroach-brave-beaver"

            access_config {
                nat_ip       = "34.90.100.196"
                network_tier = "PREMIUM"
            }
        }

        scheduling {
            automatic_restart   = true
            on_host_maintenance = "MIGRATE"
            preemptible         = false
        }

        service_account {
            email  = "1023664838061-compute@developer.gserviceaccount.com"
            scopes = [
                "https://www.googleapis.com/auth/cloud-platform",
            ]
        }

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.gcp_europe-west4.google_compute_instance.nodes[2]: Modifying... [id=europe-west4-node-0002]
module.gcp_europe-west4.google_compute_instance.nodes[2]: Modifications complete after 5s [id=europe-west4-node-0002]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

So this updated the instance in place without doing much of anything.
Re-running the selective apply showed no diff.

**Comment by Chupaka** [comment] 2019-05-26 07:50
Looks like the problem is with "ignore_changes". I have the same "update with no changes" plan on GCS buckets with manually added lifecycle rules.

**Comment by Chupaka** [comment] 2019-05-28 13:39
And the request is pretty fun:
```
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: 2019/05/28 16:32:36 [DEBUG] Google API Request Details:
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: ---[ REQUEST ]---------------------------------------
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: PATCH /storage/v1/b/bucketname?alt=json&prettyPrint=false HTTP/1.1
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: Host: www.googleapis.com
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: User-Agent: google-api-go-client/0.5 Terraform/0.12.0 (+https://www.terraform.io) terraform-provider-google/2.7.0
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: Content-Length: 3
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: Content-Type: application/json
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: Accept-Encoding: gzip
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: 
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: {}
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: 
2019-05-28T16:32:36.325+0300 [DEBUG] plugin.terraform-provider-google_v2.7.0_x4: -----------------------------------------------------
```

**Comment by rileykarson** [comment] 2019-05-29 18:16
I can't reproduce this. Are either of you able to share a minimal config where this occurs?

**Comment by mberhault** [comment] 2019-05-29 18:36
I'll give it a shot. The previous config where this happened was applied (with no further diffs showing up), but I have more similar ones. I'll try to find a minimal reproduction.
The major change on our part was terraform 0.11.14 -> 0.12.0 and google provider 1.17 -> 2.7.0. Of course, there were many config changes as part of the terraform upgrade, but no diff was otherwise generated.

**Comment by rileykarson** [comment] 2019-05-29 19:20
Thanks! I'll leave this labelled with `waiting-response` until we can find a repro case.

**Comment by rileykarson** [comment] 2019-06-24 19:31
@mberhault did you happen to find a repro case? I'm going to mark this as stale in the meantime if not, since I don't think there's anything we can do without one.

**Comment by mberhault** [comment] 2019-06-24 19:50
Sorry, my initial attempts didn't bear fruit and I didn't dig further.

**Comment by rileykarson** [comment] 2019-06-25 16:52
No problem! Since there's no action we can really take here, I'm going to close this out. If you encounter the issue again, see if you can capture logs and please file again!

**Closed by rileykarson** 2019-06-25 16:52 UTC
Labels: bug
