### ISSUE TITLE
google_compute_attached_disk detach disk after 2nd terraform apply

### ISSUE THREAD

**Issue by DeWaRs** [terraform-providers/terraform-provider-google#2123] opened 2018-09-27 08:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.7
+ provider.google v1.18.0
+ provider.random v2.0.0

### Affected Resource(s)

google_compute_attached_disk
google_compute_disk

### Terraform Configuration Files

```tf
resource "random_id" "ipStatic" {
    keepers = {
        #Generate a new id each time we switch to a new instance_name
        instance_name = "${var.instance_name}"
    }
    byte_length = 8
}

resource "google_compute_address" "staticIp" {
    name = "${var.instance_name}-${random_id.ipStatic.hex}"
    region = "${var.region}"
}


resource "google_compute_instance" "default" {
    name = "${random_id.ipStatic.keepers.instance_name}"
    machine_type = "${var.machine_type}"
    zone = "${var.availability_zone}"

    boot_disk {
        initialize_params {
            image = "${var.image_id}"
            size = "${var.boot_size}"
        }
    }
    
    network_interface {
        network = "${var.sub_network_name}"

        access_config {
            // Static IP
            nat_ip = "${google_compute_address.staticIp.address}"
        }
    }
   
   metadata {
    ssh-keys = "gcpcloud:${file(var.ssh_key)}"
   }

}

resource "google_compute_disk" "vg_sys" {
  count = "${var.sys_size == 0 ? 0 : 1}"
  name  = "${var.instance_name}-vgsys"
  type  = "pd-ssd"
  zone  = "${var.availability_zone}"
  size  = "${var.sys_size}"
}

resource "google_compute_attached_disk" "attach_vg_sys" {
  count = "${var.sys_size == 0 ? 0 : 1}"
  disk     = "${google_compute_disk.vg_sys.self_link}"
  instance = "${google_compute_instance.default.self_link}"
}

resource "google_compute_disk" "vg_data" {
  count = "${var.data_size == 0 ? 0 : 1}"
  name  = "${var.instance_name}-vgdata"
  type  = "pd-ssd"
  zone  = "${var.availability_zone}"
  size  = "${var.data_size}"
}

resource "google_compute_attached_disk" "attach_vg_data" {
  depends_on = ["google_compute_attached_disk.attach_vg_sys"]
  count = "${var.data_size == 0 ? 0 : 1}"
  disk     = "${google_compute_disk.vg_data.self_link}"
  instance = "${google_compute_instance.default.self_link}"
}

```

### Expected Behavior

Terraform should return "No change needed"

### Actual Behavior

Terraform wants to detach the disk: 

```
~/splunk/terraform_gcp  ᐅ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_id.ipStatic: Refreshing state... (ID: rvoVttbKivU)
google_compute_disk.vg_sys: Refreshing state... (ID: spl-ds-vgsys)
google_compute_disk.vg_data: Refreshing state... (ID: spl-ds-vgdata)
google_compute_address.staticIp: Refreshing state... (ID: psd-devops-coe/europe-west1/spl-ds-aefa15b6d6ca8af5)
google_compute_instance.default: Refreshing state... (ID: spl-ds)
google_compute_attached_disk.attach_vg_sys: Refreshing state... (ID: spl-ds:spl-ds-vgsys)
google_compute_attached_disk.attach_vg_data: Refreshing state... (ID: spl-ds:spl-ds-vgdata)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.deployment_server.google_compute_instance.default
      attached_disk.#:        "2" => "0"
      attached_disk.0.source: "https://www.googleapis.com/compute/v1/projects/psd-devops-coe/zones/europe-west1-b/disks/spl-ds-vgsys" => ""
      attached_disk.1.source: "https://www.googleapis.com/compute/v1/projects/psd-devops-coe/zones/europe-west1-b/disks/spl-ds-vgdata" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

- Run `terraform apply`
- Instance + disks are fully deployed
- Run `terrform apply`
- Terraform return `Plan: 0 to add, 1 to change, 0 to destroy.`

**Comment by paddycarver** [comment] 2018-09-27 17:47
This appears to be a duplicate of #2098. I'm going to close it out, but if you feel this isn't a duplicate, feel free to reply and we can discuss.

**Closed by paddycarver** 2018-09-27 17:47 UTC
Labels: bug
