### ISSUE TITLE
Add filters support for PubSub subscription

### ISSUE THREAD

**Issue by SaugataDutta** [terraform-providers/terraform-provider-google#6834] opened 2020-07-22 18:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Can we please add support for this..This is a beta feature but still very useful.
https://cloud.google.com/pubsub/docs/filtering

Create a subscription with a filter, the subscription only delivers the messages that match the filter. Pub/Sub automatically acknowledges the messages that don't match the filter. You can filter messages by their attributes.

When you receive messages from a subscription with a filter, you don't incur egress fees for the messages that Pub/Sub automatically acknowledges. For a limited time after the beta launch stage starts, you don't incur message delivery fees for these messages. All other fees apply.
### New or Affected Resource(s)

* google_pubsub_subscription

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by slevenick** [comment] 2020-07-27 17:29
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/6727

**Closed by slevenick** 2020-07-27 17:29 UTC
Labels: enhancement
