### ISSUE TITLE
Project metadata ssh-keys does not propagate to instances

### ISSUE THREAD

**Issue by bluemalkin** [terraform-providers/terraform-provider-google#1812] opened 2018-07-24 23:46 UTC
### Terraform Version
```
Terraform v0.11.7
+ provider.google v1.16.1
```

### Affected Resource(s)
- google_compute_project_metadata
- google_compute_project_metadata_item

### Terraform Configuration Files
```
resource "google_compute_project_metadata_item" "username" {
  key   = "ssh-keys"
  value = "username:ssh-rsa <xxxxxxxx> <comment>"
}
```

### Expected Behavior
The ssh key gets added to the project metadata which applies to all instances and I expect to be able to ssh into the instance (without using gcloud shell).

### Actual Behavior
Metadata gets filled in as expected.
However I get permission denied (public key) when attempting to connect via SSH command.

If I add the metadata to the instance directly I am able to ssh:
```
resource "google_compute_instance" "test" {

  metadata {
   "ssh-keys" = "username:ssh-rsa <xxxxxxxx> <comment>"
  }
}
```
I have not ticked "Block project-wide SSH keys".

Unsure whether this is a GCP or Terraform provider issue.

**Comment by ndmckinley** [comment] 2018-07-25 20:51
We can rule out a Terraform provider issue if you send us the debug logs - if you're not able to do that, I'll try to get a repro ASAP.  It seems likely that it's a GCP issue because the metadata is getting filled in as expected.

**Comment by ndmckinley** [comment] 2018-07-26 22:44
I've gotten around to trying this, and I'm successful on 1.16.2 with the ssh key on the project metadata instead of the instance directly.  Can you please confirm this is still happening for you?  Are you applying the metadata item to the same project as the instance?

**Comment by bluemalkin** [comment] 2018-07-27 00:41
@ndmckinley are you able to SSH into the host directly ?

I can confirm that the metadata gets added project wise but for some reason I get permission denied using SSH. 
Confirm the instance is in the same project too.

**Comment by ndmckinley** [comment] 2018-07-27 19:37
Yep, I'm able to SSH into the host directly when the project-wide metadata is set and can't once I remove it.

**Comment by ndmckinley** [comment] 2018-07-27 19:38
I understand if you're not able to post your config, but without that, I'm stymied as to how I'm going to help debug further.

**Comment by paddycarver** [comment] 2018-09-30 03:12
We've gone a few months without new information on this, so in the absence of a reproduction, I'm going to close it out. If someone has more details on this happening and can help us get to a reproduction, I'm happy to reopen the issue.

**Closed by paddycarver** 2018-09-30 03:12 UTC
Labels: bug
