### ISSUE TITLE
google_service_networking_connection.private_vpc_connection: Error waiting for Create Service Networking Connection: Error code 9, message: Cannot modify allocated ranges in CreateConnection. Please use UpdateConnection

### ISSUE THREAD

**Issue by SubhakarKotta** [terraform-providers/terraform-provider-google#3819] opened 2019-06-08 11:52 UTC
Terraform v0.11.14
+ provider.google v2.8.0
+ provider.google-beta v2.8.0
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2
+ provider.random v2.1.2

After running the below command it works
gcloud beta services vpc-peerings update     --service=servicenetworking.googleapis.com     --ranges=ww-spinnaker-cluster-a6c21a69-private-ip-addr     --network=default --project=mystical-being-195215     --force
But i want in automated way in terrafrom as manual execution is not possible

I am trying to create private vpc connection in default network this error was thrown attached the debug log
```hcl
provider "random" {}

resource "random_id" "id" {
  byte_length = 4
  prefix      = "${var.database_name_prefix}-"
}
data "google_compute_network" "default-network" {
  provider      = "google-beta"
  name    = "default"
}

resource "google_compute_global_address" "private_ip_address" {
  provider      = "google-beta"
  name          = "${random_id.id.hex}-private-ip-addr"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = "${data.google_compute_network.default-network.self_link}"
}

resource "google_service_networking_connection" "private_vpc_connection" {
  provider                = "google-beta"
  network                 = "${data.google_compute_network.default-network.self_link}"
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = ["${google_compute_global_address.private_ip_address.id}"]
}

resource "google_sql_database_instance" "master" {
  provider         = "google-beta"
  name             = "${random_id.id.hex}"
  region           = "${var.region}"
  database_version = "${var.database_version}"

  depends_on = [
    "google_service_networking_connection.private_vpc_connection",
  ]

  settings {
    availability_type = "${var.availability_type}"
    tier              = "${var.sql_instance_size}"
    disk_type         = "${var.sql_disk_type}"
    disk_size         = "${var.sql_disk_size}"
    disk_autoresize   = true

    ip_configuration {
      require_ssl     = "${var.sql_require_ssl}"
      ipv4_enabled    = true
      private_network = "${data.google_compute_network.default-network.self_link}"
    }

    location_preference {
      zone = "${var.region}-${var.sql_master_zone}"
    }

    backup_configuration {
      enabled    = true
      start_time = "00:00"
    }
  }
}

resource "google_sql_database" "initdatabase" {
  name     = "${google_sql_database_instance.master.name}"
  instance = "${google_sql_database_instance.master.name}"
}

resource "google_sql_user" "user" {
  depends_on = [
    "google_sql_database_instance.master",
  ]

  instance = "${google_sql_database_instance.master.name}"
  name     = "${var.sql_user}"
  password = "${var.sql_pass}"
}
```

[tmp.log](https://github.com/terraform-providers/terraform-provider-google/files/3268482/tmp.log)

**Comment by emilymye** [comment] 2019-06-13 21:13
This is sadly currently an issue with the service networking connection - closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3819. I would check that thread for updates.

**Closed by emilymye** 2019-06-13 21:13 UTC

**Comment by SubhakarKotta** [comment] 2019-06-14 03:36
@emilymye  closing as duplicate of #3819. This thread was #3819 what is the original issue

**Comment by hoos** [comment] 2019-07-09 17:47
Is there any update on this issue?
