### ISSUE TITLE
Panic on apply for google_container_cluster that has tags

### ISSUE THREAD

**Issue by majelbstoat** [terraform-providers/terraform-provider-google#1777] opened 2018-07-16 15:07 UTC
google_container_cluster does not have a `labels` field.

`Error: module.cluster.google_container_cluster.primary: : invalid or unknown key: labels`

Given this, I manually added labels to the cluster from the GKE dashboard. Having done this, `terraform apply` panics:

`panic: interface conversion: interface {} is map[string]interface {}, not map[string]string`

### Terraform Version
Terraform 0.11.7
Provider 1.16.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Panic Output
https://gist.github.com/majelbstoat/988bf6cece0a37ec4eb77d7c7e83636d

### Expected Behavior
google_container_cluster should either 
a) ignore that labels because it doesn't know what to do with them, or
b) (ideally) support labels.

Either way, it should not panic.

### Steps to Reproduce
1. import a `google_container_cluster` that has at least 1 label defined from the GKE dashboard. (succeeds, imported with n labels)
2. `terraform plan` (succeeds - n labels to change to 0)
3. `terraform apply` panic.

### Important Factoids
This is all on GKE.
This does not crash on provider `1.14.0`. I only spotted the difference when CI started using a more recent version of the provider.

**Comment by majelbstoat** [comment] 2018-07-16 15:20
(Temporary workaround is to just delete the labels from the dashboard, and then everything works again.)

**Comment by paddycarver** [comment] 2018-07-16 15:34
I believe this is a duplicate of #1767. Feel free to correct me if I'm wrong, though! Sorry for the problems, a fix has been merged and will roll out shortly.

**Closed by paddycarver** 2018-07-16 15:34 UTC
Labels: bug, crash

**Comment by paddycarver** [comment] 2018-07-16 16:48
I'm not an expert on GKE or labels, so I may be entirely wrong about this, but I believe that's what #1663 was meant to address.
