### ISSUE TITLE
Cloud Functions -> pubsub triggered function update leads to unexpected build error reffering to http triggered type

### ISSUE THREAD

**Issue by lwsanty** [terraform-providers/terraform-provider-google#6662] opened 2020-06-23 15:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
* terraform 0.12.20
* provider.google: version = "~> 3.26"
* runtime go 1.13

### Affected Resource(s)

* google_cloudfunctions_function

### Terraform Configuration Files

```tf
resource "google_cloudfunctions_function" "slack_notify" {
  name        = "${var.namespace}-slack-notify"
  entry_point = "SlackNotifyFunc"
  event_trigger {
    event_type = "google.pubsub.topic.publish"
    resource   = "projects/${var.google_project}/topics/${google_pubsub_topic.slack_notifications_topic.name}"
    failure_policy {
      retry = false
    }
  }
  runtime               = var.runtime
  service_account_email = var.google_service_account
  region                = var.google_region_global
  source_archive_bucket = var.sources_bucket
  source_archive_object = google_storage_bucket_object.slack_notify_archive.name
  vpc_connector         = var.vpc_connector
  labels = {
    environment = var.namespace
  }

  environment_variables = {
    PROMETHEUS_JOB       = "slack-notify"
    PROMETHEUS_LABELS    = <<EOF
{
	"entrypoint": "SlackNotify",
	"environment": "${var.namespace}",
	"func_id": "slack-notify",
}
EOF
    SLACK_TOKEN          = var.slack_auth_token
  }
}

```

### Expected Behavior

Function should have been updated successfully.

### Actual Behavior

```hcl
Error: Error waiting for Updating CloudFunctions Function: Error code 3, message: Build failed: # serverless_function_app/main
src/serverless_function_app/main/main.go:24:38: cannot use metadata.SlackNotifyFunc (type func(context.Context, *pubsub.Message) error) as type func(http.ResponseWriter, *http.Request) in argument to funcframework.RegisterHTTPFunction; Error ID: 6191efcd
  on main.tf line 595, in resource "google_cloudfunctions_function" "slack_notify":
 595: resource "google_cloudfunctions_function" "slack_notify" {
```

### Steps to Reproduce

1. `terraform apply`

### References

This behavior started constantly being reproduced starting from yesterday. We suspect that something could probably change from GCP side that actually builds the code and wrongly typematches the Cloud Function.

Having in mind this piece in code `funcframework.RegisterHTTPFunction` I googled and found this PR https://github.com/GoogleCloudPlatform/functions-framework-go/pull/29 to be merged around the day ago and cause the error we experience.

**Comment by lwsanty** [comment] 2020-06-23 16:35
https://issuetracker.google.com/issues/159608139

**Comment by venkykuberan** [comment] 2020-06-23 21:54
@lwsanty I am able to deploy the cf without any errors. Infact tried the same config in https://issuetracker.google.com/issues/159608139. Can you please share your debug logs to understand more ..

sample config
```
resource "google_storage_bucket" "bucket" {
  name = "source-code-prometheus-fetch-v"
}

data "archive_file" "backup" {
  type        = "zip"
  source_file = "./gofunc.go"
  output_path = "./gofunc.zip"
}

resource "google_storage_bucket_object" "archive" {
  name                = "function_go.zip"
  bucket              = google_storage_bucket.bucket.name
  source              = data.archive_file.backup.output_path
  storage_class       = "STANDARD"
  content_disposition = "attachment"
  content_encoding    = "gzip"
  content_type        = "application/zip"
}

resource "google_cloudfunctions_function" "function" {
  name        = "fetch-prometheus-data"
  description = "My function"
  runtime     = "go111"

  available_memory_mb   = 128
  source_archive_bucket = google_storage_bucket.bucket.name
  source_archive_object = google_storage_bucket_object.archive.name
  # trigger_http          = true
  entry_point           = "EventGCS"
  timeout = 60
  event_trigger {
    event_type = "google.storage.object.finalize"
    resource   = google_storage_bucket.bucket.name
  }
}
```

**Comment by michaelneale** [comment] 2020-06-24 00:33
I can reproduce this even without terraform: https://github.com/michaelneale/func-deploy-failure

**Comment by mavaa** [comment] 2020-06-24 10:56
Just ran into this myself. It seems to be happening when there's a vendor folder present AND runtime is go113. If I set runtime to go111 OR publish something at as go113 without any dependencies/vendor folder it works perfectly.

**Comment by venkykuberan** [comment] 2020-06-24 19:23
@lwsanty its an upstream issue not related to terraform/provider, i am closing it here as its been tracked elsewhere. Please reopen if you feel otherwise.

**Closed by venkykuberan** 2020-06-24 19:23 UTC
Labels: bug
