### ISSUE TITLE
Feature request: New resource type, BigQuery routines

### ISSUE THREAD

**Issue by jamiekt** [terraform-providers/terraform-provider-google#4619] opened 2019-10-04 19:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

On 2019-10-03 the BigQuery service gained the ability to use stored procedures and UDFs, see the release notes here: https://cloud.google.com/bigquery/docs/release-notes#October_03_2019

The routines resource on the BigQuery API supports management of stored procedures and UDFs: https://cloud.google.com/bigquery/docs/reference/rest/v2/routines

This issue is to request support in the Terraform GCP Provider for creating, modifying & destroying BigQuery stored procedures and UDFs.

### New or Affected Resource(s)

* google_bigquery_routine

### Potential Terraform Configuration

```tf
resource "google_bigquery_routine" "sproc" {
  project_id  = "myproject"
  dataset_id = "${google_bigquery_dataset.default.dataset_id}"
  routine_id     = "mysproc"
  routine_type = "PROCEDURE"
  language = "SQL"
  definition_body = "CREATE PROCEDURE ${google_bigquery_dataset.default.dataset_id}.mysproc () BEGIN SET x = x + delta; END"
  # see full list of attributes [here](https://cloud.google.com/bigquery/docs/reference/rest/v2/routines)
}
```

```tf
resource "google_bigquery_routine" "udf" {
  project_id  = "myproject"
  dataset_id = "${google_bigquery_dataset.default.dataset_id}"
  routine_id     = "myudf"
  routine_type = "SCALAR_FUNCTION"
  language = "SQL"
  definition_body = "${data.template.function_body}"
  # see full list of attributes [here](https://cloud.google.com/bigquery/docs/reference/rest/v2/routines)
}
```

**Comment by kurtmaile** [comment] 2019-10-21 19:56
Yes yes please!

**Comment by kurtmaile** [comment] 2019-10-21 19:58
Saved queries as well, not sure why they havent been added since they have been around for ages - or maybe I missed this?  

The new scripts, stored procs, UDFs are really important to add, albeit beta, wont belong before GA I imagine.  Many thanks!

**Comment by TheOriginalAlex** [comment] 2019-11-18 18:41
I'd like to pick this up if no one's already working on it.  :)

**Comment by paddycarver** [comment] 2019-12-06 23:32
This appears to be a duplicate of #4493.

**Closed by paddycarver** 2019-12-06 23:32 UTC
Labels: enhancement, size/M
