### ISSUE TITLE
Crash when trying to update google_container_cluster resources_label on 3.10.0 beta

### ISSUE THREAD

**Issue by bmoyet** [terraform-providers/terraform-provider-google#5769] opened 2020-02-26 15:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.21
+ provider.google v3.10.0
+ provider.google-beta v3.10.0
+ provider.helm v0.10.1
+ provider.kubernetes v1.8.1
+ provider.null v2.1.2

### Affected Resource(s)

google_container_cluster

### Terraform Configuration Files

variables.tf
```tf
variable "cluster" {
  type = object({
    name                     = string
    location                 = string
    daily_maintenance_window = string
    resource_labels          = map(string)
    network                  = string
    subnetwork               = string
    logging_service          = string
    monitoring_service       = string
    master_ipv4              = string
    pods_ipv4                = string
    services_ipv4            = string
    monitoring_dataset       = string
  })
}
```

prod.tfvars
```tf
cluster = {
  name                     = "..."
  location                 = "..."
  daily_maintenance_window = "02:00"
  resource_labels = {
    env = "env"
    label1     = "lb1"
    label2     = "lb2
    label3     = "lb3"
  }
  network            = "..."
  subnetwork         = "..."
  logging_service    = "..."
  monitoring_service = "..."
  master_ipv4        = "..."
  pods_ipv4          = "..."
  services_ipv4      = "..."
  monitoring_dataset = "..."
}
```

```tf
resource "google_container_cluster" "business_cluster" {
...
  resource_labels    = var.cluster.resource_labels
...
}
```
with var.cluster.resource_labels having new/modified values.

### Panic Output

https://gist.github.com/bmoyet/9ae3fdac30ecaf5b58a9480d87f0d765

### Expected Behavior

The resources_labels on my gc cluster should be updated. With the 3.9.0 provider, the labelFingerprint wasn't set (https://github.com/terraform-providers/terraform-provider-google/issues/5608), so I couldn't update them. So I tested the 3.10.0 beta which should have fixed the issue, but encountered the given crash.

### Steps to Reproduce

1. `terraform plan/apply`

### References

* #5608

**Comment by juzna** [comment] 2020-02-26 15:53
Same problem in #5768.

**Comment by emilymye** [comment] 2020-02-27 01:51
Closing as duplicate of #5768 - please track there

**Closed by emilymye** 2020-02-27 01:51 UTC
Labels: bug
