### ISSUE TITLE
aborting long running terraform apply operation removes all state

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#982] opened 2018-01-19 10:28 UTC
I was doing a terraform apply with two `google_container_cluster`s and 4 `google_container_node_pool`s and when it took over 10 minutes (because some preemptible machines weren't available, so it kept waiting for them for ever) my terraform state file went empty, so basically terraform has no idea of the clusters/nodepools anymore even if they are running. Not sure if this is a terraform issue or google provider issue? I've seen this happen with `google_container_clusters` only multiple times.

I'm using terraform workspaces (non-remote).

**Comment by ndmckinley** [comment] 2018-01-19 21:05
Can you provide logs?  My suspicion is that this is intended behavior - we very intentionally don't mark the resource as created until the initial creation request returns that the creation operation has started - but it could be that there's something we can do to make this a better experience.

If I'm right, would it be accurate to title this issue "Long-running terraform apply does not store state"?  I think it would be a very serious bug if you had other state that got wiped out by aborting the apply.

**Comment by matti** [comment] 2018-01-20 11:40
This happens after the `google_container_cluster` and `google_container_node_pool` has been created. To repro this (100% success rate in my ~6 tests):

1. Apply and wait for cluster and node pool to be created
2. Change the number of nodes in `google_container_node_pool` or add a new node_pool
3. Run apply again and let it run for couple of minutes and then ^C that forcefully.
4. The state file is empty

**Comment by matti** [comment] 2018-01-22 18:40
still happening, always fixed by copying state from the backup.

**Comment by ndmckinley** [comment] 2018-01-22 18:51
Interesting, yep, that's definitely not what I would expect to happen.  Let me do some investigation and report back.

**Comment by ndmckinley** [comment] 2018-01-22 18:56
I'm seeing similarities to https://github.com/hashicorp/terraform/issues/17066 - are you using -state-out?

**Comment by matti** [comment] 2018-01-23 11:43
nope, just `terraform apply`

**Comment by ndmckinley** [comment] 2018-01-23 19:04
Thanks.  This is definitely a terraform issue, and not a google provider issue, so I'm going to boot this upstream - I've referenced this issue there and I'll tag with "upstream".  You can follow along there, or I'll report back to this bug if any significant progress is made.

**Comment by matti** [comment] 2018-01-25 19:34
@ndmckinley Sorry where have you referenced this issue? It's not linked back here

**Comment by ndmckinley** [comment] 2018-01-25 19:39
A few posts up- https://github.com/hashicorp/terraform/issues/17066. That seems that it will wipe out your existing statefile if you aren't using `state-out`.

**Comment by apparentlymart** [comment] 2018-02-05 23:05
Hi @matti! Sorry for this strange issue, and thanks for reporting it.

After some investigation today I concluded that although you are seeing similar _symptoms_ as hashicorp/terraform#17066 the root causes seem to be separate. (You can see some details of how I got to that conclusion in a comment on that issue, if you're interested.)

So with that said, if you'd be willing it'd be great if you could open a new top-level issue in [the Terraform Core repository](https://github.com/hashicorp/terraform) and provide the things requested in the issue template there -- particularly the trace log -- which will hopefully allow us to understand better what's going on in your case.

Thanks, and sorry again for this weird behavior.

**Comment by paddycarver** [comment] 2018-02-08 18:54
Seeing as this has moved (I believe) to hashicorp/terraform#17282, I'm going to close this issue out. If it appears this bug is specific to the Google provider, we can reopen this issue to track it down.

**Closed by paddycarver** 2018-02-08 18:54 UTC
Labels: upstream, upstream-terraform

**Comment by matti** [comment] 2018-02-26 09:14
(fixed in  hashicorp/terraform#17282)
