### ISSUE TITLE
Managed Zone "New Resource Required" fails if Zone has any DNS records

### ISSUE THREAD

**Issue by benjamin-maynard** [terraform-providers/terraform-provider-google#1616] opened 2018-06-07 20:08 UTC
This was discovered as part of #1615 

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.22.0
+ provider.digitalocean v0.1.3
+ provider.dme v0.1.0
+ provider.github v1.1.0
+ provider.google v1.13.0
+ provider.powerdns v0.1.0
```

### Affected Resource(s)
- google_dns_managed_zone
- google_dns_record_set

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
**INITIAL:**
```
resource "google_dns_managed_zone" "benmaynard-co-uk" {
  name        = "benmaynard-co-uk"
  dns_name    = "benmaynard.co.uk."
  description = "bnemaynard.co.uk DNS Zone - Managed by Terraform"
}

resource "google_dns_record_set" "benmaynard-co-uk-A" {
  name = "${google_dns_managed_zone.benmaynard-co-uk.dns_name}"
  type = "A"
  ttl  = "${var.benmaynard_co_uk_ttl}"

  managed_zone = "${google_dns_managed_zone.benmaynard-co-uk.name}"

  rrdatas = ["${digitalocean_floating_ip.nigel-web-maynard-io.ip_address}"]
}

```
**CHANGED:** (Note description change, correcting spelling error)
```
resource "google_dns_managed_zone" "benmaynard-co-uk" {
  name        = "benmaynard-co-uk"
  dns_name    = "benmaynard.co.uk."
  description = "benmaynard.co.uk DNS Zone - Managed by Terraform"
}
resource "google_dns_record_set" "benmaynard-co-uk-A" {
  name = "${google_dns_managed_zone.benmaynard-co-uk.dns_name}"
  type = "A"
  ttl  = "${var.benmaynard_co_uk_ttl}"

  managed_zone = "${google_dns_managed_zone.benmaynard-co-uk.name}"

  rrdatas = ["${digitalocean_floating_ip.nigel-web-maynard-io.ip_address}"]
}

```
### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* google_dns_managed_zone.benmaynard-co-uk (destroy): 1 error(s) occurred:

* google_dns_managed_zone.benmaynard-co-uk: Error deleting DNS ManagedZone: googleapi: Error 400: The resource named 'benmaynard-co-uk' cannot be deleted because it is not empty, containerNotEmpty

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior
If a new resource is required for a Managed Zone, Terraform should delete all of the records defined in the zone, recreate the Managed Zone, and then re-add the DNS records.

### Actual Behavior
Terraform fails with above debug output.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create Managed Zone with a description
2. Create Record Set in Managed Zone
2. Apply Terraform Configuration
3. Change Managed Zone Description.
4. Re-apply Terraform

### Important Factoids
N/A

### References
N/A

**Comment by rosbo** [comment] 2018-06-07 20:13
This is a duplicate of #1572. Closing this issue to keep all the discussion in one place

**Closed by rosbo** 2018-06-07 20:13 UTC
