### ISSUE TITLE
google_sql_database_instance (partially) ignores "project" attribute

### ISSUE THREAD

**Issue by jaceq** [terraform-providers/terraform-provider-google#2194] opened 2018-10-09 11:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.8
* provider.google: version = "~> 1.18"
also tried
* provider.google: version = "~> 1.19"

### Affected Resource(s)

google_sql_database_instance

### Terraform Configuration Files

```
resource "google_sql_database_instance" "master" {
  name             = "${var.database_name}"
  database_version = "${var.database_engine}"
  region           = "${var.region}"
  project          = "${module.sub_project.id}"
  
  settings {
    tier = "db-f1-micro"
  }
}

```

### Plan looks like:
```
  + google_sql_database_instance.master
      id:                                <computed>
      connection_name:                   <computed>
      database_version:                  "MYSQL_5_7"
      first_ip_address:                  <computed>
      ip_address.#:                      <computed>
      master_instance_name:              <computed>
      name:                              "search-db"
      project:                           "YYYY-stage-XXXXXX"
      region:                            "europe-west1"
      replica_configuration.#:           <computed>
      self_link:                         <computed>
      server_ca_cert.#:                  <computed>
      service_account_email_address:     <computed>
      settings.#:                        "1"
      settings.0.activation_policy:      <computed>
      settings.0.availability_type:      <computed>
      settings.0.backup_configuration.#: <computed>
      settings.0.crash_safe_replication: <computed>
      settings.0.disk_autoresize:        "true"
      settings.0.disk_size:              <computed>
      settings.0.disk_type:              <computed>
      settings.0.ip_configuration.#:     <computed>
      settings.0.location_preference.#:  <computed>
      settings.0.pricing_plan:           "PER_USE"
      settings.0.replication_type:       "SYNCHRONOUS"
      settings.0.tier:                   "db-f1-micro"
      settings.0.version:                <computed>
```

### Expected Behavior

A Cloud SQL should be created in project YYYY-stage-XXXXXX and thus sqladmin.googleapis.com on that project should be used.

### Actual Behavior

Resource fails due to the fact it tries to contact sqladmin.googleapis.com in PROVIDER config, error:
```
* google_sql_database_instance.master: Error, failed to create instance search-db: googleapi: Error 403: Access Not Configured. Cloud SQL Admin API has not been used in project 739136664354 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=739136664354 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

Link from error leads to PROVIDER project, which is NOT YYYY-stage-XXXXXX. Provider project has this api DISABLED. What is also interesting is that when I enable this API for provider project, my instance does get created in  YYYY-stage-XXXXXX and not provider project itself...

### Steps to Reproduce

try to define google_sql_database_instance in different than provider project while having sqladmin.googleapis.com api DISABLED in provider project.

* #0000

**Comment by Chupaka** [comment] 2018-11-27 12:52
PING :)

Any news on this?

**Comment by sergei-ivanov** [comment] 2018-12-05 12:21
I have just wasted half a day trying to identify and then verify the root cause of this problem. And in the end it appears to be a Google Cloud API issue rather than a Terraform issue. There is a pretty good explanation of it [here](https://github.com/terraform-providers/terraform-provider-google/issues/1538#issuecomment-392127015), but let me provide some evidence to prove that it is really the case. Project names and ids had to be redacted to protect the innocent.

The set-up is as follows:
* `admin` project (id: 000000000000)
* `terraform` service account in the `admin` project
* a JSON key was generated for the `terraform` account and used as credentials in the terraform google provider configuration
* `production` project that I am trying to terraform
* a Cloud SQL instance in the `production` project

Terraform and provider versions:
```
$ terraform --version
Terraform v0.11.10
+ provider.google v1.19.1
```
So when I am running a `terraform plan` command, I get the following error:

```
$ terraform plan -target=module.main.google_sql_database_instance.mysql
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

<...>
google_sql_database_instance.mysql: Refreshing state... (ID: production-01)

Error: Error refreshing state: 1 error(s) occurred:

* module.main.google_sql_database_instance.mysql: 1 error(s) occurred:

* module.main.google_sql_database_instance.mysql: google_sql_database_instance.mysql: Error reading SQL Database Instance "production-01": googleapi: Error 403: Access Not Configured. Cloud SQL Admin API has not been used in project 000000000000 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=000000000000 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

Now, if I activate `terraform` account credentials for Google Cloud SDK and run an equivalent `gcloud` command, I will get the same kind of error:

```
$ gcloud sql instances list --quiet --project=production
ERROR: (gcloud.sql.instances.list) User [terraform@admin.iam.gserviceaccount.com] does not have permission to access project [production] (or it may not exist): Access Not Configured. Cloud SQL Admin API has not been used in project 000000000000 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=000000000000 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

Basically, what it is trying to say is that you are trying to use a particular API, but that API is not enabled in the `admin` project (id: 000000000000). It does not matter if the API is enabled in the target project, it seems that it must be enabled in the home project of the `terraform` service account, and then the service account uses its home project as a proxy to control other accounts. Listing the enabled services serves as a good illustration for the above:

```
$ gcloud services list --project=production --filter='name~sqladmin'
NAME                     TITLE
sqladmin.googleapis.com  Cloud SQL Admin API

$ gcloud services list --project=admin --filter='name~sqladmin'
Listed 0 items.
```

In summary, even if it sounds counter-intuitive and illogical, `admin` project needs to have a superset of APIs enabled in order to control APIs in other projects. And if a new service needs to be activated in the target project, it needs to be activated in the `admin` project first.

**Comment by danawillow** [comment] 2018-12-11 22:43
@sergei-ivanov is right, the enabled APIs need to be on the project where the credentials come from. I agree that this is unintuitive behavior, and I'm looking into getting some docs that explain it better. In the meantime, closing since I don't think there's anything we can do here.

**Closed by danawillow** 2018-12-11 22:43 UTC
Labels: bug
