### ISSUE TITLE
Add optionalComponents to dataproc cluster

### ISSUE THREAD

**Issue by emilymye** [terraform-providers/terraform-provider-google#4159] opened 2019-08-05 17:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add softwareConfig.optionalComponents (list of enum values) to dataproc cluster to allow for optional components 

### New or Affected Resource(s)

* `google_dataproc_cluster`

### Potential Terraform Configuration
```tf
resource "google_dataproc_cluster" "simplecluster" {
    name       = "simplecluster"
    region     = "us-central1"

   software_config {
      optional_components = [ "ANACONDA", "HIVE_WEBHCAT", "JUPYTER", "ZEPPELIN" ]
   }
}

### References

https://cloud.google.com/dataproc/docs/reference/rest/v1/ClusterConfig#softwareconfig

**Comment by danawillow** [comment] 2019-08-05 18:54
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3075

**Closed by danawillow** 2019-08-05 18:54 UTC
Labels: enhancement
