### ISSUE TITLE
Add option to set retry policy in google_pubsub_subscription resource

### ISSUE THREAD

**Issue by abhinav454** [terraform-providers/terraform-provider-google#6777] opened 2020-07-10 13:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Pub/Sub subscription now supports adding delays to the retries and allows changing the retry policy from `Retry Immediately` to `Retry after exponential backoff delay`. As part of the delay, it supports Minimum and Maximum backoff (seconds). There seems to be an API support for this, but not yet available using TF. 

### New or Affected Resource(s)

* google_pubsub_subscription

### Potential Terraform Configuration

```tf
resource "google_pubsub_subscription" "subscription" {
  name  = "my-subscription"
  topic = "my-topic"

  retry_policy {
    minimum_backoff = "20s"
    maximum_backoff = "30s" 
  }
}
```

### References

* https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#retrypolicy

**Comment by danawillow** [comment] 2020-07-13 17:44
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/6623

**Closed by danawillow** 2020-07-13 17:44 UTC
Labels: enhancement
