### ISSUE TITLE
Private IP Cloud Composer options missing

### ISSUE THREAD

**Issue by ChethanUK** [terraform-providers/terraform-provider-google#6113] opened 2020-04-14 06:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Option to enable Cloud Composer to assign only private IP addresses to the managed Google Kubernetes Engine and Cloud SQL VMs in your environment

Check more details on https://cloud.google.com/composer/docs/how-to/managing/configuring-private-ip

Enable the option to choose: 
- GKE cluster master private IP range
- Web server private IP
- Cloud SQL private IP

**Comment by bw-josepavonalvarez** [comment] 2020-04-14 06:55
You can define the GKE cluster master private IP range with the current terraform resource.

Look at the resource documentation: https://registry.terraform.io/providers/hashicorp/google/3.16.0/docs/resources/composer_environment#master_ipv4_cidr_block

On the other hand, this is a duplicate of #6106

**Comment by ChethanUK** [comment] 2020-04-14 07:39
> master private IP

Ya this was there: `master_ipv4_cidr_block`

But What about CloudSQL and Webapp?

**Comment by danawillow** [comment] 2020-04-20 17:36
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/6106.

**Closed by danawillow** 2020-04-20 17:36 UTC
Labels: enhancement
