### ISSUE TITLE
Project creation with auto_create_network=false should not fail when constraints/compute.skipDefaultNetworkCreation is enforced

### ISSUE THREAD

**Issue by dlinares-linux** [terraform-providers/terraform-provider-google#4990] opened 2019-11-25 16:56 UTC
Hi all,

Reporting this issue faced when I enforced an organization policy at organization level to skip the default network creation (constraints/compute.skipDefaultNetworkCreation).
Any project created with `auto_create_network = false` fails because it doesn't find the default network to try and delete it. As the result, the project is created on GCP, but is not imported to the tfstate.

Here is my code that fails (I apply it in 2 steps, the org policy first)
```
# Org policy to enforce constraints/compute.skipDefaultNetworkCreation
resource "google_organization_policy" "org_policy_compute_skip_default_network_creation" {
  org_id     = var.org_id
  constraint = "compute.skipDefaultNetworkCreation"

  boolean_policy {
    enforced = true
  } 
}

# Create a folder under my org
resource "google_folder" "my_test_folder" {
  display_name = "My test folder"
  parent       = "organizations/${var.org_id}"
}

# Creation of a project
resource "google_project" "my_test_project" {
  name                = "my-test-project"
  project_id          = "my-test-project"
  folder_id           = google_folder.my_test_folder.name
  billing_account     = var.billing_account
  auto_create_network = false
}
```

That code will generate the following error:
```
Error: Error deleting default network in project my-test-project: Error deleting network: googleapi: Error 404: The resource 'projects/my-test-project/global/networks/default' was not found, notFound
```

I believe this is a bug and the project creation should not fail irrespective to whether an org policy is there or not to skip the default network creation.

**Comment by ndmckinley** [comment] 2019-11-25 20:10
Agreed - I can fix that.

**Comment by ndmckinley** [comment] 2019-11-25 20:13
Ah, that's been fixed since 2.17.0 - please upgrade your provider and the issue should disappear.

**Comment by dlinares-linux** [comment] 2019-11-26 09:32
Hi @ndmckinley ,
I am using the following, which is the latest for the provider:
```
terraform version
Terraform v0.12.13
+ provider.google v3.0.0-beta1
```

Please also note that I faced a similar issue with the `constraints/serviceuser.services`. If that org policy is set to deny the `compute.googleapis.com`, then, the project creation fails because it tries to use the compute API to delete the default network and fails.

**Comment by ndmckinley** [comment] 2019-11-26 19:16
Can you link your debug logs?  I don't have access to an organization I can set that constraint on, so I'll have to work from your logs.

**Comment by ndmckinley** [comment] 2019-11-26 19:20
> Please also note that I faced a similar issue with the `constraints/serviceuser.services`. If that org policy is set to deny the `compute.googleapis.com`, then, the project creation fails because it tries to use the compute API to delete the default network and fails.

I find this part acceptable - if you have denied access to `compute.googleapis.com`, lots of `project` attributes won't work.  A handful of `project` features are in `compute`.  You can just get what you're looking for by not setting `auto_create_network` there.

**Comment by dlinares-linux** [comment] 2019-11-27 15:17
Hi @ndmckinley ,
Here is a link to a gist showing some logs (with DEBUG level) : https://gist.github.com/dlinares-linux/d83fb7ea79997dc8a22b56aa2a3ff539
For this test, I have only applied the policy enforcing compute.skipDefaultNetworkCreation.
Kind regards,
David

**Comment by ndmckinley** [comment] 2019-12-06 21:42
Hi, @dlinares-linux,

The log you've pasted includes only the top 20 and bottom 20 lines of the output - I need much more detail than that.  If you're uncomfortable posting it publicly, you can email it to me at the email address on my profile, nmckinley@google.com.

**Comment by xynova** [comment] 2019-12-15 21:52
We just ran with 2.20 and faced the issue too

  required_providers {
    google      = "v2.20.0"
    google-beta = "v2.20.0"
  }

**Comment by chrisst** [comment] 2020-01-09 00:40
closing as this is a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3582

**Closed by chrisst** 2020-01-09 00:40 UTC
Labels: bug
