### ISSUE TITLE
Add NAT parameters to Google Compute Router

### ISSUE THREAD

**Issue by Phylu** [terraform-providers/terraform-provider-google#2389] opened 2018-11-02 08:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

[Google Cloud NAT](https://cloud.google.com/nat/docs/) allows to create a NAT gateway using the Google Compute Router. All network traffic from instances in the network without an external IP address will be routed through the NAT gateway.

### New or Affected Resource(s)

* google_compute_router

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_router" "foobar" {
  name    = "my-router"
  network = "${google_compute_network.foobar.name}"
  nat {
    name = "nat-gateway"
    sourceSubnetworkIpRangesToNat = "10.0.0.0/16"
    subnetworks {
        name = "subnetwork-1"
        source_ip_ranges_to_nat = ["10.0.0.0/24"]
        secondary_ip_range_names = ["${google_compute_subnetwork.secondary_ip_range.0.name}"]
      }
      natIps = ["${google_compute_address.my_address.address}"]
  }
}
```

### References

* [REST API](https://cloud.google.com/compute/docs/reference/rest/beta/routers)

**Comment by Chupaka** [comment] 2018-11-02 08:33
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/2249

**Comment by ndmckinley** [comment] 2018-11-06 00:06
Closing as a duplicate - I agree that this is important, as indicated by the ~90 :+1: on that other PR.  :)

**Closed by ndmckinley** 2018-11-06 00:06 UTC
Labels: enhancement

**Comment by Phylu** [comment] 2018-11-06 17:58
Thanks for closing. I didn't see that it wasn't closed automatically after the duplicate comment. I need to work on my github issue filters for the future ;-)
