### ISSUE TITLE
Permadiff on container network/subnetwork after upgrading from 1.12

### ISSUE THREAD

**Issue by fproulx-eoscanada** [terraform-providers/terraform-provider-google#1960] opened 2018-08-29 19:58 UTC
This occured following an upgrade from 1.12 to 1.17 (this works well with 1.12).
We are using a Google Cloud Storage state backend.

### Terraform Version
```
$ terraform -v
Terraform v0.11.8
+ provider.google v1.17.1
```

### Affected Resource(s)
- google_container_cluster
- google_compute_network
- google_compute_subnetwork

### Terraform Configuration Files
```hcl
...
resource "google_compute_network" "vpc" {
  name                    = "vpc"
  auto_create_subnetworks = false
  routing_mode            = "REGIONAL"
}
...
resource "google_compute_subnetwork" "subnet-yul-api" {
  name                     = "subnet-yul-api"
  ip_cidr_range            = "10.1.0.0/18"                                 # max: 10.1.63.255
  network                  = "${google_compute_network.vpc.self_link}"
  region                   = "northamerica-northeast1"
  private_ip_google_access = true
  enable_flow_logs         = false

  secondary_ip_range {
    range_name    = "range-yul-api-services"
    ip_cidr_range = "10.1.64.0/20"           # max: 10.1.79.255
  }

  secondary_ip_range {
    range_name    = "range-yul-api-containers"
    ip_cidr_range = "10.1.128.0/17"            # max: 10.1.255.255
  }
}
...
esource "google_container_cluster" "k8s-yul-api" {
  name   = "k8s-yul-api"
  region = "northamerica-northeast1"

  min_master_version = "${var.k8s_min_master_version}"
  node_version       = "${var.k8s_node_version}"

  network    = "${google_compute_network.vpc.self_link}"
  subnetwork = "${google_compute_subnetwork.subnet-yul-api.name}"

  ip_allocation_policy {
    cluster_secondary_range_name  = "range-yul-api-containers"
    services_secondary_range_name = "range-yul-api-services"
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block = "${google_compute_subnetwork.subnet-yul-management.ip_cidr_range}"
    }

    cidr_blocks {
      cidr_block = "${var.k8s_remote_management_cidr}"
    }
  }

  # Disables fully legacy insecure authentication
  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  addons_config {
    kubernetes_dashboard {
      disabled = true
    }
  }

  lifecycle {
    ignore_changes = ["node_pool"]
  }

  node_pool {
    name = "default-pool"
  }

  remove_default_node_pool = true
}
...
```

### Expected Behavior

No-op - the state is in sync with the hcl.

### Actual Behavior

Successive applies keep acting as if state has not changed. I get this in endless loop everytime I apply:

```
...
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ google_container_cluster.k8s-yul-api
      network:    "projects/myproject/global/networks/vpc" => "https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc"
      subnetwork: "projects/myproject/regions/northamerica-northeast1/subnetworks/subnet-yul-api" => "subnet-yul-api"

Plan: 0 to add, 1 to change, 0 to destroy.
...
```

### Steps to Reproduce
1. `terraform apply`

**Comment by paddycarver** [comment] 2018-08-30 10:10
I'm going to retitle this issue, because this isn't actually a state _corruption_--the state is still there, and is still valid, and being read back appropriately. Which is good news! This is something that can be fixed without much pain or manual intervention. A state corruption is much messier and requires more manual effort. So I'm happy you don't have one of those.

That does not mean, however, that you don't have an issue, or that it's not important to fix that issue. So let's dig into the issue you do have!

It looks like when we introduced Shared VPC support for GKE (#1528), we switched from modifying the `network` and `subnetwork` fields before they went into the state, to considering several values in the state as equivalent. More concretely, we used to write `https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc` to the state, and Terraform would _actually_ record `projects/myproject/global/networks/vpc`. Then when it came time to detect a diff, we'd compare `projects/myproject/global/networks/vpc` to `projects/myproject/global/networks/vpc`, see they're the same, and say there's no diff.

In 1.13, it looks like we changed instead to actually recording `https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc`, and when it came time to diff, saying `https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc` and `vpc` should both be considered equal to `https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc`.

Noticeably, it looks like we left out `projects/myproject/global/networks/vpc` from that logic. But Terraform should have automatically overwritten that with `https://www.googleapis.com/compute/v1/projects/myproject/global/networks/vpc` before we even got to the diff.

Are you running with `-refresh=false`?

Does calling `terraform refresh` then `terraform plan` fix this?

**Comment by danawillow** [comment] 2018-09-07 00:31
I think this is a dupe of #988 (upstream issue https://github.com/hashicorp/terraform/issues/18209) since it's showing an in-place update on a ForceNew field. I'm going to go ahead and close this as a duplicate. There are some potential workarounds that people have posted on #988 and its linked issues- hopefully one of them works for you!

**Closed by danawillow** 2018-09-07 00:31 UTC
Labels: bug
