### ISSUE TITLE
google_compute_instance created from within Google Cloud has no network attributes despite their being set

### ISSUE THREAD

**Issue by christopher-demarco** [terraform-providers/terraform-provider-google#571] opened 2017-10-11 00:44 UTC
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance

### Terraform Configuration Files
```hcl
variable "admin" { default = "magrathea" }
variable "admin_key" { default = "keys/magrathea.pub" }
variable "names" { default = ["alpha"] }
variable "subdomain" { default = "" }
variable "region" { default = "us-east4" }

provider "google" {
  credentials = "${file("keys/magrathea.json")}"
  project = "magrathea-178523"
  region = "${var.region}"
}

resource "google_compute_instance" "workstation" {
  count = "${length(var.names)}"
  name = "${var.names[count.index]}"
  #machine_type = "f1-micro"
  machine_type = "n1-standard-1"
  #machine_type = "n1-highcpu-2"
  zone = "${var.region}-a"
  can_ip_forward = true
  boot_disk { initialize_params { image = "ubuntu-1704" } }
  network_interface { network = "default" access_config { } }
  metadata { sshKeys = "${var.admin}:${file("${var.admin_key}")}" }
}

output "workstations" { value = "${google_compute_instance.workstation.*.network_interface.0.access_config.0.assigned_nat_ip}" }

output "hostnames" { value = "${google_compute_instance.workstation.*.name}" }
```

### Debug Output
https://gist.github.com/christopher-demarco/148b7ab8c14e157420ad5627a3d2cdfc

### Expected Behavior
The resource should have been created with `network_interface.0.access_config.0.assigned_nat_ip`—or indeed any networking attributes at all.

### Actual Behavior
The resource was created with *no* network attributes.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The behavior is limited to when running inside a Google Cloud instance; macOS host works just fine. Credentials etc. are otherwise the same.

**Comment by christopher-demarco** [comment] 2017-10-11 00:50
Note, however, that in lines 2492 .. 2495 of the attached gist, that an external-nat address *does* appear to have been allocated. It's just not visible to Terraform. The networking config does not appear in the output of `terraform show` nor in the `terraform.tfstate`.

**Comment by christopher-demarco** [comment] 2017-10-11 00:55
And, indeed, if I pop open the Google Cloud console, I can discover the IP address allocated to this resource and SSH in just fine.

The problem is that Terraform doesn't seem to understand that these attributes have been allocated!

**Comment by zarmin** [comment] 2017-10-11 12:16
exactly the same issue here

**Comment by rosbo** [comment] 2017-10-11 20:24
Duplicate of #519. PR #536 will fix it.

**Closed by rosbo** 2017-10-11 20:24 UTC
