### ISSUE TITLE
Terraform provider is out of sync with Dataproc API, to Enable Component Gateway

### ISSUE THREAD

**Issue by VigneshCanada** [terraform-providers/terraform-provider-google#5878] opened 2020-03-11 00:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Couldn't enable component gateway on dataproc cluster thru Terraform. Using endpoint_config option is also not working as it is error'ed out with "invalid or unknown key". 
FYI : I have tried with google-beta provider.  

Can someone please update the Dataproc API for the terraform provider.

### New or Affected Resource(s)

* google_dataproc_cluster
* Component_gateway
* Endpoint_config

### Potential Terraform Configuration

```software_config {
      optional_components   = [ "DOCKER",  "ANACONDA", "JUPYTER" ]
      image_version         = "${var.cluster_version}"
      override_properties   = {
        "dataproc:dataproc.allow.zero.workers" = "true"
        "dataproc:dataproc.logging.stackdriver.enable" = "true"
        "dataproc:dataproc.enable_component_gateway" = "true"
      }
   }
  endpoint_config {
      enable_http_port_access = "true"
   }
```
This would be of immense help to spin up the resources as code and avoid using console to manually get this done each time. 

Appreciate your time to look into this feature request.

Thank you

**Comment by danawillow** [comment] 2020-03-16 17:38
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/4128.

**Closed by danawillow** 2020-03-16 17:38 UTC
Labels: enhancement
