### ISSUE TITLE
Supporting hivePartitioningOptions offered in table.insert in the TF external_data_configuration block

### ISSUE THREAD

**Issue by megaz94** [terraform-providers/terraform-provider-google#6487] opened 2020-05-29 14:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Terraform BigQuery currently does not support [ExternalDataConfiguration](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#externaldataconfiguration) > hivePartitioningOptions. At the time of writing this message, [terraform](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#argument-reference) supports 2 ExternalDataConfiguration options: csvOptions and googleSheetsOptions.

### Potential Terraform Configuration

At this time, there is no configuration workaround.

As a hint for the terraform team, note that the constructions of [table.insert](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/insert)  for hivePartitioningOptions must have the following form:
```
{
tableReference {},
externalDataConfiguration{schema {}, hivePartitioningOptions{}} // putting the schema inside externalDataConfiguration and not in the outer scope
}
```
Constructing the JSON in the following way is incorrect and doesn't propagate the hive_keys correctly to the BQ destination table:
```
{
tableReference {},
schema {},
externalDataConfiguration{hivePartitioningOptions{}}
}
```

**Comment by danawillow** [comment] 2020-06-01 18:21
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5664. The feature has been merged so I think it'll show up in next Monday's release.

**Closed by danawillow** 2020-06-01 18:21 UTC
Labels: enhancement
