### ISSUE TITLE
How to disable Object-level permissions when creating a bucket?

### ISSUE THREAD

**Issue by kdzhao** [terraform-providers/terraform-provider-google#3721] opened 2019-05-24 22:48 UTC
Hello!
When creating a bucket using google provider, how do I disable Object-level permissions for it? (so all objects in that bucket will have the same permission as the bucket). I didn't see such option in this doc (https://www.terraform.io/docs/providers/google/r/storage_bucket.html), but please let me know if it is via another operation. 

Thanks!

**Comment by Chupaka** [comment] 2019-05-28 13:11
Here's the feature request: https://github.com/terraform-providers/terraform-provider-google/issues/3073

**Comment by kdzhao** [comment] 2019-05-28 16:54
Thanks, good to know.

**Comment by rileykarson** [comment] 2019-05-28 17:23
Closing as a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3073

**Closed by rileykarson** 2019-05-28 17:23 UTC
