### ISSUE TITLE
Regression: can't set up a www -> no-www redirect now, used to work in 3.25.0

### ISSUE THREAD

**Issue by hallvors** [terraform-providers/terraform-provider-google#6695] opened 2020-06-25 11:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.27
+ provider.google v3.27.0

### Affected Resource(s)

* google_compute_url_map

### Terraform Configuration Files

This is an extract from a larger file:

```tf
resource "google_compute_url_map" "default" {
  name        = "test-staging-loadbalancer-urlmap"
  description = "test load balancer (URL map). Managed by Terraform."

  project         = test
  default_service = google_compute_backend_service.public.self_link

  host_rule {
    hosts        = [var.domain_admin]
    path_matcher = "admin"
  }

  path_matcher {
    name            = "admin"
    default_service = google_compute_backend_service.admin.self_link
  }

  host_rule {
    description  = "remove www. prefixes"
    hosts        = ["www.${var.domain_public}"]
    path_matcher = "public-nowww"
  }

  path_matcher {
    name = "public-nowww"
    default_url_redirect {
      host_redirect = var.domain_public
      strip_query   = false
    }
  }
}


```

### Expected Behavior

www.* to no-www redirect, like one is still allowed to configure manually in the console.

### Actual Behavior

Running this in 3.25.0 works fine, running it with 3.27.0 causes an error:
Error: "path_matcher.1.default_url_redirect": conflicts with default_service

I think this may be a regression caused by https://github.com/terraform-providers/terraform-provider-google/pull/6547

Also, I'm not the only person who ran into this problem: https://stackoverflow.com/questions/62469495/how-to-add-host-redirect-from-secondary-to-primary-domain-using-terraform-and-go

I understand this change my be on purpose and perhaps the config should have different URL maps set up instead of adding these rules to a single URL map. If so, documentation for a breaking change on how to fix it would be appreciated.

### References

* https://github.com/terraform-providers/terraform-provider-google/pull/6547

**Comment by edwardmedia** [comment] 2020-06-25 15:42
I do see behavior changes

**Comment by c2thorn** [comment] 2020-06-30 22:46
@hallvors thanks for pointing this out! It was unintended behavior, and should be resolved in the next patch.

**Closed** 2020-06-30 22:45 UTC
Labels: bug
