### ISSUE TITLE
Support KMS Asymetric Signing / Decryption keys

### ISSUE THREAD

**Issue by fproulx-eoscanada** [terraform-providers/terraform-provider-google#2159] opened 2018-10-03 21:16 UTC
### Description

GCloud offers KMS Asymetric keys, it'd be good that Terraform supports it
https://cloud.google.com/kms/docs/create-validate-signatures

**Comment by paddycarver** [comment] 2019-12-12 23:35
This looks like a duplicate of #3039.

**Closed by paddycarver** 2019-12-12 23:35 UTC
Labels: enhancement
