### ISSUE TITLE
Empty string in members in google_kms_key_ring_iam_binding produces an error

### ISSUE THREAD

**Issue by psalaberria002** [terraform-providers/terraform-provider-google#3850] opened 2019-06-14 12:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.12.2

### Affected Resource(s)

* google_kms_key_ring_iam_binding

### Terraform Configuration Files

```tf
provider "google" {
  version     = "2.7.0"
}

resource "google_kms_key_ring" "nostromo_key_ring" {
  name     = "nostromo"
  location = "global"
}

resource "google_kms_key_ring_iam_binding" "nostromo_key_ring_encrypter_decrypter" {
  key_ring_id = google_kms_key_ring.nostromo_key_ring.id
  role        = "roles/cloudkms.cryptoKeyEncrypterDecrypter"

  members = []
}
```

### Debug Output

https://gist.github.com/psalaberria002/8a6feb6991fc209eb6ba49a90d657a2d

### Expected Behavior

Terraform should not have failed. It should just make sure nobody has that given role in the resource.

### Actual Behavior

It crashes.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Setting members to an empty list does not seem to work.
This used to work in 0.11. It would try to recreate it in every run, but it would not crash.

**Comment by emilymye** [comment] 2019-06-14 17:57
Did you create the binding with 0.11 and then upgrade?

**Comment by drebes** [comment] 2019-06-17 20:15
Looks like a dupe of terraform-providers/terraform-provider-google#2007

**Comment by chrisst** [comment] 2019-07-09 20:49
Closing as duplicate.

**Closed by chrisst** 2019-07-09 20:49 UTC
Labels: bug
