### ISSUE TITLE
google_project_services returning before APIs fully enabled in GCP

### ISSUE THREAD

**Issue by steven-edgar** [terraform-providers/terraform-provider-google#2129] opened 2018-09-28 15:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
v0.11.7
Google provider 1.15

### Affected Resource(s)

* google_dataproc_cluster
* google_project_services

### Terraform Configuration Files

```
resource "google_project" "my-gcp-project1" {
  name = "my-gcp-proiect1"
  project_id = "my-gcp-project1"
  folder_id = "1234567890"
  billing_account = "abcdef-123456-123abc"
  skip_delete = "true"
}
resource "google_project_services" "my-gcp-project1" {
  project = "${google_project.my-gcp-project1.number}"
  services = [ "compute.googleapis.com", "oslogin.googleapis.com", "logging.googleapis.com", "monitoring.googleapis.com", "iam.googleapis.com", "dataproc.googleapis.com" ]

resource "google_dataproc_cluster" "my-gcp-project1" {
  name = "dataproc-cluster-1"
  cluster_config {
....
  }
  depends_on = [ "google_project.my-gcp-project", "google_project_services.my-gcp-project" ]
}
```

### Expected Behavior
Google project created, then listed APIs enabled, and finally dataproc cluster created after the dataproc API has been fully enabled in the project. I've actually seen this behaviour before with other resource types trying to provision before APIs are fully enabled, so presume this is actually an issue with the google_project_services module returning before the API(s) are fully enabled in GCP. Re-running the apply generally works.

### Actual Behavior

Terraform exits with error stating the API is not enabled. 
Error applying plan:

1 error(s) occurred:

* google_dataproc_cluster.dataproc-cluster-1: 1 error(s) occurred:

* google_dataproc_cluster.dataproc-cluster-1: Error creating Dataproc cluster: googleapi: Error 403: Cloud Dataproc API has not been used in project 1234567890123 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=1234567890123 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by danawillow** [comment] 2018-10-01 17:16
Hi @steven-edgar, in this particular case, the resource name is different between the definition and the `depends_on`:
```
resource "google_project_services" "my-gcp-project1" {
```
```
depends_on = [ "google_project.my-gcp-project", "google_project_services.my-gcp-project" ]
```

can you try again with the correct resource name and see if that works?

**Comment by steven-edgar** [comment] 2018-10-02 06:53
Sorry, that was just my removing internal names from the example, I obviously typo’d that, but my source terraform file is consistent.

Thanks

Steven

**Comment by danawillow** [comment] 2018-10-02 17:53
Hm, that's a bummer. Do you have debug logs? My guess is this is a GCP issue- we know that this API is eventually consistent, and that even when the service usage API returns that a service is enabled, it can't always be used right away, but that case should be more rare than it sounds like you're experiencing it. Debug logs will help us pinpoint whether it's a GCP issue or a TF one.

**Comment by jaceq** [comment] 2018-10-09 12:52
I encountered same problem... As a workaround I added a 30 second sleep after enabling APIs and before any other resources are created... so far this works 100% of time.

**Comment by likwid** [comment] 2019-02-27 22:13
I experience this problem 100% of the time, with some interaction between `google_project`, `google_project_service`, and `google_compute_network`.  I talked to Ben Bleything about this on the HangOps Slack community as well.

Here is the gist containing the repro terraform code:  https://gist.github.com/likwid/d1f0b220089ffb810f5211edc8768791

I tried the local provisioner, and that didn't work either. I noticed that Steven's example is slightly different, as he is using `google_project_services` instead of `google_project_service` with count.

I tried modifying my terraform code to use `google_project_services` and the problem actually seemed to get worse.

I am attempting to create GCP projects with networks in them, and the eventual consistency issues with this API are making it pretty challenging. I recognize resolving the issue is going to take some time, but I am at a loss of what to do until then.

Any ideas?

**Comment by danawillow** [comment] 2019-02-28 14:49
Hey @likwid, could you open a new issue with the full template (including debug logs)? It sounds like what you're running into is different from this issue (and I'm taking a break from TF at the moment so I won't be able to investigate this right now)

**Comment by uberspot** [comment] 2019-03-14 11:15
I get the same error when changing from individual google_project_service to google_project_services.

```   - google_project_service.enable_container_analysis

  - google_project_service.enable_container_service

  - google_project_service.enable_dns_service

  - google_project_service.enable_kms_service

  - google_project_service.enable_servicenetworking_service

  + google_project_services.project_name
      id:                           <computed>
      disable_on_destroy:           "true"
      project:                      "project_name"
      services.#:                   "20"
      services.1305307:           "storage-component.googleapis.com"
      services.15684289:          "oslogin.googleapis.com"
      services.16102296:          "bigquery-json.googleapis.com"
      services.17125308:          "containerregistry.googleapis.com"
      services.17931363:          "clouddebugger.googleapis.com"
      services.54675454:          "serviceusage.googleapis.com"
      services.21174213:          "pubsub.googleapis.com"
      services.21764226:          "cloudkms.googleapis.com"
      services.22404979:          "compute.googleapis.com"
      services.22544451:          "containeranalysis.googleapis.com"
      services.24556047:          "servicenetworking.googleapis.com"
      services.24715660:          "servicemanagement.googleapis.com"
      services.29284140:          "dns.googleapis.com"
      services.3125032:           "cloudtrace.googleapis.com"
      services.32375688:          "monitoring.googleapis.com"
      services.33593353:          "logging.googleapis.com"
      services.37400850:          "container.googleapis.com"
      services.35785048:          "storage-api.googleapis.com"
      services.773126:            "sql-component.googleapis.com"
      services.9368001:           "datastore.googleapis.com"
```
which fails with 
```
 Error: Error refreshing state: 3 error(s) occurred:

* google_service_networking_connection.default: 1 error(s) occurred:

* google_service_networking_connection.default: google_service_networking_connection.default: googleapi: Error 403: Service Networking API has not been used in project <redacted> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/servicenetworking.googleapis.com/overview?project=<redacted> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
* google_kms_crypto_key.key_name: 1 error(s) occurred:

* google_kms_crypto_key.key_name: google_kms_crypto_key.key_name: Error reading CryptoKey: googleapi: Error 400: Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=<redacted> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., failedPrecondition
* google_kms_crypto_key.redacted: 1 error(s) occurred:

* google_kms_crypto_key.redacted: google_kms_crypto_key.vault: Error reading CryptoKey: googleapi: Error 400: Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=<redacted> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., failedPrecondition
```

and it keeps failing until I manually enable the API from the console.

After enabling the APIs, terraform apply sometimes has no change and sometimes adds/removes other services from the enabled_services list without any apparent reason.

**Comment by rileykarson** [comment] 2019-06-27 16:41
We currently wait until all services are enabled before exiting the resource, which I don't believe was implemented at the time of this issue. If you're still encountering this behaviour in a`2.X` series release, please file a new issue!

**Closed by rileykarson** 2019-06-27 16:41 UTC
Labels: bug
