### ISSUE TITLE
google_compute_region_instance_group_manager: Fails to create with an INTERNAL_ERROR

### ISSUE THREAD

**Issue by adastidar** [terraform-providers/terraform-provider-google#1961] opened 2018-08-30 06:12 UTC
### Terraform Version
0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_region_instance_group_manager

### Terraform Configuration Files
```hcl
module "nat_gateway_group" {
  source            = "GoogleCloudPlatform/managed-instance-group/google"
  version           = "1.1.10"
  region            = "${var.region}"
  name              = "xxx"
  size              = "1"
  can_ip_forward    = true
  target_tags       = ["service-nat"]
  service_port      = 80
  service_port_name = "tcp"
  autoscaling       = false
  http_health_check = false
  compute_image     = "centos-cloud/centos-7-v20180716"
  subnetwork        = "${data.google_compute_subnetwork.subnetwork.self_link}"
  ssh_fw_rule       = false
  wait_for_instances = true
  startup_script    = "${data.template_file.startup.rendered}"
  zone              = "${var.region}"
  zonal             = false
}
```

### Debug Output
https://gist.github.com/adastidar/24b25b946df4927d0297df8b11bc0b4c

### Panic Output
No

### Expected Behavior
Create the Instance group and the VM instances as part of this group

### Actual Behavior
The run fails with an error code and the debug response shows this:
```
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  "error": {
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:   "errors": [
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:    {
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:     "code": "INTERNAL_ERROR",
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:     "message": "Code: '3754916996071859369'"
2018-08-29T21:37:39.414Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:    }
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:   ]
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  },
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  "warnings": [
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:   {
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:    "code": "NOT_CRITICAL_ERROR",
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:    "message": "Health check should be provided when specifying initial delay."
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:   }
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  ],
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  "httpErrorStatusCode": 503,
2018-08-29T21:37:39.415Z [DEBUG] plugin.terraform-provider-google_v1.17.1_x4:  "httpErrorMessage": "SERVICE UNAVAILABLE",
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
No

### References
No

**Comment by paddycarver** [comment] 2018-08-30 09:37
Can you verify that this happens consistently, and was not just a one-off error? The 503 response suggests that there was an error in the GCP backend, not in the request made.

**Comment by adastidar** [comment] 2018-08-30 09:38
Yes, it happens evertime. However, when I grant the service account owner permissions on the project, the resources get created.

**Comment by paddycarver** [comment] 2018-08-30 09:58
Interesting! I'm going to label this `upstream`, because the API should never throw a 503 reliably in the face of only _certain_ requests. I'll distill this to an API request that can reliably replicate the error, and get a bug opened upstream on it.

The warning seems to spawn from the `initial_delay` defaulting to `300` in the module you're using, but the health check being set to `""`.

**Comment by danawillow** [comment] 2018-09-07 00:27
@paddycarver, assigning this to you since you said you were going to do stuff. If you aren't, feel free to unassign :)

**Comment by rileykarson** [comment] 2019-06-25 21:28
Since this seems like an API issue and the module it was based on isn't update for `0.12`/`2.0.0`, I'm closing this out. If you're able to reproduce today with a `2.X` series release of the provider, please file a new issue!

**Closed by rileykarson** 2019-06-25 21:28 UTC
Labels: bug, upstream
