### ISSUE TITLE
google_composer_environment fails with `Http error message: BAD REQUEST`

### ISSUE THREAD

**Issue by jaksky** [terraform-providers/terraform-provider-google#5244] opened 2019-12-20 12:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.18
+ provider.google v3.3.0

### Affected Resource(s)

* google_composer_environment

### Terraform Configuration Files

```tf
variable "project" {
  default = "procect-XY"
}

variable "region" {
  default = "us-central1"
}

variable "zone" {
  default = "us-central1-a"
}

resource "google_composer_environment" "airflow" {
  provider = google-beta
  name   = var.env
  region = var.region
  project = var.project
  config {
    node_count = 3
    node_config {
      zone         = var.zone
      machine_type = "n1-standard-2"
      disk_size_gb = 50
    }
    software_config {
      python_version = 3
      image_version  = "composer-1.7.1-airflow-1.10.2"
    }
  }
  labels = {
    env = var.env
  }
}
```

### Debug Output

Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 3, message: Http error status code: 400
Http error message: BAD REQUEST
Additional errors:
        {"ResourceType":"appengine.v1.version","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Legacy health checks are no longer supported for the App Engine Flexible environment. Please remove the 'health_check' section from your app.yaml and configure updated health checks. For instructions on migrating to split health checks see https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks","status":"INVALID_ARGUMENT","details":[],"statusMessage":"Bad Request","requestPath":"https://appengine.googleapis.com/v1/apps/he80a86dc0ef9d872-tp/services/default/versions","httpMethod":"POST"}}

  on airflow.tf line 8, in resource "google_composer_environment" 

### Expected Behavior

Create composer environment

### Actual Behavior

Environment creation failed

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by emilymye** [comment] 2019-12-23 17:01
Looks like this might be from the upstream API: https://issuetracker.google.com/146592602

**Comment by emilymye** [comment] 2019-12-30 21:49
@jaksky im going to go ahead and close this since Im not sure we can do anything about this in Terraform and its being tracked in the upstream issue. If it persists or you have other questions, feel free to reopen!

**Closed by emilymye** 2019-12-30 21:49 UTC
Labels: upstream

**Comment by jaksky** [comment] 2020-01-06 11:03
That is correct, I found later that even `gcloud` is not able to create an environment so seemed as internal GCP issue

**Comment by poligraph** [comment] 2020-01-22 10:53
it's only reproducible if image_version `composer-1.7.1-airflow-1.10.2`  is used , if use `composer-1.8.3-airflow-1.9.0` - I can create composer with no issues.
