### ISSUE TITLE
Notebooks API support

### ISSUE THREAD

**Issue by gogasca** [terraform-providers/terraform-provider-google#6494] opened 2020-06-01 05:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We recently launched Notebooks API (Beta), which allows you to create and manage Google Cloud AI Platform Notebooks, we provide a sdk via "gcloud beta notebooks" and REST API
Currently for Terraform we use the Google Cloud Compute Engine but want to support this natively.
https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/tools/terraform

### New or Affected Resource(s)

* google_notebooks

### Potential Terraform Configuration

```tf
resource "random_id" "instance_id" {
  byte_length = 8
}

resource "google_notebooks_instance" "default" {
  name         = "vm-${random_id.instance_id.hex}"
  machine_type = var.instance_type
  location         = var.location

  boot_disk {
    initialize_params {
      image = "deeplearning-platform-release/tf-ent-latest-gpu" # TensorFlow Enterprise
      size  = 50                                                // 50 GB Storage
    }
  }

  network_interface {
    network = "default"
    access_config {}
  }

  guest_accelerator {
    type  = var.gpu_type
    count = var.gpu_count
  }

  scheduling {
    automatic_restart   = true
    on_host_maintenance = "TERMINATE"
  }

  service_account {
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }
}
```

### References

https://cloud.google.com/sdk/gcloud/reference/beta/notebooks
https://cloud.google.com/ai-platform/notebooks/docs/reference/rest

* #0000

I would like to get information in how to get started, I will be willing to create this module.

**Comment by danawillow** [comment] 2020-06-01 18:22
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5879

**Closed by danawillow** 2020-06-01 18:22 UTC
Labels: enhancement, new-resource, size/M
