### ISSUE TITLE
Add support for managing only AuditConfig in IAM policy

### ISSUE THREAD

**Issue by marcin-kolda** [terraform-providers/terraform-provider-google#3084] opened 2019-02-19 20:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently [auditConfigs](https://cloud.google.com/logging/docs/audit/configure-data-access#config-api) can be only configured using [google_iam_policy](https://www.terraform.io/docs/providers/google/d/google_iam_policy.html) data source, which requires `binding` in IAM policy as well. We would like to configure `auditConfigs` without IAMs (they would be configured separately) or with using `google_project_iam_member` resource.

### New or Affected Resource(s)

* google_project_iam_audit_config

### Potential Terraform Configuration

Terraform configuration should be the same as `audit_config` part in [google_iam_policy](https://www.terraform.io/docs/providers/google/d/google_iam_policy.html) data source.

### References

* #1531

**Comment by paddycarver** [comment] 2019-02-19 23:22
We actually [have support](https://github.com/terraform-providers/terraform-provider-google/blob/v2.0.0/google/provider.go#L225) for that in 2.0.0, I was just neglectful and forgot to document it on the website. (See #3066.) I'll get that info up on the website.

**Comment by rileykarson** [comment] 2019-02-25 23:53
I'm going to close this as a dupe of https://github.com/terraform-providers/terraform-provider-google/issues/3066 since that tracks adding the docs, and the fine-grained resource already exists.

If you're interested in managing this on non-project IAM policies (eg org, billing, subnetwork, etc) please file another issue! (And let me know if I closed this in error.)

**Closed by rileykarson** 2019-02-25 23:53 UTC
Labels: documentation
