### ISSUE TITLE
google_logging_metric is missing 'unit' field

### ISSUE THREAD

**Issue by algermissen** [terraform-providers/terraform-provider-google#4383] opened 2019-08-31 09:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The google_logging_metric resource should support the 'unit' field.

### New or Affected Resource(s)

* google_logging_metric

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by megan07** [comment] 2019-09-05 16:56
hi @algermissen 

Thanks for opening this issue :)

Taking a look through this appears to be a duplicate of #3881  - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3881 for updates?

Thanks!

**Closed by megan07** 2019-09-05 16:56 UTC
Labels: enhancement
