### ISSUE TITLE
Incorrect documentation for google_project_iam_policy

### ISSUE THREAD

**Issue by lobeck** [terraform-providers/terraform-provider-google#335] opened 2017-08-17 13:48 UTC
This is a refresh of https://github.com/hashicorp/terraform/issues/15243

The documentation states:

    policy_data - (Required) The google_iam_policy data source that represents the IAM policy that will be applied to the project. The policy will be merged with any existing policy applied to the project.

We've got multiple modules manipulating the same project and i don't like the idea of merging all policies into one when in fact they are used by different modules. Note here, that the modules are independent and don't share the same state file.

The resources look like this and sometimes the policies get merged, sometimes replaced which is rather annoying because getting the correct configuration is not reliable.

So this seems to be either an issue with the state file or the update logic. Actually no state would be required for this, as it has to refresh the project anyway to allow for outside manipulation.

    resource "google_service_account" "certbot" {
      account_id   = "certbot"
      display_name = "certbot"
    }
    
    data "google_iam_policy" "certbot" {
      binding {
        role = "roles/editor"
    
        members = [
          "serviceAccount:${google_service_account.certbot.email}",
        ]
      }
    }
    
    resource "google_project_iam_policy" "foobar-1337" {
      project     = "foobar-1337"
      policy_data = "${data.google_iam_policy.certbot.policy_data}"
    }

**Comment by paddycarver** [comment] 2017-08-25 00:53
This feels like a duplicate of #72 and #58. Essentially, _for the moment_ `google_project_iam_policy` does its best to merge existing policies with those in your config. As you've noticed, though, this starts breaking down and becoming confusing when modules get involved.

Our recommendation at this time is:

* if you're looking to make sure the IAM policy for the project is _exactly_ what you have in your config (in a single module)--nothing more, nothing less, no variation--then use `google_project_iam_policy` and set the `authoritative` property to `true`. In the near-ish future, there will no longer be a non-authoritative option for the `google_project_iam_policy`.
* if you're looking for the merging behaviour, I recommend `google_project_iam_binding` and `google_project_iam_member`, which will let you manage a single role or a single role/member pairing. Note that any roles (or role/member pairs if you're using `google_project_iam_member`) that _don't_ match your config _will be ignored_, not undone.
* If you're looking for the merging behaviour but want any bindings not created by Terraform to be undone/removed, there is currently no way to support that, and I honestly can't see how that would happen reliably.

Hopefully this sheds some light. I'm going to close out this issue, but if you have more questions, think I didn't understand, or would like to discuss this more, please feel free to reply and we'll reopen this.

**Closed by paddycarver** 2017-08-25 00:53 UTC

**Comment by smileprem** [comment] 2018-03-30 20:16
Hi - How to achieve `authoritative` behavior with `google_project_iam_member` ?

**Comment by rosbo** [comment] 2018-04-03 19:51
You can't. `*_iam_member` resource are not authoritative by design.

Here is how each iam resources differ from each other:

`*_iam_policy`: Authoritative. Sets the IAM policy for an entity and replaces any existing policy already attached.
`*_iam_binding`: Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the entity are preserved.
`*_iam_member`: Non-authoritative. Updates the IAM policy to grant a role to a new member. Other members for the role for the entity are preserved.

**Comment by smileprem** [comment] 2018-04-03 20:56
Thanks @rosbo for the clarification

**Comment by rosbo** [comment] 2018-04-03 21:25
You're welcome. We updated the docs in #1227 to make this clearer.
