### ISSUE TITLE
google_endpoints_service  panic: time: missing Location in call to Time.In 

### ISSUE THREAD

**Issue by dontgetit** [terraform-providers/terraform-provider-google#6880] opened 2020-07-29 16:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

 Terraform v0.12.20
Initializing provider plugins...
 - Checking for available provider plugins...
 - Downloading plugin for provider "http" (hashicorp/http) 1.2.0...
 - Downloading plugin for provider "google" (hashicorp/google) 3.32.0...
 - Downloading plugin for provider "google-beta" (hashicorp/google-beta) 3.32.0...

### Affected Resource(s)

* google_endpoints_service

### Terraform Configuration Files

```tf
resource "google_endpoints_service" "test_openapi_service" {
  service_name   = "test-api.endpoints.test-project.cloud.goog"
  project        = "test-project"
  openapi_config = file("test-api.yml")
}
```

### Debug Output

```
2020-07-29T10:25:09.140Z [DEBUG] plugin: plugin process exited: path=/builds/pit-iaas/customer-registry/.terraform/plugins/linux_amd64/terraform-provider-google_v3.32.0_x5 pid=197 error="exit status 2"
```
### Panic Output
```
 panic: time: missing Location in call to Time.In
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: 
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: goroutine 93 [running]:
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: time.Time.In(...)
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: 	/opt/goenv/versions/1.14.5/src/time/time.go:1126
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: github.com/terraform-providers/terraform-provider-google/google.predictServiceId(0xc0009e68c0, 0x23946a0, 0xc0009e8000, 0xc0003e4c80, 0xc0009e68c0)
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/google/resource_endpoints_service.go:157 +0x572
 2020-07-29T12:34:58.975Z [DEBUG] plugin.terraform-provider-google_v3.32.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.schemaMap.Diff(0xc0003c13b0, 0xc0006ae0f0, 0xc000544e70, 0x284bf70, 0x23946a0, 0xc0009e8000, 0x2c2b900, 0x0, 0xffffffffffffffff, 0x0)
```

### Expected Behavior

Terraform deploys new Google Endpoints spec. 

### Actual Behavior
Terraform crashes

### Steps to Reproduce

Running  `terraform plan`  with any change to the the openAPI spec for Endpoints is resulting in a terraform crash. 

That would be running terraform in a docker container derived from image  `hashicorp/terraform:0.12.20`  which I think won't have any timezone files.

### Important Factoids

#6840  was trying to resolve the same problem, I think,  but doesn't seem to have helped me  for some reason.
### References

* #6840

**Comment by edwardmedia** [comment] 2020-07-29 17:34
@dontgetit can you post the full debug log? Thanks

**Comment by dontgetit** [comment] 2020-07-29 21:01
@edwardmedia   I recreated the issue  in cloud shell  by creating a simple endpoints resource. If I remove the tzdata package from cloud shell  - then I get the problem when trying to plan any change -  the crash.log is in this [gist](https://gist.github.com/dontgetit/46f76c4cbbd9b8152104f39d0d77c37f)    Thanks.

**Comment by rileykarson** [comment] 2020-07-30 19:14
Closing as a dupe of #6840. That fix will release on Monday in `3.33.0`. While `3.32.0` released since that change was merged, we tend to cut release branches on the prior Wednesday to give us some flexibility to patch in changes if required.

If you're still encountering the issue on `3.33.0+`, please feel free to comment here or file again!

**Closed by rileykarson** 2020-07-30 19:14 UTC
Labels: bug, crash
