### ISSUE TITLE
Not able to create multiple SQL db instance on private network

### ISSUE THREAD

**Issue by igoooor** [terraform-providers/terraform-provider-google#4249] opened 2019-08-14 11:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.6
+ provider.google-beta v2.12.0

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
provider "google-beta" {
  region = "europe-west6"
  zone   = "europe-west6-a"
  project = "thegoodone35753"
}

resource "google_compute_network" "private_network" {
  count = 1

  provider = "google-beta"

  name       = "private-network"
}
resource "google_compute_global_address" "private_ip_address" {
  count = 1

  provider = "google-beta"

  name          = "private-ip-address"
  purpose       = "VPC_PEERING"
  address_type = "INTERNAL"
  prefix_length = 20
  network       = google_compute_network.private_network.0.self_link

  depends_on = [
    "google_compute_network.private_network",
  ]
}
resource "google_service_networking_connection" "private_vpc_connection" {
  count = 1

  provider = "google-beta"

  network       = google_compute_network.private_network.0.self_link
  service       = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.private_ip_address.0.name]

  depends_on = [
    "google_compute_global_address.private_ip_address",
  ]
}

resource "google_sql_database_instance" "simple" {
  count = 2

  name = "yodoudildou-${count.index}-xyz"
  region = "europe-west6"
  database_version = "MYSQL_5_7"

  settings {
    disk_autoresize = true
    tier = "db-g1-small"
    ip_configuration {
      ipv4_enabled = "true"
      private_network = google_compute_network.private_network.0.self_link
    }
  }

  provider = "google-beta"

  timeouts {
    create = "60m"
  }

  depends_on = [
    "google_service_networking_connection.private_vpc_connection",
  ]
}
```

### Debug Output

Here is the part of the logs where we can see the creation failing.
But it doesn't give more informations.
https://gist.github.com/igoooor/4c15370408c2f0d9647058786488d4ce

### Expected Behavior

2 instances of "google_sql_database_instance.simple" should be created.

### Actual Behavior

only 1 instance is created, the 2nd produces an error.
terraform produces the following ouput:
```
Error: Error waiting for Create Instance: 
  on modules/2_mysql/main.tf line 12, in resource "google_sql_database_instance" "simple":
  12: resource "google_sql_database_instance" "simple" {
```
The google cloud console lists the 2 instances.
1 is green, 1 is red (in error), and the error says "An unknown error occurred".

If I change the configuration to entirely remove the private network and use the default one, the 2 instances are correctly created.
With the private network, when the 2nd instance is in error, If I manually create another SQL instance on the same private network from the Google Cloud Console, it works.
It's only with private network, created from terraform.

Edit:
I did another few tries, and here is what I managed to do:
* start from a clean environment
* `terraform apply` everything
* 1 instance is working, 1 is in error
* manually delete the 2 instances from GCP console
* manually remove them from terraform state
* `terraform apply` once more
* 2 instances are working

But I can't explain why it's working like that. It's not a solution, but I hope this helps you to find out what could be wrong

* #3278 looks similar, but I still have 1 instance working correctly, so the configuration of the private network looks correct.

**Comment by slevenick** [comment] 2019-09-16 17:24
Hey, sorry about the long delay.

Looks like this is a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3069 and unfortunately, nothing has changed since then. Going to close this out in favor of that issue.

**Closed by slevenick** 2019-09-16 17:24 UTC
Labels: bug
