### ISSUE TITLE
Python3.7 Runtime Support for Google Cloud Functions

### ISSUE THREAD

**Issue by paul-opsguru** [terraform-providers/terraform-provider-google#2530] opened 2018-11-27 03:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Hi,

It would be useful to have Python3.7.x runtime support for the existing Google Cloud Function Terraform provider.

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

Runtime selector or something similar would be great:
```tf
resource "google_cloudfunctions_function" "test" {
    name                      = "test"
    entry_point             = "helloGET"
    runtime                   = "Python37"
    available_memory_mb     = 128
    timeout                   = 60
    project                   = "${var.project_name}"
    region                    = "${var.region}"
    trigger_http              = true
    source_archive_bucket     = "${google_storage_bucket.bucket.name}"
    source_archive_object     = "${google_storage_bucket_object.archive.name}"
    labels                    = "${var.labels}"
}
```

### References

https://cloud.google.com/functions/docs/concepts/python-runtime

**Comment by paddycarver** [comment] 2018-11-27 09:18
This seems to be a dupe of #2033. If you believe it to be distinct, feel free to comment, and we can discuss reopening it.

**Closed by paddycarver** 2018-11-27 09:18 UTC
Labels: enhancement
