### ISSUE TITLE
Remove schema.SchemaConfigModeAttr usages

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3491] opened 2019-04-25 15:31 UTC
During testing with the `0.12` SDK, we identified https://github.com/hashicorp/terraform/issues/20505, an issue that meant `Computed` + `Optional` nested blocks could no longer be specified as empty. It turns out that was unintentional behaviour by the SDK, and will no longer be supported going forwards. https://github.com/hashicorp/terraform/pull/20837 introduced a temporary fixup that can mitigate this- but we need to be sparing about using it, as we'll likely need to remove it in the future in any case where we do.

As such, as part of releasing our first `0.12`-compatible release we had to evaluate whether each of our `Computed` + `Optional` TypeList / TypeSet fields could be explicitly set to the empty list to assert that no elements of that type existed.

In most cases, APIs would revert to a default value leading to a diff. This _could_ be a useful behaviour in some use cases during interactive use but we  didn't preserve it. Terraform was entering an invalid state when used in this manner.

In some cases though, fields had a distinct empty value that would be reached by sending an explicit empty list in the request vs not sending one at all. In those cases, we had to apply this fixup.

By `3.0.0` , we should either remove all occurences of the fixup (whether with breaking changes or by using a future fix from the SDK) or guarantee that they'll be preserved for ~a year until `4.0.0`.

**Comment by mxk** [comment] 2019-08-22 12:31
Is this the reason we can't currently use this syntax in `google_compute_instance`?

```
  network_interface {
    subnetwork    = google_compute_subnetwork.default.self_link
    access_config = var.public-ip ? [{
      network_tier = "STANDARD"
    }] : []
  }
```

The error is:

> An argument named "access_config" is not expected here. Did you mean to define
a block of type "access_config"?

**Comment by rileykarson** [comment] 2019-08-22 16:19
Hey @mxk!

Using SchemaConfigModeAttr on the field *would* make that syntax work, but we don't intend to apply the fixup to the field as it isn't necessary. You can achieve the same behaviour with a [`dynamic`](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) block.

**Comment by paddycarver** [comment] 2020-01-21 13:08
Going to close this as a dupe of #4326.

**Closed by paddycarver** 2020-01-21 13:08 UTC
Labels: breaking-change, technical-debt
