### ISSUE TITLE
google_bigquery_dataset_iam_member requires undocumented project parameter

### ISSUE THREAD

**Issue by preston-hf** [terraform-providers/terraform-provider-google#6769] opened 2020-07-09 15:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_bigquery_dataset_iam_member

### Problem

If `project` is a supported variable, it should be documented. As it seems now, you would specify the project by referencing a dataset resource's id field, which matches the example syntax. Unfortunately this doesn't work, and if you don't specify a project, you receive an error.

* #6553

**Comment by edwardmedia** [comment] 2020-07-09 17:03
@preston-hf  I am able to run below code without adding the **project**. Am I missing the point you make? 

```tf
resource "google_bigquery_dataset_iam_member" "editor" {
  dataset_id = google_bigquery_dataset.dataset.dataset_id
  role       = "roles/bigquery.dataEditor"
  member     = "user:myemail@gmail.com"
}
resource "google_bigquery_dataset" "dataset" {
  dataset_id                  = "issue6769dataset"
  friendly_name               = "test"
  description                 = "This is a test description"
  location                    = "EU"
  default_table_expiration_ms = 3600000
  labels = {
    env = "default"
  }
  access {
    role          = "OWNER"
    user_by_email = google_service_account.bqowner.email
  }
  access {
    role   = "READER"
    domain = "hashicorp.com"
  }
}
resource "google_service_account" "bqowner" {
  account_id = "bqowner"
}
```

**Comment by preston-hf** [comment] 2020-07-09 17:38
Do you have a default project set on your provider possibly?

**Comment by preston-hf** [comment] 2020-07-09 17:40
I have been getting this error: 
```
Error: project: required field is not set
```
Pretty standard, I get it all of the time. The main issue here is you can't specify the project a dataset is in by using the full dataset id, only the dataset name without the project. Also, the project var is totally undocumented.

**Comment by edwardmedia** [comment] 2020-07-10 02:16
@preston-hf can you provide the config that will fail? Thanks

**Comment by edwardmedia** [comment] 2020-07-13 19:39
@preston-hf I do have below environment variable.  
`GOOGLE_PROJECT=`

**Comment by edwardmedia** [comment] 2020-07-15 21:11
@preston-hf is this still an issue with you? If yes, could you please provide the config so I can repro it?

**Comment by preston-hf** [comment] 2020-07-16 14:54
The issue still exists, yes. Unfortunately I can't provide proprietary config here and I don't have more time to track this down. The quick fix would be to document that this resource accepts the project parameter.

**Comment by edwardmedia** [comment] 2020-07-16 15:06
@preston-hf Using above code, I tested the resource does accept `project`. I guess the issue may be caused by other reasons. Without the code, it is difficult to guess. I am closing this issue at this moment. Please feel free to reopen it if we could have code to repro it. Thanks

**Closed by edwardmedia** 2020-07-16 15:06 UTC
Labels: bug

**Comment by preston-hf** [comment] 2020-07-23 20:51
As I said, the docs need to be updated to show that they accept a project parameter. I do understand that it accepts one, I am using it.
