### ISSUE TITLE
google_monitoring_alert_policy flags label changes on every run

### ISSUE THREAD

**Issue by craigwatson** [terraform-providers/terraform-provider-google#5358] opened 2020-01-09 12:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.18
+ provider.google v3.4.0
+ provider.google-beta v3.4.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* google_monitoring_alert_policy

### Terraform Configuration Files

```tf
resource "google_monitoring_alert_policy" "alert_policy" {
  count                 = var.lb_stackdriver_endpoint_check == "true" ? local.enabled_count * 1 : 0
  display_name          = "Uptime Check - ${var.name}-${terraform.workspace}"
  notification_channels = var.stackdriver_notify_channels
  combiner              = "OR"
  user_labels           = {}
  conditions {
    display_name = "Uptime Health Check"
    condition_threshold {
      filter          = "metric.type=\"monitoring.googleapis.com/uptime_check/check_passed\" resource.type=\"uptime_url\" metric.label.\"check_id\"=\"${basename(google_monitoring_uptime_check_config.endpoint[0].id)}\""
      duration        = "60s"
      comparison      = "COMPARISON_GT"
      threshold_value = 1.0
      trigger {
        count = 1
      }
      aggregations {
        alignment_period     = "1200s"
        cross_series_reducer = "REDUCE_COUNT_FALSE"
        group_by_fields      = ["resource.*"]
        per_series_aligner   = "ALIGN_NEXT_OLDER"
      }
    }
  }
}
```

### Expected Behavior

* No changes

### Actual Behavior

```
Terraform will perform the following actions:

  # google_monitoring_alert_policy.alert_policy[0] will be updated in-place
  ~ resource "google_monitoring_alert_policy" "alert_policy" {
        combiner              = "OR"
        creation_record       = [
            {
                mutate_time = "2019-12-09T10:27:40.916869396Z"
                mutated_by  = "REDACTED"
            },
        ]
        display_name          = "REDACTED"
        enabled               = true
        id                    = "REDACTED"
      + labels                = (known after apply)
        name                  = "REDACTED"
        notification_channels = [
            "REDACTED",
        ]
        project               = "REDACTED"
        user_labels           = {}

        conditions {
            display_name = "Uptime Health Check"
            name         = "REDACTED"

            condition_threshold {
                comparison      = "COMPARISON_GT"
                duration        = "60s"
                filter          = "metric.type=\"monitoring.googleapis.com/uptime_check/check_passed\" resource.type=\"uptime_url\" metric.label.\"check_id\"=\"REDACTED\""
                threshold_value = 1

                aggregations {
                    alignment_period     = "1200s"
                    cross_series_reducer = "REDUCE_COUNT_FALSE"
                    group_by_fields      = [
                        "resource.*",
                    ]
                    per_series_aligner   = "ALIGN_NEXT_OLDER"
                }

                trigger {
                    count   = 1
                    percent = 0
                }
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Steps to Reproduce

1. `terraform apply`

**Comment by edwardmedia** [comment] 2020-01-09 20:33
@craigwatson What do you mean "No changes" for the Expected Behavior? Can you specify the steps how to repro your issue? Also it would be very helpful if you can attach a full debug log. Thanks

**Comment by craigwatson** [comment] 2020-01-09 21:18
@edwardmedia By "no changes" I mean that no changes should be flagged by Terraform, as nothing is actually changing. 

I believe that this may be a bug introduced by 3.4.0 (where removed fields were marked as computed - see #5313 - specifically [this commit),](https://github.com/terraform-providers/terraform-provider-google/pull/5313/files#diff-92d943eb5aad07f2fc62a04b2e2b8132) as I've only started to see the behaviour after upgrading to 3.4.0.

I'm unsure of the steps to reproduce, but our codebase has been through several versions of the `google` provider - from 2.x to 3.0.0 to 3.3.0 to 3.4.0 so there's every chance that a removed field is hanging around in our state.

**Comment by courteouselk** [comment] 2020-01-10 07:34
We have the same issue.  I can keep running `terraform apply` over and over again, with `labels` argument causing the delta.

**Comment by edwardmedia** [comment] 2020-01-10 22:36
@craigwatson I see what you said. Here is what I got repeating `tf apply`. It seems a bug to me. 
```
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by edwardmedia** [comment] 2020-01-11 01:47
Reassign as it is too late for this week

**Comment by chrisst** [comment] 2020-01-13 19:20
Closing as a duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/5339

**Closed by chrisst** 2020-01-13 19:20 UTC
Labels: bug
