### ISSUE TITLE
BigQuery persistent function resource

### ISSUE THREAD

**Issue by Fryuni** [terraform-providers/terraform-provider-google#4740] opened 2019-10-23 21:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

To avoid repetition defining views it would be nice to have a resource to create persistent functions, or routines as they are named on the API resource.

### New or Affected Resource(s)

* google_bigquery_routine

### Potential Terraform Configuration

```tf

resource "google_bigquery_routine" "ensure_integer" {
  dataset_id = google_bigquery_dataset.my_dataset.dataset_id
  routine_id = "ensure_integer"

  body = "IF(REGEXP_CONTAINS(CAST(x AS STRING), r'\\D'),NULL,CAST(x AS INT64))"
  type = "SCALAR_FUNCTION"
  language = "SQL"

  // Arguments as a list of maps like the API, maybe this could be a map (name>kind)...
  arguments = [
    {
      name = "x"
      kind = "ANY_TYPE" // It is "argumentKind" on the API, but I think it is unnecessary to add the full name here
    },
  ]

  // Return type block like the API definition here https://cloud.google.com/bigquery/docs/reference/rest/v2/StandardSqlDataType
  returnType {
    typeKind = "INT64"
  }
}

```

### References

* Routines API docs: https://cloud.google.com/bigquery/docs/reference/rest/v2/routines#resource-routine

**Comment by paddycarver** [comment] 2019-12-06 21:13
Closing this as a duplicate of #4619.

**Closed by paddycarver** 2019-12-06 21:13 UTC
Labels: enhancement, new-resource, size/M
