### ISSUE TITLE
bigtable instance level IAM binding or role members

### ISSUE THREAD

**Issue by Charles546** [terraform-providers/terraform-provider-google#3750] opened 2019-05-30 20:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I couldn't find a resource in the google provider for terraform to add IAM bindings for bigtable on the instance level.

I am able to add role members on instance level through gcloud console UI. I am assuming it should be possible to do it through API.

### New or Affected Resource(s)

* google_bigtable_instance_iam_member
* google_bigtable_instance_iam_binding

### Potential Terraform Configuration

```tf

resource "google_bigtable_instance_iam_member" "test" {
  bigtable_instance_name = "test"
  role                 = "roles/bigtable.user"
  members            = [
    "serviceAccount:xxxx",
    "group:xxxx",
  ]
}

```

**Comment by danawillow** [comment] 2019-06-29 00:58
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/3488.

**Closed by danawillow** 2019-06-29 00:58 UTC
Labels: enhancement, new-resource
