### ISSUE TITLE
Add google_spanner_instance data source

### ISSUE THREAD

**Issue by minaf1** [terraform-providers/terraform-provider-google#6369] opened 2020-05-13 18:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
+ Terraform v0.12.18
+ provider.google v3.20.0

### Affected Resource(s)

* google_spanner_instance

### Terraform Configuration Files

```tf
data "google_spanner_instance" "spanner_instance" {
  config       = "regional-us-central1"
  display_name = "Test Spanner Instance"
  num_nodes   = 1
}

resource "google_spanner_database" "database" {
  instance = data.google_spanner_instance.spanner_instance
  name     = "database"
}

```

### Debug Output
The provider provider.google does not support data source "google_spanner_instance".

### Expected Behavior
It should detect that an spanner instance already exists and go forward creating the spanner database.

### Actual Behavior
The error mentioned above.

### Steps to Reproduce
terraform validate or terraform plan both produce the error above

### References
I've been trying to use the documentation mentioned here: https://www.terraform.io/docs/modules/composition.html
more specifically, I'm trying to apply the conditional creation of objects section in the link.

**Comment by venkykuberan** [comment] 2020-05-13 21:46
@minaf1 data_source isn't available yet for spanner_instance. I will change this issue as an enhancement which will be triaged and taken up for work.

**Comment by danawillow** [comment] 2020-05-18 18:11
Duplicate of https://github.com/terraform-providers/terraform-provider-google/issues/1866

**Closed by danawillow** 2020-05-18 18:11 UTC
Labels: bug, enhancement
